'use strict';

// electron/sync/handlers/albums.js — generated by scripts/generate-handlers.js
// IPC handlers for the albums table (install-scoped).
// Channels: albums:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.albums.*
//
// Install-scoped: data is shared across all stations. No station_id filtering
// on list. withMutation receives station_id: null per [N-89].

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE    = 'albums';
const PATCHABLE = ["title","artist_id","year","updated_at"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[albums] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'install') {
    throw new Error(`[albums] expected install-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function albumsList(db, opts) {
  const { limit = 500, offset = 0 } = opts || {};
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL ORDER BY rowid LIMIT ? OFFSET ?`
  ).all(limit, offset);
}

function albumsGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function albumsCreate(db, payload) {
  validateScope();
  if (payload.station_id != null) {
    throw new Error(`[albums] station_id must not be set on install-scoped create (got ${payload.station_id})`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     null,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (title, artist_id, year, created_at, uuid, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?)`
    ).run(row.title, row.artist_id, row.year, row.created_at, row.uuid, row.updated_at, row.deleted_at);
  });
  return albumsGet(db, uuid);
}

function albumsUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[albums] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[albums] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[albums] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     null,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return albumsGet(db, uuid);
}

function albumsDelete(db, uuid) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[albums] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     null,
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}

function albumsFindOrCreate(db, { title, artistId, year }) {
  validateScope();
  const existing = artistId != null
    ? db.prepare(`SELECT * FROM ${TABLE} WHERE title = ? AND artist_id = ? AND deleted_at IS NULL`).get(title, artistId)
    : db.prepare(`SELECT * FROM ${TABLE} WHERE title = ? AND deleted_at IS NULL`).get(title);
  if (existing) {
    if (year != null) {
      let uuid = existing.uuid;
      if (!uuid) {
        uuid = crypto.randomUUID();
        db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(uuid, existing.id);
      }
      return albumsUpdate(db, uuid, { year });
    }
    return existing;
  }
  return albumsCreate(db, { title, artist_id: artistId ?? null, year: year ?? null });
}

// ── IPC installation ──────────────────────────────────────────────────────────

function installAlbums(ipcMain, db) {
  ipcMain.handle('albums:list', (_, opts) => {
    try { return { ok: true, rows: albumsList(db, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('albums:get-by-id', (_, uuid) => {
    try { return { ok: true, row: albumsGet(db, uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('albums:create', (_, payload) => {
    try { return { ok: true, row: albumsCreate(db, payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('albums:update', (_, uuid, patch) => {
    try { return { ok: true, row: albumsUpdate(db, uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('albums:delete', (_, uuid) => {
    try { return { ok: true, ...albumsDelete(db, uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[albums] handlers installed');
}

module.exports = {
  installAlbums,
  validateScope,
  albumsList,
  albumsGet,
  albumsCreate,
  albumsUpdate,
  albumsDelete,
  albumsFindOrCreate,
};
