'use strict';

// electron/sync/handlers/announcements.js — generated by scripts/generate-handlers.js
// IPC handlers for the announcements table (station-scoped).
// Channels: announcements:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.announcements.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const libraryAsset = require('./library_asset');
const { REGISTRY } = require('../synced-tables');
// v47 — an announcement is the ASSET; WHEN it plays lives in announcement_schedule. Deleting the
// asset has to take its entries with it.
const { deleteEntriesForAnnouncement } = require('./announcement_schedule');

const TABLE              = 'announcements';
const HAS_STATION_ID_COL = true;
const PATCHABLE          = ["title","file_path","trigger_time","days","duck_music","resume_music","duck_level","is_active","last_played_at","updated_at","trigger_type","close_offset_min"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[announcements] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'station') {
    throw new Error(`[announcements] expected station-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function announcementsList(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function announcementsGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

// ── THE LIBRARY MIRROR (step 5, docs/library-current-state.md — Option 1) ──────────────────────
//
// An announcement is an element in the ONE typed library, so every write here also writes its
// `library_asset` row. The panels are filtered views over that library, and a view can only show
// what the writer put there.
//
// TWO RULES THIS FOLLOWS, both learned the hard way:
//
//   READER AND WRITER LAND TOGETHER. Step 4a flipped a reader onto library_asset while nothing wrote
//   it, which left rotation reading a snapshot frozen at v50. Reverted. The panel read in step 4 is
//   only safe because this exists.
//
//   ONE ATOMIC UNIT. This runs INSIDE the caller's withMutation, so the announcement row and its
//   asset row commit or roll back together — better-sqlite3 nests transactions as SAVEPOINTs, and
//   mutation-writer pushes a context stack so the asset mutation is journalled as a child of the
//   announcement's. They can never disagree, which is the whole failure mode being designed out.
//
// The uuid is SHARED with the announcement — the same contract v50 used for songs and spots, and
// what makes `la.uuid = a.uuid` the join for every reader.
function mirrorToLibrary(db, row, op) {
  // A title is required by assetCreate, and an untitled announcement should still be findable in the
  // library rather than rejected at the door.
  const title = row.title || (row.file_path ? String(row.file_path).split(/[\\/]/).pop() : null) || 'Announcement';
  const existing = db.prepare('SELECT uuid, deleted_at FROM library_asset WHERE uuid = ?').get(row.uuid);

  if (op === 'delete') {
    if (existing && !existing.deleted_at) libraryAsset.assetDelete(db, row.uuid);
    return;
  }
  if (!existing) {
    libraryAsset.assetCreate(db, {
      uuid: row.uuid, type: 'ANNOUNCEMENT', title, file_path: row.file_path ?? null,
    });
    return;
  }
  // assetUpdate carries its own no-op guard, so an unchanged title/path journals nothing.
  libraryAsset.assetUpdate(db, row.uuid, { title, file_path: row.file_path ?? null });
}

function announcementsCreate(db, payload) {
  validateScope();
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[announcements] station_id is required for station-scoped create`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     payload.station_id,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (title, file_path, trigger_time, days, duck_music, resume_music, duck_level, is_active, last_played_at, created_at, station_id, uuid, updated_at, deleted_at, trigger_type, close_offset_min) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(row.title, row.file_path, row.trigger_time, row.days, row.duck_music, row.resume_music, row.duck_level, row.is_active, row.last_played_at, row.created_at, row.station_id, row.uuid, row.updated_at, row.deleted_at, row.trigger_type ?? 'absolute', row.close_offset_min ?? 0);
    mirrorToLibrary(db, row, 'insert');
  });
  return announcementsGet(db, uuid);
}

function announcementsUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[announcements] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[announcements] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[announcements] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     existing.station_id,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
    mirrorToLibrary(db, updated, 'update');
  });
  return announcementsGet(db, uuid);
}

function announcementsDelete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[announcements] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     (stationId ?? existing.station_id),
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
    mirrorToLibrary(db, existing, 'delete');
  });
  // CASCADE, not a bridge: a deleted announcement must not leave live schedule entries pointing at
  // it. Referential cleanup the panel should never have to remember to do. Soft-deleted, so peers
  // converge on the same removal.
  deleteEntriesForAnnouncement(db, uuid, stationId ?? existing.station_id);
  return { ok: true };
}



function announcementsUpdateById(db, intId, patch) {
  validateScope();
  let existing = db.prepare(`SELECT * FROM ${TABLE} WHERE id = ? AND deleted_at IS NULL`).get(intId);
  if (!existing) throw new Error(`[announcements] row not found: id=${intId}`);
  if (!existing.uuid) {
    const uuid = crypto.randomUUID();
    db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(uuid, intId);
    existing = { ...existing, uuid };
  }
  return announcementsUpdate(db, existing.uuid, patch);
}

function announcementsDeleteById(db, intId) {
  validateScope();
  let existing = db.prepare(`SELECT * FROM ${TABLE} WHERE id = ? AND deleted_at IS NULL`).get(intId);
  if (!existing) return { ok: true };
  if (!existing.uuid) {
    const uuid = crypto.randomUUID();
    db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(uuid, intId);
    existing = { ...existing, uuid };
  }
  return announcementsDelete(db, existing.uuid, existing.station_id);
}

// ── IPC installation ──────────────────────────────────────────────────────────

function installAnnouncements(ipcMain, db) {
  const getDb = (typeof db === 'function') ? db : () => db;
  ipcMain.handle('announcements:list', (_, stationId, opts) => {
    try { return { ok: true, rows: announcementsList(getDb(), stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('announcements:get-by-id', (_, uuid) => {
    try { return { ok: true, row: announcementsGet(getDb(), uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('announcements:create', (_, payload) => {
    try { return { ok: true, row: announcementsCreate(getDb(), payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('announcements:update', (_, uuid, patch) => {
    try { return { ok: true, row: announcementsUpdate(getDb(), uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('announcements:delete', (_, uuid, stationId) => {
    try { return { ok: true, ...announcementsDelete(getDb(), uuid, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });


  ipcMain.handle('announcements:update-by-id', (_, intId, patch) => {
    try { return { ok: true, row: announcementsUpdateById(getDb(), intId, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('announcements:delete-by-id', (_, intId) => {
    try { return { ok: true, ...announcementsDeleteById(getDb(), intId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[announcements] handlers installed');
}

module.exports = {
  installAnnouncements,
  validateScope,
  announcementsList,
  announcementsGet,
  announcementsCreate,
  announcementsUpdate,
  announcementsDelete,
  announcementsUpdateById,
  announcementsDeleteById,
};
