'use strict';

// electron/sync/handlers/artists.js — generated by scripts/generate-handlers.js
// IPC handlers for the artists table (install-scoped).
// Channels: artists:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.artists.*
//
// Install-scoped: data is shared across all stations. No station_id filtering
// on list. withMutation receives station_id: null per [N-89].

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE    = 'artists';
const PATCHABLE = ["name","sort_name","gender","updated_at"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[artists] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'install') {
    throw new Error(`[artists] expected install-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function artistsList(db, opts) {
  const { limit = 500, offset = 0 } = opts || {};
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL ORDER BY rowid LIMIT ? OFFSET ?`
  ).all(limit, offset);
}

function artistsGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function artistsCreate(db, payload) {
  validateScope();
  if (payload.station_id != null) {
    throw new Error(`[artists] station_id must not be set on install-scoped create (got ${payload.station_id})`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     null,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (name, sort_name, gender, created_at, uuid, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?)`
    ).run(row.name, row.sort_name, row.gender, row.created_at, row.uuid, row.updated_at, row.deleted_at);
  });
  return artistsGet(db, uuid);
}

function artistsUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[artists] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[artists] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[artists] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     null,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return artistsGet(db, uuid);
}

function artistsFindOrCreateByName(db, name) {
  validateScope();
  if (!name || !name.trim()) throw new Error('[artists] name is required for findOrCreateByName');
  const existing = db.prepare(
    `SELECT * FROM ${TABLE} WHERE name = ? AND deleted_at IS NULL`
  ).get(name.trim());
  if (existing) return existing;
  return artistsCreate(db, { name: name.trim(), sort_name: name.trim() });
}

function artistsDelete(db, uuid) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[artists] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     null,
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}

// ── IPC installation ──────────────────────────────────────────────────────────

function installArtists(ipcMain, db) {
  const getDb = (typeof db === 'function') ? db : () => db;
  ipcMain.handle('artists:list', (_, opts) => {
    try { return { ok: true, rows: artistsList(getDb(), opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('artists:get-by-id', (_, uuid) => {
    try { return { ok: true, row: artistsGet(getDb(), uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('artists:create', (_, payload) => {
    try { return { ok: true, row: artistsCreate(getDb(), payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('artists:update', (_, uuid, patch) => {
    try { return { ok: true, row: artistsUpdate(getDb(), uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('artists:delete', (_, uuid) => {
    try { return { ok: true, ...artistsDelete(getDb(), uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('artists:find-or-create-by-name', (_, name) => {
    try { return { ok: true, row: artistsFindOrCreateByName(getDb(), name) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[artists] handlers installed');
}

module.exports = {
  installArtists,
  validateScope,
  artistsList,
  artistsGet,
  artistsCreate,
  artistsUpdate,
  artistsDelete,
  artistsFindOrCreateByName,
};
