'use strict';

// electron/sync/handlers/cart_slots.js — generated by scripts/generate-handlers.js
// IPC handlers for the cart_slots table (station-scoped).
// Channels: cart_slots:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.cartSlots.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE              = 'cart_slots';
const HAS_STATION_ID_COL = true;
const PATCHABLE          = ["slot_number","title","file_path","color","hotkey","updated_at"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[cart_slots] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'station') {
    throw new Error(`[cart_slots] expected station-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function cartSlotsList(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function cartSlotsGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function cartSlotsCreate(db, payload) {
  validateScope();
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[cart_slots] station_id is required for station-scoped create`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     payload.station_id,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (slot_number, title, file_path, color, hotkey, station_id, uuid, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(row.slot_number, row.title, row.file_path, row.color, row.hotkey, row.station_id, row.uuid, row.created_at, row.updated_at, row.deleted_at);
  });
  return cartSlotsGet(db, uuid);
}

function cartSlotsUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[cart_slots] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[cart_slots] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[cart_slots] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     existing.station_id,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return cartSlotsGet(db, uuid);
}

function cartSlotsDelete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[cart_slots] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     (stationId ?? existing.station_id),
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}

function cartSlotsUpsertBySlotNumber(db, stationId, slotNumber, payload) {
  validateScope();
  const existing = db.prepare(
    `SELECT * FROM ${TABLE} WHERE station_id = ? AND slot_number = ? AND deleted_at IS NULL`
  ).get(stationId, slotNumber);
  if (existing) {
    return cartSlotsUpdate(db, existing.uuid, payload);
  } else {
    return cartSlotsCreate(db, { station_id: stationId, slot_number: slotNumber, ...payload });
  }
}

function cartSlotsDeleteBySlotNumber(db, stationId, slotNumber) {
  validateScope();
  const existing = db.prepare(
    `SELECT * FROM ${TABLE} WHERE station_id = ? AND slot_number = ? AND deleted_at IS NULL`
  ).get(stationId, slotNumber);
  if (!existing) return { ok: true };
  return cartSlotsDelete(db, existing.uuid, stationId);
}


// ── IPC installation ──────────────────────────────────────────────────────────

function installCartSlots(ipcMain, db) {
  const getDb = (typeof db === 'function') ? db : () => db;
  ipcMain.handle('cart_slots:list', (_, stationId, opts) => {
    try { return { ok: true, rows: cartSlotsList(getDb(), stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('cart_slots:get-by-id', (_, uuid) => {
    try { return { ok: true, row: cartSlotsGet(getDb(), uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('cart_slots:create', (_, payload) => {
    try { return { ok: true, row: cartSlotsCreate(getDb(), payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('cart_slots:update', (_, uuid, patch) => {
    try { return { ok: true, row: cartSlotsUpdate(getDb(), uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('cart_slots:delete', (_, uuid, stationId) => {
    try { return { ok: true, ...cartSlotsDelete(getDb(), uuid, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('cart_slots:upsert-by-slot-number', (_, stationId, slotNumber, payload) => {
    try { return { ok: true, row: cartSlotsUpsertBySlotNumber(getDb(), stationId, slotNumber, payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('cart_slots:delete-by-slot-number', (_, stationId, slotNumber) => {
    try { return { ok: true, ...cartSlotsDeleteBySlotNumber(getDb(), stationId, slotNumber) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[cart_slots] handlers installed');
}

module.exports = {
  installCartSlots,
  validateScope,
  cartSlotsList,
  cartSlotsGet,
  cartSlotsCreate,
  cartSlotsUpdate,
  cartSlotsDelete,
  cartSlotsUpsertBySlotNumber,
  cartSlotsDeleteBySlotNumber,
};
