'use strict';

// electron/sync/handlers/categories.js — generated by scripts/generate-handlers.js
// IPC handlers for the categories table (station-scoped).
// Channels: categories:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.categories.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE              = 'categories';
const HAS_STATION_ID_COL = true;
const PATCHABLE          = ["code","name","color","spins_per_hour","priority","updated_at","overlay_kind","overlay_song_id","overlay_category_id","overlay_lead_in_sec","overlay_underlap_sec","overlay_active_hours"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[categories] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'station') {
    throw new Error(`[categories] expected station-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function categoriesList(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function categoriesGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function categoriesCreate(db, payload) {
  validateScope();
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[categories] station_id is required for station-scoped create`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     payload.station_id,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    // Honor an explicit id when provided (parallels the uuid-passthrough above). Used by the
    // cloud-staged-programming import to clone DJ Deniro's category scheme into OV's station with
    // the SAME integer ids, so the borrowed library's songs (which carry DJ's category_id) match
    // OV's clock_slots and fill rotation. Normal creates omit id → SQLite AUTOINCREMENT, as before.
    if (payload.id != null) {
      db.prepare(
        `INSERT INTO ${TABLE} (id, code, name, color, spins_per_hour, priority, station_id, uuid, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
      ).run(payload.id, row.code, row.name, row.color, row.spins_per_hour, row.priority, row.station_id, row.uuid, row.created_at, row.updated_at, row.deleted_at);
    } else {
      db.prepare(
        `INSERT INTO ${TABLE} (code, name, color, spins_per_hour, priority, station_id, uuid, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
      ).run(row.code, row.name, row.color, row.spins_per_hour, row.priority, row.station_id, row.uuid, row.created_at, row.updated_at, row.deleted_at);
    }
  });
  return categoriesGet(db, uuid);
}

function categoriesUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[categories] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[categories] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[categories] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     existing.station_id,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return categoriesGet(db, uuid);
}

function categoriesUpdateById(db, intId, patch) {
  let existing = db.prepare(`SELECT * FROM ${TABLE} WHERE id = ?`).get(intId);
  if (!existing) throw new Error(`[categories] row not found by id: ${intId}`);
  if (!existing.uuid) {
    const newUuid = crypto.randomUUID();
    db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(newUuid, intId);
    existing = { ...existing, uuid: newUuid };
  }
  return categoriesUpdate(db, existing.uuid, patch);
}

function categoriesDelete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[categories] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     (stationId ?? existing.station_id),
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}



// ── IPC installation ──────────────────────────────────────────────────────────

function installCategories(ipcMain, db) {
  const getDb = (typeof db === 'function') ? db : () => db;
  ipcMain.handle('categories:list', (_, stationId, opts) => {
    try { return { ok: true, rows: categoriesList(getDb(), stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('categories:get-by-id', (_, uuid) => {
    try { return { ok: true, row: categoriesGet(getDb(), uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('categories:create', (_, payload) => {
    try { return { ok: true, row: categoriesCreate(getDb(), payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('categories:update', (_, uuid, patch) => {
    try { return { ok: true, row: categoriesUpdate(getDb(), uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('categories:delete', (_, uuid, stationId) => {
    try { return { ok: true, ...categoriesDelete(getDb(), uuid, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('categories:update-by-id', (_, intId, patch) => {
    try { return { ok: true, row: categoriesUpdateById(getDb(), intId, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[categories] handlers installed');
}

module.exports = {
  installCategories,
  validateScope,
  categoriesList,
  categoriesGet,
  categoriesCreate,
  categoriesUpdate,
  categoriesUpdateById,
  categoriesDelete,
};
