'use strict';

// electron/sync/handlers/clock_slots.js — generated by scripts/generate-handlers.js
// IPC handlers for the clock_slots table (station-scoped).
// Channels: clock_slots:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.clockSlots.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE              = 'clock_slots';
const HAS_STATION_ID_COL = true;
const PATCHABLE          = ["clock_id","position","slot_type","category_id","song_id","label","duration_min","chain_type","spot_type","updated_at"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[clock_slots] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'station') {
    throw new Error(`[clock_slots] expected station-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function clockSlotsList(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function clockSlotsGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function clockSlotsCreate(db, payload) {
  validateScope();
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[clock_slots] station_id is required for station-scoped create`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     payload.station_id,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (clock_id, position, slot_type, category_id, song_id, label, duration_min, spot_type, station_id, uuid, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(row.clock_id, row.position, row.slot_type, row.category_id, row.song_id ?? null, row.label, row.duration_min, row.spot_type ?? null, row.station_id, row.uuid, row.created_at, row.updated_at, row.deleted_at);
  });
  return clockSlotsGet(db, uuid);
}

function clockSlotsUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[clock_slots] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[clock_slots] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[clock_slots] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     existing.station_id,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return clockSlotsGet(db, uuid);
}

function clockSlotsDelete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[clock_slots] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     (stationId ?? existing.station_id),
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}

function clockSlotsUpdateById(db, intId, patch) {
  let existing = db.prepare(`SELECT * FROM ${TABLE} WHERE id = ?`).get(intId);
  if (!existing) throw new Error(`[clock_slots] row not found by id: ${intId}`);
  if (!existing.uuid) {
    const newUuid = crypto.randomUUID();
    db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(newUuid, intId);
    existing = { ...existing, uuid: newUuid };
  }
  return clockSlotsUpdate(db, existing.uuid, patch);
}

function clockSlotsDeleteById(db, intId) {
  let existing = db.prepare(`SELECT * FROM ${TABLE} WHERE id = ?`).get(intId);
  if (!existing) throw new Error(`[clock_slots] row not found by id: ${intId}`);
  if (!existing.uuid) {
    const newUuid = crypto.randomUUID();
    db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(newUuid, intId);
    existing = { ...existing, uuid: newUuid };
  }
  return clockSlotsDelete(db, existing.uuid, existing.station_id);
}

function clockSlotsClearByClockId(db, clockId, stationId) {
  validateScope();
  const rows = db.prepare(`SELECT * FROM ${TABLE} WHERE clock_id = ? AND station_id = ? AND deleted_at IS NULL`).all(clockId, stationId);
  for (const r of rows) clockSlotsDelete(db, r.uuid, r.station_id);
  return { ok: true, deleted: rows.length };
}


// ── IPC installation ──────────────────────────────────────────────────────────

function installClockSlots(ipcMain, db) {
  ipcMain.handle('clock_slots:list', (_, stationId, opts) => {
    try { return { ok: true, rows: clockSlotsList(db, stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('clock_slots:get-by-id', (_, uuid) => {
    try { return { ok: true, row: clockSlotsGet(db, uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('clock_slots:create', (_, payload) => {
    try { return { ok: true, row: clockSlotsCreate(db, payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('clock_slots:update', (_, uuid, patch) => {
    try { return { ok: true, row: clockSlotsUpdate(db, uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('clock_slots:delete', (_, uuid, stationId) => {
    try { return { ok: true, ...clockSlotsDelete(db, uuid, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('clock_slots:update-by-id', (_, intId, patch) => {
    try { return { ok: true, row: clockSlotsUpdateById(db, intId, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('clock_slots:delete-by-id', (_, intId) => {
    try { return { ok: true, ...clockSlotsDeleteById(db, intId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('clock_slots:clear-by-clock-id', (_, clockId, stationId) => {
    try { return { ok: true, ...clockSlotsClearByClockId(db, clockId, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[clock_slots] handlers installed');
}

module.exports = {
  installClockSlots,
  validateScope,
  clockSlotsList,
  clockSlotsGet,
  clockSlotsCreate,
  clockSlotsUpdate,
  clockSlotsDelete,
  clockSlotsUpdateById,
  clockSlotsDeleteById,
  clockSlotsClearByClockId,

};
