'use strict';

// electron/sync/handlers/deck_configs.js — generated by scripts/generate-handlers.js
// IPC handlers for the deck_configs table (station-scoped).
// Channels: deck_configs:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.deckConfigs.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE              = 'deck_configs';
const HAS_STATION_ID_COL = true;
// SLICE 2 (2026-08-22): kind + address are patchable — `kind` is what the SOURCE channel's
// dropdown writes on every change, and `address` is its Phase 2 companion (mic device id /
// network endpoint). Without them here the guard rejects the write outright:
//   "[deck_configs] cannot patch immutable field(s): kind, address"
// v58 (2026-09-09): channel_on — the console channel's ON lamp. It was renderer useState with no
// store, and an effect asserted it downward into the engine, which made the fader section a WRITER
// of the channel cut. Two windows rendering that section would have fought over it. Without
// channel_on here the guard rejects the write outright:
//   "[deck_configs] cannot patch immutable field(s): channel_on"
const PATCHABLE          = ["type","label","color","enabled","purpose","updated_at","kind","address","duck","duckable","channel_on"];

// ── THIS FILE IS GENERATED, AND FOUR THINGS IN IT ARE NOT ──────────────────────────────────────
// scripts/generate-handlers.js renders every table in its REGISTRY from templates and overwrites
// each file unconditionally. Running it would silently revert, in this file alone:
//   1. PATCHABLE's `kind` and `address` (slice 2, 2026-08-22)
//   2. PATCHABLE's `duck` and `duckable` (v43/v44)
//   3. PATCHABLE's `channel_on` (v58, above)
//   4. the deck_configs:changed broadcast (below)
// Each is load-bearing: without 1-3 the write is refused by the guard; without 4 two windows drift
// apart on the same board. Filed in docs/backlog.md under the generator trap.

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[deck_configs] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'station') {
    throw new Error(`[deck_configs] expected station-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function deckConfigsList(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function deckConfigsGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function deckConfigsCreate(db, payload) {
  validateScope();
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[deck_configs] station_id is required for station-scoped create`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     payload.station_id,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      // SLICE 2 — kind/address are in the column list because a SOURCE channel on a brand-new slot
      // (S1..S5) is CREATED through here. Fixing only PATCHABLE would let an existing slot be
      // patched while a newly created one came back with an empty dropdown.
      `INSERT INTO ${TABLE} (slot, type, label, color, enabled, purpose, kind, address, duck, duckable, station_id, uuid, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(row.slot, row.type, row.label, row.color, row.enabled, row.purpose, row.kind ?? '', row.address ?? null, row.duck ?? 0, row.duckable ?? 1, row.station_id, row.uuid, row.created_at, row.updated_at, row.deleted_at);
  });
  return deckConfigsGet(db, uuid);
}

function deckConfigsUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[deck_configs] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[deck_configs] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[deck_configs] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     existing.station_id,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return deckConfigsGet(db, uuid);
}

function deckConfigsDelete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[deck_configs] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     (stationId ?? existing.station_id),
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}



// UPSERT by (station_id, slot). This used to be update-only and THREW "slot not found"
// on any station with no rows — which was every station except station 1, because the
// old `slot`-only PK could not hold a second station's decks. The IPC wrapper turned
// that throw into {ok:false} and the caller ignored it, so Apply Layout reported a
// success it never had. A write for a slot that does not exist yet now creates it.
function deckConfigsUpdateBySlot(db, stationId, slot, patch) {
  validateScope();
  let existing = db.prepare(
    `SELECT * FROM ${TABLE} WHERE station_id = ? AND slot = ? AND deleted_at IS NULL`
  ).get(stationId, slot);
  if (!existing) {
    // No row for this station+slot — create it, carrying the station's uuid so the row
    // is visible to peer sync, and log it as an insert mutation like any other create.
    let stationUuid = null;
    try { stationUuid = db.prepare('SELECT uuid FROM stations WHERE id = ?').get(stationId)?.uuid ?? null; }
    catch { /* stations table unavailable — leave null */ }
    return deckConfigsCreate(db, {
      station_id:   stationId,
      station_uuid: stationUuid,
      slot,
      type:    patch.type    ?? 'music',
      label:   patch.label   ?? `Deck ${slot}`,
      color:   patch.color   ?? '#34d399',
      enabled: patch.enabled ?? 0,
      purpose: patch.purpose ?? '',
      // SLICE 2 — a SOURCE channel is created by this path (the + button calls updateBySlot on a
      // slot that has no row yet), so the patch point must survive the create or the channel would
      // come back with an empty dropdown.
      kind:    patch.kind    ?? '',
      address: patch.address ?? null,
      duck:    patch.duck    ?? 0,
      // Default 1: a slot created by the + button ducks like every other deck until told otherwise.
      duckable: patch.duckable ?? 1,
    });
  }
  if (!existing.uuid) {
    const uuid = crypto.randomUUID();
    db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE station_id = ? AND slot = ?`).run(uuid, stationId, slot);
    existing = { ...existing, uuid };
  }
  return deckConfigsUpdate(db, existing.uuid, patch);
}

function deckConfigsClearAll(db, stationId) {
  const rows = db.prepare(
    `SELECT * FROM ${TABLE} WHERE station_id = ? AND deleted_at IS NULL`
  ).all(stationId);
  for (const row of rows) {
    let uuid = row.uuid;
    if (!uuid) {
      // deck_configs has no `id` column — this used to be `WHERE id = ?`, which throws
      // "no such column: id" the moment a uuid-less row is reached. Key on the row's own
      // identity instead: (station_id, slot).
      uuid = crypto.randomUUID();
      db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE station_id = ? AND slot = ?`)
        .run(uuid, row.station_id, row.slot);
    }
    deckConfigsDelete(db, uuid, stationId);
  }
  return { ok: true, cleared: rows.length };
}

// ── IPC installation ──────────────────────────────────────────────────────────

function installDeckConfigs(ipcMain, db) {
  const getDb = (typeof db === 'function') ? db : () => db;

  // ── EVERY WINDOW RE-READS WHEN THE BOARD CHANGES ────────────────────────────────────────────
  //
  // useDeckConfig() (src/components/DeckConfigurator.tsx) re-reads only on [isReady, stationId], so
  // a board change made in ONE window was invisible in every other until it re-mounted. With the
  // fader section rendering in both the dashboard and its own window that is not cosmetic: add a
  // channel with +, re-dial a source, or toggle a channel's ON lamp, and the two windows would show
  // different boards and assert different things downward at the engine.
  //
  // It lives HERE, at the write, rather than in the renderer that happens to call save() — a change
  // announcement that depends on which caller made the change is the kind of partial truth that
  // produces exactly the disagreement this removes. Every writer announces, including the sync layer
  // applying a remote mutation.
  const announce = (stationId) => {
    try {
      const { BrowserWindow } = require('electron');
      for (const w of BrowserWindow.getAllWindows()) {
        try { if (!w.isDestroyed()) w.webContents.send('deck_configs:changed', { stationId: stationId ?? null }); }
        catch { /* window closing */ }
      }
    } catch { /* no electron (tests) — the write itself already stands */ }
  };
  ipcMain.handle('deck_configs:list', (_, stationId, opts) => {
    try { return { ok: true, rows: deckConfigsList(getDb(), stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('deck_configs:get-by-id', (_, uuid) => {
    try { return { ok: true, row: deckConfigsGet(getDb(), uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('deck_configs:create', (_, payload) => {
    try { const row = deckConfigsCreate(getDb(), payload); announce(row && row.station_id); return { ok: true, row }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('deck_configs:update', (_, uuid, patch) => {
    try { const row = deckConfigsUpdate(getDb(), uuid, patch); announce(row && row.station_id); return { ok: true, row }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('deck_configs:delete', (_, uuid, stationId) => {
    try { const r = deckConfigsDelete(getDb(), uuid, stationId); announce(stationId); return { ok: true, ...r }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('deck_configs:update-by-slot', (_, stationId, slot, patch) => {
    try { const row = deckConfigsUpdateBySlot(getDb(), stationId, slot, patch); announce(stationId); return { ok: true, row }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[deck_configs] handlers installed');
}

module.exports = {
  installDeckConfigs,
  validateScope,
  deckConfigsList,
  deckConfigsGet,
  deckConfigsCreate,
  deckConfigsUpdate,
  deckConfigsUpdateBySlot,
  deckConfigsDelete,
  deckConfigsClearAll,
};
