'use strict';

// electron/sync/handlers/index.js — generated by scripts/generate-handlers.js
// Aggregator: installs all 31 typed IPC handler sets (station_programming hand-written
// + 30 generated) in one call. main.js calls installAll(ipcMain, db).

const { installStationProgramming } = require('./station_programming');
const { installAlbums } = require('./albums');
const { installAnnouncements } = require('./announcements');
const { installArtists } = require('./artists');
const { installCartSlots } = require('./cart_slots');
const { installCategories } = require('./categories');
const { installClockSlots } = require('./clock_slots');
const { installClocks } = require('./clocks');
const { installDeckConfigs } = require('./deck_configs');
const { installFormatClocks } = require('./format_clocks');
const { installGeneratedSchedule } = require('./generated_schedule');
const { installLinerCards } = require('./liner_cards');
const { installMacros } = require('./macros');
const { installMetadataDefinitions } = require('./metadata_definitions');
const { installMetadataVocabulary } = require('./metadata_vocabulary');
const { installMoodTags } = require('./mood_tags');
const { installOperatorNotes } = require('./operator_notes');
const { installOperators } = require('./operators');
const { installPinnedSongs } = require('./pinned_songs');
const { installPlayLog } = require('./play_log');
const { installPrepNotes } = require('./prep_notes');
const { installPublishedEpisodes } = require('./published_episodes');
const { installRtmpDestinations } = require('./rtmp_destinations');
const { installScheduledLog } = require('./scheduled_log');
const { installSeparationRules } = require('./separation_rules');
const { installShows } = require('./shows');
const { installSmartScheduleRules } = require('./smart_schedule_rules');
const { installSongMetadataValues } = require('./song_metadata_values');
const { installSongs } = require('./songs');
const { installSpots } = require('./spots');
const { installStationConfigKv } = require('./station_config_kv');
const { installStationProgrammingMoods } = require('./station_programming_moods');
const { installStations } = require('./stations');
const { installVoiceTracks } = require('./voice_tracks');

function installAll(ipcMain, db) {
  installStationProgramming(ipcMain, db);
  installAlbums(ipcMain, db);
  installAnnouncements(ipcMain, db);
  installArtists(ipcMain, db);
  installCartSlots(ipcMain, db);
  installCategories(ipcMain, db);
  installClockSlots(ipcMain, db);
  installClocks(ipcMain, db);
  installDeckConfigs(ipcMain, db);
  installFormatClocks(ipcMain, db);
  installGeneratedSchedule(ipcMain, db);
  installLinerCards(ipcMain, db);
  installMacros(ipcMain, db);
  installMetadataDefinitions(ipcMain, db);
  installMetadataVocabulary(ipcMain, db);
  installMoodTags(ipcMain, db);
  installOperatorNotes(ipcMain, db);
  installOperators(ipcMain, db);
  installPinnedSongs(ipcMain, db);
  installPlayLog(ipcMain, db);
  installPrepNotes(ipcMain, db);
  installPublishedEpisodes(ipcMain, db);
  installRtmpDestinations(ipcMain, db);
  installScheduledLog(ipcMain, db);
  installSeparationRules(ipcMain, db);
  installShows(ipcMain, db);
  installSmartScheduleRules(ipcMain, db);
  installSongMetadataValues(ipcMain, db);
  installSongs(ipcMain, db);
  installSpots(ipcMain, db);
  installStationConfigKv(ipcMain, db);
  installStationProgrammingMoods(ipcMain, db);
  installStations(ipcMain, db);
  installVoiceTracks(ipcMain, db);
}

module.exports = { installAll };
