'use strict';

// electron/sync/handlers/metadata_vocabulary.js — generated by scripts/generate-handlers.js
// IPC handlers for the metadata_vocabulary table (station-scoped).
// Channels: metadata_vocabulary:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.metadataVocabulary.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE              = 'metadata_vocabulary';
const HAS_STATION_ID_COL = true;
const PATCHABLE          = ["definition_id","value","display_order","color","updated_at"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[metadata_vocabulary] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'station') {
    throw new Error(`[metadata_vocabulary] expected station-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function metadataVocabularyList(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function metadataVocabularyGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function metadataVocabularyCreate(db, payload) {
  validateScope();
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[metadata_vocabulary] station_id is required for station-scoped create`);
  }

  // UNIQUE(definition_id, value) includes soft-deleted rows, so a deleted value blocks re-creation.
  // Resurrect the deleted row instead of inserting a new one.
  const ghost = db.prepare(
    `SELECT * FROM ${TABLE} WHERE definition_id = ? AND value = ? AND station_id = ? AND deleted_at IS NOT NULL LIMIT 1`
  ).get(payload.definition_id, payload.value, payload.station_id);

  if (ghost) {
    const now     = new Date().toISOString();
    const updated = { ...ghost, deleted_at: null, updated_at: now,
                      color: payload.color !== undefined ? payload.color : ghost.color };
    const before  = serializePayload(ghost, TABLE);
    const after   = serializePayload(updated, TABLE);
    withMutation(db, {
      table_name: TABLE, row_id: ghost.uuid, op: 'update',
      payload_before: before, payload_after: after,
      station_id: ghost.station_id, actor_id: payload.actor_id ?? null,
    }, () => {
      db.prepare(`UPDATE ${TABLE} SET deleted_at = NULL, updated_at = ?, color = ? WHERE uuid = ?`)
        .run(now, updated.color, ghost.uuid);
    });
    return metadataVocabularyGet(db, ghost.uuid);
  }

  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     payload.station_id,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (uuid, station_id, definition_id, value, display_order, color, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(row.uuid, row.station_id, row.definition_id, row.value, row.display_order, row.color, row.created_at, row.updated_at, row.deleted_at);
  });
  return metadataVocabularyGet(db, uuid);
}

function metadataVocabularyUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[metadata_vocabulary] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[metadata_vocabulary] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[metadata_vocabulary] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     existing.station_id,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return metadataVocabularyGet(db, uuid);
}

function metadataVocabularyDelete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[metadata_vocabulary] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);
  let cascadeCount = 0;

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     (stationId ?? existing.station_id),
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    // Query inside the transaction so the snapshot is atomic with the writes (Correction 1)
    // value_vocabulary_id is an integer FK to metadata_vocabulary.id, not the uuid
    const smvRows = db.prepare(
      `SELECT * FROM song_metadata_values WHERE value_vocabulary_id = ? AND deleted_at IS NULL`
    ).all(existing.id);

    for (const smv of smvRows) {
      const smvBefore = serializePayload(smv, 'song_metadata_values');
      withMutation(db, {
        table_name:     'song_metadata_values',
        row_id:         smv.uuid,
        op:             'delete',
        payload_before: smvBefore,
        payload_after:  null,
        station_id:     smv.station_id,
        actor_id:       null,
      }, () => {
        db.prepare(`UPDATE song_metadata_values SET deleted_at = ?, updated_at = ? WHERE uuid = ?`)
          .run(now, now, smv.uuid);
      });
    }
    cascadeCount = smvRows.length;

    db.prepare(`UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`)
      .run(now, now, uuid);
  });

  return { ok: true, cascadeCount };
}



// ── IPC installation ──────────────────────────────────────────────────────────

function installMetadataVocabulary(ipcMain, db) {
  ipcMain.handle('metadata_vocabulary:list', (_, stationId, opts) => {
    try { return { ok: true, rows: metadataVocabularyList(db, stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('metadata_vocabulary:get-by-id', (_, uuid) => {
    try { return { ok: true, row: metadataVocabularyGet(db, uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('metadata_vocabulary:create', (_, payload) => {
    try { return { ok: true, row: metadataVocabularyCreate(db, payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('metadata_vocabulary:update', (_, uuid, patch) => {
    try { return { ok: true, row: metadataVocabularyUpdate(db, uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('metadata_vocabulary:delete', (_, uuid, stationId) => {
    try { return { ok: true, ...metadataVocabularyDelete(db, uuid, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });


  console.log('[metadata_vocabulary] handlers installed');
}

module.exports = {
  installMetadataVocabulary,
  validateScope,
  metadataVocabularyList,
  metadataVocabularyGet,
  metadataVocabularyCreate,
  metadataVocabularyUpdate,
  metadataVocabularyDelete,

};
