'use strict';

// electron/sync/handlers/metadata_definitions.js — generated by scripts/generate-handlers.js
// IPC handlers for the metadata_definitions table (station-scoped).
// Channels: metadata_definitions:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.metadataDefinitions.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE              = 'metadata_definitions';
const HAS_STATION_ID_COL = true;
const PATCHABLE          = ["name","data_type","description","is_built_in","is_required","display_order","updated_at"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[metadata_definitions] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'station') {
    throw new Error(`[metadata_definitions] expected station-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function metadataDefinitionsList(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function metadataDefinitionsGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function metadataDefinitionsCreate(db, payload) {
  validateScope();
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[metadata_definitions] station_id is required for station-scoped create`);
  }

  // UNIQUE(station_id, name) includes soft-deleted rows, so a deleted definition
  // blocks re-creation. Resurrect the ghost row instead of inserting a new one.
  // NOTE: vocab rows and smv rows that were cascade-deleted with the original
  // definition are NOT restored — they stay deleted. Only the definition itself
  // is un-deleted; the operator must re-add vocab values if needed.
  const ghost = db.prepare(
    `SELECT * FROM ${TABLE} WHERE station_id = ? AND name = ? AND deleted_at IS NOT NULL LIMIT 1`
  ).get(payload.station_id, payload.name);

  if (ghost) {
    const now     = new Date().toISOString();
    const updated = {
      ...ghost,
      deleted_at:    null,
      updated_at:    now,
      data_type:     payload.data_type     !== undefined ? payload.data_type     : ghost.data_type,
      description:   payload.description   !== undefined ? payload.description   : ghost.description,
      is_built_in:   payload.is_built_in   !== undefined ? payload.is_built_in   : ghost.is_built_in,
      is_required:   payload.is_required   !== undefined ? payload.is_required   : ghost.is_required,
      display_order: payload.display_order !== undefined ? payload.display_order : ghost.display_order,
    };
    const before = serializePayload(ghost,   TABLE);
    const after  = serializePayload(updated, TABLE);
    withMutation(db, {
      table_name:     TABLE,
      row_id:         ghost.uuid,
      op:             'update',
      payload_before: before,
      payload_after:  after,
      station_id:     ghost.station_id,
      actor_id:       payload.actor_id ?? null,
    }, () => {
      db.prepare(
        `UPDATE ${TABLE} SET deleted_at = NULL, data_type = ?, description = ?, is_built_in = ?, is_required = ?, display_order = ?, updated_at = ? WHERE uuid = ?`
      ).run(updated.data_type, updated.description, updated.is_built_in, updated.is_required, updated.display_order, now, ghost.uuid);
    });
    return metadataDefinitionsGet(db, ghost.uuid);
  }

  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     payload.station_id,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (uuid, station_id, name, data_type, description, is_built_in, is_required, display_order, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(row.uuid, row.station_id, row.name, row.data_type, row.description, row.is_built_in, row.is_required, row.display_order, row.created_at, row.updated_at, row.deleted_at);
  });
  return metadataDefinitionsGet(db, uuid);
}

function metadataDefinitionsUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[metadata_definitions] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[metadata_definitions] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[metadata_definitions] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     existing.station_id,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return metadataDefinitionsGet(db, uuid);
}

function metadataDefinitionsDelete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[metadata_definitions] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);
  let cascadeCount = 0;

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     (stationId ?? existing.station_id),
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    // CASCADE level 1: vocab rows for this definition (query inside txn — Correction 1)
    const vocabRows = db.prepare(
      `SELECT * FROM metadata_vocabulary WHERE definition_id = ? AND deleted_at IS NULL`
    ).all(existing.id);

    for (const v of vocabRows) {
      const vocabBefore = serializePayload(v, 'metadata_vocabulary');
      withMutation(db, {
        table_name:     'metadata_vocabulary',
        row_id:         v.uuid,
        op:             'delete',
        payload_before: vocabBefore,
        payload_after:  null,
        station_id:     v.station_id,
        actor_id:       null,
      }, () => {
        // CASCADE level 2: SMV rows for this vocab value
        // value_vocabulary_id is an integer FK to metadata_vocabulary.id, not the uuid
        const smvRows = db.prepare(
          `SELECT * FROM song_metadata_values WHERE value_vocabulary_id = ? AND deleted_at IS NULL`
        ).all(v.id);

        for (const smv of smvRows) {
          const smvBefore = serializePayload(smv, 'song_metadata_values');
          withMutation(db, {
            table_name:     'song_metadata_values',
            row_id:         smv.uuid,
            op:             'delete',
            payload_before: smvBefore,
            payload_after:  null,
            station_id:     smv.station_id,
            actor_id:       null,
          }, () => {
            db.prepare(`UPDATE song_metadata_values SET deleted_at = ?, updated_at = ? WHERE uuid = ?`)
              .run(now, now, smv.uuid);
          });
          cascadeCount++;
        }

        db.prepare(`UPDATE metadata_vocabulary SET deleted_at = ?, updated_at = ? WHERE uuid = ?`)
          .run(now, now, v.uuid);
      });
    }

    db.prepare(`UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`)
      .run(now, now, uuid);
  });

  return { ok: true, cascadeCount };
}



// ── IPC installation ──────────────────────────────────────────────────────────

function installMetadataDefinitions(ipcMain, db) {
  const getDb = (typeof db === 'function') ? db : () => db;
  ipcMain.handle('metadata_definitions:list', (_, stationId, opts) => {
    try { return { ok: true, rows: metadataDefinitionsList(getDb(), stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('metadata_definitions:get-by-id', (_, uuid) => {
    try { return { ok: true, row: metadataDefinitionsGet(getDb(), uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('metadata_definitions:create', (_, payload) => {
    try { return { ok: true, row: metadataDefinitionsCreate(getDb(), payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('metadata_definitions:update', (_, uuid, patch) => {
    try { return { ok: true, row: metadataDefinitionsUpdate(getDb(), uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('metadata_definitions:delete', (_, uuid, stationId) => {
    try { return { ok: true, ...metadataDefinitionsDelete(getDb(), uuid, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });


  console.log('[metadata_definitions] handlers installed');
}

module.exports = {
  installMetadataDefinitions,
  validateScope,
  metadataDefinitionsList,
  metadataDefinitionsGet,
  metadataDefinitionsCreate,
  metadataDefinitionsUpdate,
  metadataDefinitionsDelete,

};
