'use strict';

// electron/sync/handlers/mood_tags.js — generated by scripts/generate-handlers.js
// IPC handlers for the mood_tags table (install-scoped).
// Channels: mood_tags:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.moodTags.*
//
// Install-scoped: data is shared across all stations. No station_id filtering
// on list. withMutation receives station_id: null per [N-89].

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE    = 'mood_tags';
const PATCHABLE = ["name","description","color","updated_at"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[mood_tags] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'install') {
    throw new Error(`[mood_tags] expected install-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function moodTagsList(db, opts) {
  const { limit = 500, offset = 0 } = opts || {};
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL ORDER BY rowid LIMIT ? OFFSET ?`
  ).all(limit, offset);
}

function moodTagsGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function moodTagsCreate(db, payload) {
  validateScope();
  if (payload.station_id != null) {
    throw new Error(`[mood_tags] station_id must not be set on install-scoped create (got ${payload.station_id})`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     null,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (uuid, name, description, color, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?)`
    ).run(row.uuid, row.name, row.description, row.color, row.created_at, row.updated_at, row.deleted_at);
  });
  return moodTagsGet(db, uuid);
}

function moodTagsUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[mood_tags] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[mood_tags] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[mood_tags] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     null,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return moodTagsGet(db, uuid);
}

function moodTagsDelete(db, uuid) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[mood_tags] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     null,
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}

// ── IPC installation ──────────────────────────────────────────────────────────

function installMoodTags(ipcMain, db) {
  ipcMain.handle('mood_tags:list', (_, opts) => {
    try { return { ok: true, rows: moodTagsList(db, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('mood_tags:get-by-id', (_, uuid) => {
    try { return { ok: true, row: moodTagsGet(db, uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('mood_tags:create', (_, payload) => {
    try { return { ok: true, row: moodTagsCreate(db, payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('mood_tags:update', (_, uuid, patch) => {
    try { return { ok: true, row: moodTagsUpdate(db, uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('mood_tags:delete', (_, uuid) => {
    try { return { ok: true, ...moodTagsDelete(db, uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[mood_tags] handlers installed');
}

module.exports = {
  installMoodTags,
  validateScope,
  moodTagsList,
  moodTagsGet,
  moodTagsCreate,
  moodTagsUpdate,
  moodTagsDelete,
};
