'use strict';

// electron/sync/handlers/operator_notes.js — generated by scripts/generate-handlers.js
// IPC handlers for the operator_notes table (station-scoped).
// Channels: operator_notes:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.operatorNotes.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE              = 'operator_notes';
const HAS_STATION_ID_COL = true;
const PATCHABLE          = ["operator_id","note","updated_at"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[operator_notes] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'station') {
    throw new Error(`[operator_notes] expected station-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function operatorNotesList(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function operatorNotesGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function operatorNotesCreate(db, payload) {
  validateScope();
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[operator_notes] station_id is required for station-scoped create`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     payload.station_id,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (operator_id, note, updated_at, station_id, uuid, created_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?)`
    ).run(row.operator_id, row.note, row.updated_at, row.station_id, row.uuid, row.created_at, row.deleted_at);
  });
  return operatorNotesGet(db, uuid);
}

function operatorNotesUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[operator_notes] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[operator_notes] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[operator_notes] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     existing.station_id,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return operatorNotesGet(db, uuid);
}

function operatorNotesDelete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[operator_notes] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     (stationId ?? existing.station_id),
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}



function operatorNotesUpsertByOperatorId(db, operatorId, stationId, note) {
  const existing = db.prepare(
    `SELECT * FROM ${TABLE} WHERE operator_id = ? AND station_id = ? AND deleted_at IS NULL`
  ).get(operatorId, stationId);
  if (existing) {
    if (!existing.uuid) {
      const newUuid = crypto.randomUUID();
      db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(newUuid, existing.id);
      existing.uuid = newUuid;
    }
    return operatorNotesUpdate(db, existing.uuid, { note });
  }
  return operatorNotesCreate(db, { operator_id: operatorId, note, station_id: stationId });
}

// ── IPC installation ──────────────────────────────────────────────────────────

function installOperatorNotes(ipcMain, db) {
  ipcMain.handle('operator_notes:list', (_, stationId, opts) => {
    try { return { ok: true, rows: operatorNotesList(db, stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('operator_notes:get-by-id', (_, uuid) => {
    try { return { ok: true, row: operatorNotesGet(db, uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('operator_notes:create', (_, payload) => {
    try { return { ok: true, row: operatorNotesCreate(db, payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('operator_notes:update', (_, uuid, patch) => {
    try { return { ok: true, row: operatorNotesUpdate(db, uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('operator_notes:delete', (_, uuid, stationId) => {
    try { return { ok: true, ...operatorNotesDelete(db, uuid, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });


  console.log('[operator_notes] handlers installed');
}

module.exports = {
  installOperatorNotes,
  validateScope,
  operatorNotesList,
  operatorNotesGet,
  operatorNotesCreate,
  operatorNotesUpdate,
  operatorNotesDelete,
  operatorNotesUpsertByOperatorId,
};
