'use strict';

// electron/sync/handlers/play_log.js — generated by scripts/generate-handlers.js
// IPC handlers for the play_log table (station-scoped).
// Channels: play_log:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.playLog.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload, logMutation } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE              = 'play_log';
const HAS_STATION_ID_COL = true;
const PATCHABLE          = ["title","artist","deck","deck_id","duration_ms","session_id","played_at","scheduled_log_id","show_name","category_code","updated_at","programming_row_id"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[play_log] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'station') {
    throw new Error(`[play_log] expected station-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function playLogList(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function playLogGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function playLogCreate(db, payload) {
  validateScope();
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[play_log] station_id is required for station-scoped create`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     payload.station_id,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (title, artist, deck, deck_id, duration_ms, session_id, played_at, scheduled_log_id, show_name, category_code, station_id, uuid, created_at, updated_at, deleted_at, programming_row_id, file_path) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(row.title, row.artist, row.deck, row.deck_id, row.duration_ms, row.session_id, row.played_at, row.scheduled_log_id, row.show_name, row.category_code, row.station_id, row.uuid, row.created_at, row.updated_at, row.deleted_at, row.programming_row_id, row.file_path ?? null);
  });
  return playLogGet(db, uuid);
}

function playLogUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[play_log] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[play_log] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[play_log] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     existing.station_id,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return playLogGet(db, uuid);
}

function playLogDelete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[play_log] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     (stationId ?? existing.station_id),
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}

function playLogClearByStation(db, stationId) {
  validateScope();
  if (stationId == null) throw new Error('[play_log] stationId required for clearByStation');

  const now = new Date().toISOString();

  // Soft-delete all non-deleted rows for this station in one atomic transaction.
  // Per-row delete mutations are written with logMutation (direct use permitted
  // for batch operations that manage their own transaction — mutation-writer.js §4 note).
  return db.transaction(() => {
    const rows = db.prepare(
      `SELECT * FROM ${TABLE} WHERE station_id = ? AND deleted_at IS NULL`
    ).all(stationId);

    for (const row of rows) {
      const before = serializePayload(row, TABLE);
      db.prepare(
        `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
      ).run(now, now, row.uuid);
      logMutation(db, {
        table_name:     TABLE,
        row_id:         row.uuid,
        op:             'delete',
        payload_before: before,
        payload_after:  null,
        station_id:     stationId,
        actor_id:       null,
      });
    }

    return { ok: true, cleared: rows.length };
  })();
}



// ── IPC installation ──────────────────────────────────────────────────────────

function installPlayLog(ipcMain, db) {
  ipcMain.handle('play_log:list', (_, stationId, opts) => {
    try { return { ok: true, rows: playLogList(db, stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('play_log:get-by-id', (_, uuid) => {
    try { return { ok: true, row: playLogGet(db, uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('play_log:create', (_, payload) => {
    try { return { ok: true, row: playLogCreate(db, payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('play_log:update', (_, uuid, patch) => {
    try { return { ok: true, row: playLogUpdate(db, uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('play_log:delete', (_, uuid, stationId) => {
    try { return { ok: true, ...playLogDelete(db, uuid, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('play_log:clear-by-station', (_, stationId) => {
    try { return playLogClearByStation(db, stationId); }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[play_log] handlers installed');
}

module.exports = {
  installPlayLog,
  validateScope,
  playLogList,
  playLogGet,
  playLogCreate,
  playLogUpdate,
  playLogDelete,
  playLogClearByStation,
};
