'use strict';

// electron/sync/handlers/scheduled_log.js — generated by scripts/generate-handlers.js
// IPC handlers for the scheduled_log table (station-scoped).
// Channels: scheduled_log:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.scheduledLog.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE              = 'scheduled_log';
const HAS_STATION_ID_COL = true;
const PATCHABLE          = ["log_date","hour","position","song_id","title","artist","category_id","duration_ms","clock_id","overflow","fade_out_at_ms","fade_duration_ms","chain_type","updated_at"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[scheduled_log] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'station') {
    throw new Error(`[scheduled_log] expected station-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function scheduledLogList(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function scheduledLogGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function scheduledLogCreate(db, payload) {
  validateScope();
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[scheduled_log] station_id is required for station-scoped create`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     payload.station_id,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (log_date, hour, position, song_id, title, artist, category_id, duration_ms, clock_id, created_at, overflow, fade_out_at_ms, fade_duration_ms, chain_type, station_id, uuid, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(row.log_date, row.hour, row.position, row.song_id, row.title, row.artist, row.category_id, row.duration_ms, row.clock_id, row.created_at, row.overflow, row.fade_out_at_ms, row.fade_duration_ms, row.chain_type, row.station_id, row.uuid, row.updated_at, row.deleted_at);
  });
  return scheduledLogGet(db, uuid);
}

function scheduledLogUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[scheduled_log] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[scheduled_log] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[scheduled_log] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     existing.station_id,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return scheduledLogGet(db, uuid);
}

function scheduledLogDelete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[scheduled_log] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     (stationId ?? existing.station_id),
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}



// ── IPC installation ──────────────────────────────────────────────────────────

function installScheduledLog(ipcMain, db) {
  ipcMain.handle('scheduled_log:list', (_, stationId, opts) => {
    try { return { ok: true, rows: scheduledLogList(db, stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('scheduled_log:get-by-id', (_, uuid) => {
    try { return { ok: true, row: scheduledLogGet(db, uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('scheduled_log:create', (_, payload) => {
    try { return { ok: true, row: scheduledLogCreate(db, payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('scheduled_log:update', (_, uuid, patch) => {
    try { return { ok: true, row: scheduledLogUpdate(db, uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('scheduled_log:delete', (_, uuid, stationId) => {
    try { return { ok: true, ...scheduledLogDelete(db, uuid, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });


  console.log('[scheduled_log] handlers installed');
}

module.exports = {
  installScheduledLog,
  validateScope,
  scheduledLogList,
  scheduledLogGet,
  scheduledLogCreate,
  scheduledLogUpdate,
  scheduledLogDelete,

};
