'use strict';

// electron/sync/handlers/songs.js — generated by scripts/generate-handlers.js
// IPC handlers for the songs table (install-scoped).
// Channels: songs:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.songs.*
//
// Install-scoped: data is shared across all stations. No station_id filtering
// on list. withMutation receives station_id: null per [N-89].

const crypto = require('crypto');
const { withMutation, logMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

// WIRE / REGISTRY name — what peers see and what serializePayload + REGISTRY are keyed on. It MUST
// stay 'songs' forever: changing it would make every other install treat our mutations as a different
// table and the two would diverge.
const TABLE    = 'songs';
const PATCHABLE = ["title","file_path","file_key","artist_id","album_id","category_id","genre","duration_ms","bpm","energy","mood","gender","rotation_status","daypart_mask","no_repeat_hours","lufs_measured","peak_db","gain_db","is_processed","cue_in","cue_out","cue_in_ms","cue_out_ms","intro_end","outro_start","intro_end_ms","outro_start_ms","intro_version_path","has_intro","last_played_at","play_count","is_explicit","updated_at","raw_metadata","spotify_uri","cart_id","content_class","jingle_category_id"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[songs] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'install') {
    throw new Error(`[songs] expected install-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function songsList(db, opts) {
  const { limit = 500, offset = 0 } = opts || {};
  return db.prepare(
    `SELECT * FROM ${TABLE} ORDER BY id LIMIT ? OFFSET ?`
  ).all(limit, offset);
}

function songsGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function songsCreate(db, payload) {
  validateScope();
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     null,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (title, file_path, artist_id, album_id, category_id, genre, duration_ms, bpm, energy, mood, gender, rotation_status, daypart_mask, no_repeat_hours, lufs_measured, peak_db, gain_db, is_processed, cue_in, cue_out, cue_in_ms, cue_out_ms, intro_end, outro_start, intro_end_ms, outro_start_ms, intro_version_path, has_intro, last_played_at, play_count, is_explicit, created_at, updated_at, raw_metadata, spotify_uri, cart_id, uuid, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(row.title, row.file_path, row.artist_id, row.album_id, row.category_id, row.genre, row.duration_ms, row.bpm, row.energy, row.mood, row.gender, row.rotation_status, row.daypart_mask, row.no_repeat_hours, row.lufs_measured, row.peak_db, row.gain_db, row.is_processed, row.cue_in, row.cue_out, row.cue_in_ms, row.cue_out_ms, row.intro_end, row.outro_start, row.intro_end_ms, row.outro_start_ms, row.intro_version_path, row.has_intro, row.last_played_at, row.play_count, row.is_explicit, row.created_at, row.updated_at, row.raw_metadata, row.spotify_uri, row.cart_id, row.uuid, row.deleted_at);
  });
  return songsGet(db, uuid);
}

function songsUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[songs] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[songs] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[songs] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     null,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return songsGet(db, uuid);
}

function songsDelete(db, uuid) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[songs] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);
  let retracted = null;

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     null,
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    neuterSong(db, uuid, now);
    retracted = retractSongReferences(db, existing, now);
  });
  noteSongRetraction(existing, retracted);
  return { ok: true, retracted };
}


// ── Neutering: how a deleted song becomes unreachable ─────────────────────────
// The row STAYS in `songs`. It has to: generated_schedule / scheduled_log / song_metadata_values
// reference songs(id) with NO ACTION, station_programming with RESTRICT, and pinned_songs with
// CASCADE — and the preserved history we deliberately keep is exactly what holds those references.
// Proof on a real database: removing the row fails with FOREIGN KEY constraint failed, and the
// CASCADE would silently delete the operator's pins.
//
// So unreachability is achieved in DATA, on fields every selector ALREADY reads:
//   • rotation_status = 'inactive' — every music selector filters this today: stmtCandidates
//     (main.js), loggen baseConditions + fillQueueEnforced, and the jingle/sweeper pools.
//   • file_path = NULL — the air-time resolver is COALESCE(gs.file_path, s.file_path), so it yields
//     NULL and the reader's existing `.filter(r => r.file_path)` drops the row. That was the second
//     hole ("Gap B") in the original diagnosis, closed here by data.
//   • deleted_at — the tombstone sync and the library already read.
//
// Nothing is renamed, no shape changes, every FK stays intact, and any build — including ones already
// in the field — opens the database and sees an inactive song with no file, which it cannot air either.
// The original path is preserved in the delete mutation's payload_before, so a restore can put it back.
// docs/migration-safety-and-customer-recovery-2026-08-06.md
function neuterSong(db, uuid, nowIso) {
  db.prepare(
    `UPDATE ${TABLE}
        SET deleted_at = ?, updated_at = ?, rotation_status = 'inactive', file_path = NULL
      WHERE uuid = ?`
  ).run(nowIso, nowIso, uuid);
}

// ── The delete contract ───────────────────────────────────────────────────────
// A delete RETRACTS THE SONG'S FUTURE and NEVER EDITS ITS PAST.
// docs/deleted-songs-still-air-design-2026-08-06.md §9 (Jeff's ruling, 2026-08-06).
//
// PRESERVED, deliberately — do not "clean these up" in a later pass:
//   • play_log                      — the advertiser airplay proof. The old cascade hard-DELETEd it,
//                                     so deleting a song erased the evidence it ever aired (songs 6/11/22
//                                     lost their history that way). Never again.
//   • generated_schedule played/missed — the record of what actually went to air.
//   • generated_schedule playing    — that is audio ON AIR RIGHT NOW. Never yank it out from under the
//                                     operator (physical deck positions are sacred; Esc never kills audio).
//
// WHY UNLOGGED (no per-row mutations): the GUARANTEE that a deleted song never airs is that the row is
// GONE from `songs` — invisible to every selector and every air-time resolution join, on THIS install and on
// every peer the moment the delete mutation lands. This cascade is local log hygiene on top of that
// guarantee, not the guarantee itself, so it does not need to be replicated row-by-row. (The cascade it
// replaces was also unlogged — and hard-deleted, which was worse.)
//
// Returns per-table counts so the delete is observable instead of silent.
function retractSongReferences(db, song, nowIso) {
  const out = { pendingLog: 0, programming: 0, pinned: 0, metadata: 0, clockSlots: 0, overlays: 0, legacyLog: 0 };
  const soft = (sql, ...args) => {
    try { return db.prepare(sql).run(...args).changes || 0; } catch { return 0; }
  };

  // FUTURE AIR — pending only. 'played'/'missed'/'playing' are history or present, and stay.
  out.pendingLog = soft(
    `UPDATE generated_schedule SET deleted_at = ?, updated_at = ?
      WHERE song_id = ? AND state = 'pending' AND deleted_at IS NULL`, nowIso, nowIso, song.id);

  // PROGRAMMING REFERENCES — rows that exist only to point at this song.
  out.programming = soft(
    `UPDATE station_programming SET deleted_at = ?, updated_at = ?
      WHERE song_id = ? AND deleted_at IS NULL`, nowIso, nowIso, song.id);
  out.pinned = soft(
    `UPDATE pinned_songs SET deleted_at = ?, updated_at = ?
      WHERE song_id = ? AND deleted_at IS NULL`, nowIso, nowIso, song.id);
  out.metadata = soft(
    `UPDATE song_metadata_values SET deleted_at = ?, updated_at = ?
      WHERE song_id = ? AND deleted_at IS NULL`, nowIso, nowIso, song.id);
  // Legacy log: retract only what has not aired. Even if this table's status vocabulary ever differs,
  // the airplay PROOF lives in play_log, which this function never touches.
  out.legacyLog = soft(
    `UPDATE scheduled_log SET deleted_at = ?, updated_at = ?
      WHERE song_id = ? AND deleted_at IS NULL AND (status IS NULL OR status <> 'played')`,
    nowIso, nowIso, song.id);
  // Local diagnostic table, no deleted_at/uuid — a hard delete is correct here.
  try { db.prepare(`DELETE FROM scheduler_reasons WHERE song_id = ?`).run(song.id); } catch {}

  // STRUCTURES THAT OUTLIVE THE SONG — null the reference, keep the row. A clock slot and a category
  // are the station's programming structure; they must not vanish because one song did.
  out.clockSlots = soft(
    `UPDATE clock_slots SET song_id = NULL, updated_at = ?
      WHERE song_id = ? AND deleted_at IS NULL`, nowIso, song.id);
  out.overlays = soft(
    `UPDATE categories SET overlay_song_id = NULL, updated_at = ?
      WHERE overlay_song_id = ? AND deleted_at IS NULL`, nowIso, song.id);

  return out;
}

// The sense: a delete that silently retracts 24 log rows is exactly how this defect survived 16 days.
// Never throws into the delete path.
function noteSongRetraction(song, retracted) {
  if (!retracted) return;
  const total = Object.values(retracted).reduce((a, b) => a + b, 0);
  try {
    console.log(`[songs] retracted "${song.title}" (id ${song.id}): ` +
      `${retracted.pendingLog} pending log rows, ${retracted.programming} programming, ` +
      `${retracted.pinned} pinned, ${retracted.metadata} metadata, ${retracted.clockSlots} clock slots, ` +
      `${retracted.overlays} overlays, ${retracted.legacyLog} legacy log — play_log and aired history preserved`);
  } catch {}
  try {
    require('../../library-health').noteEvent('song-retracted', {
      songId: song.id, title: song.title, total, ...retracted,
    });
  } catch { /* health module optional — never block a delete */ }
}

function songsGetByIntId(db, intId) {
  return db.prepare(`SELECT * FROM ${TABLE} WHERE id = ? AND deleted_at IS NULL`).get(intId) ?? null;
}

function songsUpdateById(db, intId, patch) {
  let existing = db.prepare(`SELECT * FROM ${TABLE} WHERE id = ?`).get(intId);
  if (!existing) throw new Error(`[songs] row not found by id: ${intId}`);
  if (!existing.uuid) {
    const newUuid = crypto.randomUUID();
    db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(newUuid, intId);
    existing = { ...existing, uuid: newUuid };
  }
  return songsUpdate(db, existing.uuid, patch);
}

function songsDeleteById(db, intId) {
  let existing = db.prepare(`SELECT * FROM ${TABLE} WHERE id = ?`).get(intId);
  if (!existing) throw new Error(`[songs] row not found by id: ${intId}`);
  if (!existing.uuid) {
    const newUuid = crypto.randomUUID();
    db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(newUuid, intId);
    existing = { ...existing, uuid: newUuid };
  }
  return songsDelete(db, existing.uuid);
}

// Mark a song as just-aired: stamp last_played_at (unix seconds) and bump play_count. This is the
// ONE writer of last_played_at — the whole rotation engine (live picker AND the generator) reads it
// for song/artist separation and LRP, but nothing ever wrote it, so separation was a silent no-op.
// Resolved by file_path (what the audio engine actually played); routed through the mutation path so
// sync stays consistent. Returns {ok, matched}.
function songsMarkPlayed(db, filePath, atSec) {
  validateScope();
  if (!filePath) return { ok: true, matched: 0 };
  const row = db.prepare(`SELECT * FROM ${TABLE} WHERE file_path = ? AND deleted_at IS NULL`).get(filePath);
  if (!row) return { ok: true, matched: 0 };
  const now = new Date().toISOString();
  const playedAt = Number.isFinite(atSec) ? Math.floor(atSec) : Math.floor(Date.now() / 1000);
  let uuid = row.uuid;
  if (!uuid) { uuid = crypto.randomUUID(); db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(uuid, row.id); }
  const before  = serializePayload({ ...row, uuid }, TABLE);
  const updated = { ...row, uuid, last_played_at: playedAt, play_count: (row.play_count || 0) + 1, updated_at: now };
  const after   = serializePayload(updated, TABLE);
  withMutation(db, {
    table_name: TABLE, row_id: uuid, op: 'update',
    payload_before: before, payload_after: after, station_id: null, actor_id: null,
  }, () => {
    db.prepare(`UPDATE ${TABLE} SET last_played_at = ?, play_count = ?, updated_at = ? WHERE id = ?`)
      .run(playedAt, (row.play_count || 0) + 1, now, row.id);
  });
  return { ok: true, matched: 1 };
}

function songsDeleteByStation(db, _stationId) {
  const rows = db.prepare(
    `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`
  ).all();
  const now = new Date().toISOString();
  const doAll = db.transaction(() => {
    for (const row of rows) {
      let uuid = row.uuid;
      if (!uuid) {
        uuid = crypto.randomUUID();
        db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(uuid, row.id);
      }
      const before = serializePayload({ ...row, uuid }, TABLE);
      neuterSong(db, uuid, now);
      // Same delete contract as songsDelete: retract the future, never edit the past (§9).
      retractSongReferences(db, row, now);
      logMutation(db, {
        table_name:     TABLE,
        row_id:         uuid,
        op:             'delete',
        payload_before: before,
        payload_after:  null,
        station_id:     null,
        actor_id:       null,
      });
    }
  });
  doAll();
  return { ok: true, cleared: rows.length };
}

function songsResetLoudnessByStation(db, _stationId) {
  const rows = db.prepare(
    `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`
  ).all();
  const now = new Date().toISOString();
  const doAll = db.transaction(() => {
    for (const row of rows) {
      let uuid = row.uuid;
      if (!uuid) {
        uuid = crypto.randomUUID();
        db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(uuid, row.id);
      }
      const rowWithUuid = { ...row, uuid };
      const before  = serializePayload(rowWithUuid, TABLE);
      const updated = { ...rowWithUuid, lufs_measured: null, peak_db: null, gain_db: 0, updated_at: now };
      const after   = serializePayload(updated, TABLE);
      db.prepare(`UPDATE ${TABLE} SET lufs_measured = NULL, peak_db = NULL, gain_db = 0, updated_at = ? WHERE id = ?`).run(now, row.id);
      logMutation(db, {
        table_name:     TABLE,
        row_id:         uuid,
        op:             'update',
        payload_before: before,
        payload_after:  after,
        station_id:     null,
        actor_id:       null,
      });
    }
  });
  doAll();
  return { ok: true, cleared: rows.length };
}

// ── IPC installation ──────────────────────────────────────────────────────────

function installSongs(ipcMain, db) {
  const getDb = (typeof db === 'function') ? db : () => db;
  ipcMain.handle('songs:list', (_, opts) => {
    try { return { ok: true, rows: songsList(getDb(), opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('songs:get-by-id', (_, uuid) => {
    try { return { ok: true, row: songsGet(getDb(), uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('songs:create', (_, payload) => {
    try { return { ok: true, row: songsCreate(getDb(), payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('songs:update', (_, uuid, patch) => {
    try { return { ok: true, row: songsUpdate(getDb(), uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('songs:delete', (_, uuid) => {
    try { return { ok: true, ...songsDelete(getDb(), uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('songs:get-by-int-id', (_, intId) => {
    try { return { ok: true, row: songsGetByIntId(getDb(), intId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('songs:update-by-id', (_, intId, patch) => {
    try { return { ok: true, row: songsUpdateById(getDb(), intId, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('songs:delete-by-id', (_, intId) => {
    try { return { ok: true, ...songsDeleteById(getDb(), intId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('songs:delete-by-station', (_, stationId) => {
    try { return { ok: true, ...songsDeleteByStation(getDb(), stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('songs:reset-loudness-by-station', (_, stationId) => {
    try { return { ok: true, ...songsResetLoudnessByStation(getDb(), stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('songs:mark-played', (_, filePath, atSec) => {
    try { return songsMarkPlayed(getDb(), filePath, atSec); }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[songs] handlers installed');
}

module.exports = {
  installSongs,
  validateScope,
  songsList,
  songsGet,
  songsGetByIntId,
  songsCreate,
  songsUpdate,
  songsUpdateById,
  songsDelete,
  songsDeleteById,
  songsDeleteByStation,
  songsResetLoudnessByStation,
  songsMarkPlayed,
  neuterSong,
};
