'use strict';

// electron/sync/handlers/songs.js — generated by scripts/generate-handlers.js
// IPC handlers for the songs table (install-scoped).
// Channels: songs:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.songs.*
//
// Install-scoped: data is shared across all stations. No station_id filtering
// on list. withMutation receives station_id: null per [N-89].

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE    = 'songs';
const PATCHABLE = ["title","file_path","artist_id","album_id","category_id","genre","duration_ms","bpm","energy","mood","gender","rotation_status","daypart_mask","no_repeat_hours","lufs_measured","peak_db","gain_db","is_processed","cue_in","cue_out","cue_in_ms","cue_out_ms","intro_end","outro_start","intro_end_ms","outro_start_ms","intro_version_path","has_intro","last_played_at","play_count","is_explicit","updated_at","raw_metadata","spotify_uri"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[songs] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'install') {
    throw new Error(`[songs] expected install-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function songsList(db, opts) {
  const { limit = 500, offset = 0 } = opts || {};
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL ORDER BY rowid LIMIT ? OFFSET ?`
  ).all(limit, offset);
}

function songsGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function songsCreate(db, payload) {
  validateScope();
  if (payload.station_id != null) {
    throw new Error(`[songs] station_id must not be set on install-scoped create (got ${payload.station_id})`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     null,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (title, file_path, artist_id, album_id, category_id, genre, duration_ms, bpm, energy, mood, gender, rotation_status, daypart_mask, no_repeat_hours, lufs_measured, peak_db, gain_db, is_processed, cue_in, cue_out, cue_in_ms, cue_out_ms, intro_end, outro_start, intro_end_ms, outro_start_ms, intro_version_path, has_intro, last_played_at, play_count, is_explicit, created_at, updated_at, raw_metadata, spotify_uri, station_id, uuid, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(row.title, row.file_path, row.artist_id, row.album_id, row.category_id, row.genre, row.duration_ms, row.bpm, row.energy, row.mood, row.gender, row.rotation_status, row.daypart_mask, row.no_repeat_hours, row.lufs_measured, row.peak_db, row.gain_db, row.is_processed, row.cue_in, row.cue_out, row.cue_in_ms, row.cue_out_ms, row.intro_end, row.outro_start, row.intro_end_ms, row.outro_start_ms, row.intro_version_path, row.has_intro, row.last_played_at, row.play_count, row.is_explicit, row.created_at, row.updated_at, row.raw_metadata, row.spotify_uri, row.station_id, row.uuid, row.deleted_at);
  });
  return songsGet(db, uuid);
}

function songsUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[songs] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[songs] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[songs] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     null,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return songsGet(db, uuid);
}

function songsDelete(db, uuid) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[songs] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     null,
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}

// ── IPC installation ──────────────────────────────────────────────────────────

function installSongs(ipcMain, db) {
  ipcMain.handle('songs:list', (_, opts) => {
    try { return { ok: true, rows: songsList(db, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('songs:get-by-id', (_, uuid) => {
    try { return { ok: true, row: songsGet(db, uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('songs:create', (_, payload) => {
    try { return { ok: true, row: songsCreate(db, payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('songs:update', (_, uuid, patch) => {
    try { return { ok: true, row: songsUpdate(db, uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('songs:delete', (_, uuid) => {
    try { return { ok: true, ...songsDelete(db, uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[songs] handlers installed');
}

module.exports = {
  installSongs,
  validateScope,
  songsList,
  songsGet,
  songsCreate,
  songsUpdate,
  songsDelete,
};
