'use strict';

// electron/sync/handlers/song_metadata_values.js — generated by scripts/generate-handlers.js
// IPC handlers for the song_metadata_values table (station-scoped).
// Channels: song_metadata_values:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.songMetadataValues.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE              = 'song_metadata_values';
const HAS_STATION_ID_COL = true;
const PATCHABLE          = ["song_id","definition_id","value_text","value_vocabulary_id","updated_at"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[song_metadata_values] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'station') {
    throw new Error(`[song_metadata_values] expected station-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function songMetadataValuesList(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function songMetadataValuesGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function songMetadataValuesCreate(db, payload) {
  validateScope();
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[song_metadata_values] station_id is required for station-scoped create`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     payload.station_id,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (uuid, station_id, song_id, definition_id, value_text, value_vocabulary_id, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(row.uuid, row.station_id, row.song_id, row.definition_id, row.value_text, row.value_vocabulary_id, row.created_at, row.updated_at, row.deleted_at);
  });
  return songMetadataValuesGet(db, uuid);
}

function songMetadataValuesUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[song_metadata_values] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[song_metadata_values] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[song_metadata_values] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     existing.station_id,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return songMetadataValuesGet(db, uuid);
}

function songMetadataValuesDelete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[song_metadata_values] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     (stationId ?? existing.station_id),
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}



// ── Bulk apply ────────────────────────────────────────────────────────────────
//
// Atomically applies a batch of per-definition changes across a set of songs.
// Each BulkChange maps to one parent mutation; each per-song smv operation
// creates a child mutation that inherits the parent via _mutationContextStack.
//
// change.action semantics:
//   'set'   — delete all existing smv rows for song+definition, then insert one
//             new row (value_text or value_vocabulary_id).
//   'add'   — additive for multi_choice: insert vocab rows not already present.
//             Existing tags are preserved; duplicates are silently skipped.
//   'clear' — soft-delete all smv rows for song+definition (any value).

function metadataValuesBulkApply(db, { song_ids, changes, station_id }) {
  validateScope();
  if (!Array.isArray(song_ids) || song_ids.length === 0) throw new Error('[bulk_apply] song_ids must be a non-empty array');
  if (!Array.isArray(changes) || changes.length === 0)   throw new Error('[bulk_apply] changes must be a non-empty array');
  if (station_id == null) throw new Error('[bulk_apply] station_id is required');

  let songsAffected = 0;
  let smvOperations = 0;

  // Single outer transaction — any inner failure rolls back everything.
  db.transaction(() => {
    for (const change of changes) {
      const { definition_id, action } = change;
      if (!definition_id || !action) throw new Error(`[bulk_apply] invalid change: ${JSON.stringify(change)}`);

      withMutation(db, {
        table_name:     TABLE,
        row_id:         `bulk:${definition_id}:${action}`,
        op:             'bulk_apply',
        payload_before: null,
        payload_after:  null,
        station_id:     String(station_id),
      }, () => {
        // _mutationContextStack now has this mutation's id; nested
        // songMetadataValuesCreate/Delete calls inherit it as parent.
        for (const songId of song_ids) {
          if (action === 'clear') {
            const rows = db.prepare(
              `SELECT uuid FROM ${TABLE} WHERE song_id = ? AND definition_id = ? AND deleted_at IS NULL`
            ).all(songId, definition_id);
            for (const row of rows) {
              songMetadataValuesDelete(db, row.uuid, station_id);
              smvOperations++;
            }
          } else if (action === 'set') {
            const rows = db.prepare(
              `SELECT uuid FROM ${TABLE} WHERE song_id = ? AND definition_id = ? AND deleted_at IS NULL`
            ).all(songId, definition_id);
            for (const row of rows) {
              songMetadataValuesDelete(db, row.uuid, station_id);
              smvOperations++;
            }
            songMetadataValuesCreate(db, {
              song_id:             songId,
              definition_id,
              value_text:          change.value_text          ?? null,
              value_vocabulary_id: change.value_vocabulary_id ?? null,
              station_id,
            });
            smvOperations++;
          } else if (action === 'add') {
            for (const vocabId of (change.value_vocabulary_ids ?? [])) {
              const exists = db.prepare(
                `SELECT id FROM ${TABLE} WHERE song_id = ? AND definition_id = ? AND value_vocabulary_id = ? AND deleted_at IS NULL`
              ).get(songId, definition_id, vocabId);
              if (!exists) {
                songMetadataValuesCreate(db, {
                  song_id:             songId,
                  definition_id,
                  value_text:          null,
                  value_vocabulary_id: vocabId,
                  station_id,
                });
                smvOperations++;
              }
            }
          } else {
            throw new Error(`[bulk_apply] unknown action: ${action}`);
          }
          songsAffected++;
        }
      });
    }
  })();

  return { ok: true, songsAffected, smvOperations };
}

// ── IPC installation ──────────────────────────────────────────────────────────

function installSongMetadataValues(ipcMain, db) {
  ipcMain.handle('song_metadata_values:list', (_, stationId, opts) => {
    try { return { ok: true, rows: songMetadataValuesList(db, stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('song_metadata_values:get-by-id', (_, uuid) => {
    try { return { ok: true, row: songMetadataValuesGet(db, uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('song_metadata_values:create', (_, payload) => {
    try { return { ok: true, row: songMetadataValuesCreate(db, payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('song_metadata_values:update', (_, uuid, patch) => {
    try { return { ok: true, row: songMetadataValuesUpdate(db, uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('song_metadata_values:delete', (_, uuid, stationId) => {
    try { return { ok: true, ...songMetadataValuesDelete(db, uuid, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('song_metadata_values:bulk-apply', (_, payload) => {
    try { return metadataValuesBulkApply(db, payload); }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[song_metadata_values] handlers installed');
}

module.exports = {
  installSongMetadataValues,
  validateScope,
  songMetadataValuesList,
  songMetadataValuesGet,
  songMetadataValuesCreate,
  songMetadataValuesUpdate,
  songMetadataValuesDelete,
  metadataValuesBulkApply,
};
