'use strict';

// electron/sync/handlers/song_metadata_values.js — generated by scripts/generate-handlers.js
// IPC handlers for the song_metadata_values table (station-scoped).
// Channels: song_metadata_values:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.songMetadataValues.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE              = 'song_metadata_values';
const HAS_STATION_ID_COL = true;
const PATCHABLE          = ["song_id","definition_id","value_text","value_vocabulary_id","updated_at"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[song_metadata_values] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'station') {
    throw new Error(`[song_metadata_values] expected station-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function songMetadataValuesList(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function songMetadataValuesGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function songMetadataValuesCreate(db, payload) {
  validateScope();
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[song_metadata_values] station_id is required for station-scoped create`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     payload.station_id,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (uuid, station_id, song_id, definition_id, value_text, value_vocabulary_id, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(row.uuid, row.station_id, row.song_id, row.definition_id, row.value_text, row.value_vocabulary_id, row.created_at, row.updated_at, row.deleted_at);
  });
  return songMetadataValuesGet(db, uuid);
}

function songMetadataValuesUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[song_metadata_values] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[song_metadata_values] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[song_metadata_values] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     existing.station_id,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return songMetadataValuesGet(db, uuid);
}

function songMetadataValuesDelete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[song_metadata_values] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     (stationId ?? existing.station_id),
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}



// ── Bulk apply ────────────────────────────────────────────────────────────────
//
// Atomically applies a batch of per-definition changes across a set of songs.
// Each BulkChange maps to one parent mutation; each per-song smv operation
// creates a child mutation that inherits the parent via _mutationContextStack.
//
// change.action semantics:
//   'set'   — delete all existing smv rows for song+definition, then insert one
//             new row (value_text or value_vocabulary_id).
//   'add'   — additive for multi_choice: insert vocab rows not already present.
//             Existing tags are preserved; duplicates are silently skipped.
//   'clear' — soft-delete all smv rows for song+definition (any value).

function metadataValuesBulkApply(db, { song_ids, changes, station_id }) {
  validateScope();
  if (!Array.isArray(song_ids) || song_ids.length === 0) throw new Error('[bulk_apply] song_ids must be a non-empty array');
  if (!Array.isArray(changes) || changes.length === 0)   throw new Error('[bulk_apply] changes must be a non-empty array');
  if (station_id == null) throw new Error('[bulk_apply] station_id is required');

  let songsAffected = 0;
  let smvOperations = 0;

  // Single outer transaction — any inner failure rolls back everything.
  db.transaction(() => {
    for (const change of changes) {
      const { definition_id, action } = change;
      if (!definition_id || !action) throw new Error(`[bulk_apply] invalid change: ${JSON.stringify(change)}`);

      const def = db.prepare(
        `SELECT data_type FROM metadata_definitions WHERE id = ? AND deleted_at IS NULL`
      ).get(definition_id);
      if (!def) {
        throw new Error(`[bulk_apply] definition ${definition_id} not found or deleted`);
      }
      if (action === 'set' && def.data_type === 'multi_choice') {
        throw new Error(`[bulk_apply] action 'set' is invalid for multi_choice definition ${definition_id} ('${def.data_type}'); use 'add' instead`);
      }
      if (action === 'add' && def.data_type !== 'multi_choice') {
        throw new Error(`[bulk_apply] action 'add' is only valid for multi_choice definitions; definition ${definition_id} is '${def.data_type}'`);
      }

      for (const songId of song_ids) {
        if (action === 'clear') {
          const rows = db.prepare(
            `SELECT uuid FROM ${TABLE} WHERE song_id = ? AND definition_id = ? AND deleted_at IS NULL`
          ).all(songId, definition_id);
          for (const row of rows) {
            songMetadataValuesDelete(db, row.uuid, station_id);
            smvOperations++;
          }
        } else if (action === 'set') {
          const rows = db.prepare(
            `SELECT uuid FROM ${TABLE} WHERE song_id = ? AND definition_id = ? AND deleted_at IS NULL`
          ).all(songId, definition_id);
          for (const row of rows) {
            songMetadataValuesDelete(db, row.uuid, station_id);
            smvOperations++;
          }
          songMetadataValuesCreate(db, {
            song_id:             songId,
            definition_id,
            value_text:          change.value_text          ?? null,
            value_vocabulary_id: change.value_vocabulary_id ?? null,
            station_id,
          });
          smvOperations++;
        } else if (action === 'add') {
          for (const vocabId of (change.value_vocabulary_ids ?? [])) {
            const exists = db.prepare(
              `SELECT id FROM ${TABLE} WHERE song_id = ? AND definition_id = ? AND value_vocabulary_id = ? AND deleted_at IS NULL`
            ).get(songId, definition_id, vocabId);
            if (!exists) {
              songMetadataValuesCreate(db, {
                song_id:             songId,
                definition_id,
                value_text:          null,
                value_vocabulary_id: vocabId,
                station_id,
              });
              smvOperations++;
            }
          }
        } else {
          throw new Error(`[bulk_apply] unknown action: ${action}`);
        }
        songsAffected++;
      }
    }
  })();

  return { ok: true, songsAffected, smvOperations };
}

// ── List by song ──────────────────────────────────────────────────────────────
//
// Returns all active smv rows for a given set of song_ids. Server-side
// filtering replaces the old renderer pattern: list(stationId, { limit:10000 })
// + client-side filter. For a 5000-song library with 10+ columns this was
// scanning every smv row; now only rows for the requested songs are returned.

function metadataValuesListBySong(db, songIds, stationId) {
  if (!Array.isArray(songIds) || songIds.length === 0) return [];
  if (stationId == null) throw new Error('[list-by-song] station_id is required');
  const ph = songIds.map(() => '?').join(', ');
  return db.prepare(
    `SELECT uuid, song_id, definition_id, value_text, value_vocabulary_id, station_id, created_at, updated_at
     FROM ${TABLE}
     WHERE deleted_at IS NULL AND station_id = ? AND song_id IN (${ph})`
  ).all(String(stationId), ...songIds);
}

// ── Upsert ────────────────────────────────────────────────────────────────────
//
// Single-call replacement for the renderer's old create-vs-update decision logic.
// Handler decides the right operation by querying current state.
//
// Single-row path (text / number / date / boolean / single_choice):
//   payload: { song_id, definition_id, station_id, value_text?, value_vocabulary_id? }
//   • Both values null + row exists  → soft-delete (operator clear). Returns action: 'cleared'.
//   • Both values null + no row      → noop. Returns action: 'no-change'.
//   • Row exists + values unchanged  → noop. Returns action: 'no-change', uuid.
//   • Row exists + values changed    → update. Returns action: 'updated', uuid.
//   • No row                         → insert. Returns action: 'created', uuid.
//
// Multi-choice diff path (value_vocabulary_ids: number[] present):
//   payload: { song_id, definition_id, station_id, value_vocabulary_ids }
//   Fetches existing active rows, computes adds/removes, applies atomically.
//   Dedup guard: each toAdd id is re-queried before inserting to handle
//   race conditions (double-click, optimistic-state desync, network retry).
//   Returns action: 'updated' | 'no-change'.

function metadataValuesUpsert(db, { song_id, definition_id, station_id, value_text, value_vocabulary_id, value_vocabulary_ids }) {
  validateScope();
  if (station_id == null)   throw new Error('[upsert] station_id is required');
  if (!song_id)             throw new Error('[upsert] song_id is required');
  if (!definition_id)       throw new Error('[upsert] definition_id is required');

  // ── Multi-choice diff path ────────────────────────────────────────────────
  if (Array.isArray(value_vocabulary_ids)) {
    const existing = db.prepare(
      `SELECT uuid, value_vocabulary_id FROM ${TABLE}
       WHERE song_id = ? AND definition_id = ? AND deleted_at IS NULL`
    ).all(song_id, definition_id);

    const existingIds = new Set(existing.map(r => r.value_vocabulary_id));
    const targetIds   = new Set(value_vocabulary_ids);

    const toAdd    = value_vocabulary_ids.filter(id => !existingIds.has(id));
    const toRemove = existing.filter(r => !targetIds.has(r.value_vocabulary_id));

    if (toAdd.length === 0 && toRemove.length === 0) {
      return { ok: true, action: 'no-change' };
    }

    db.transaction(() => {
      for (const vocabId of toAdd) {
        // Correction 1: re-query inside transaction to guard against race conditions
        // (renderer double-click, optimistic desync, network retry).
        const alreadyExists = db.prepare(
          `SELECT id FROM ${TABLE} WHERE song_id = ? AND definition_id = ? AND value_vocabulary_id = ? AND deleted_at IS NULL`
        ).get(song_id, definition_id, vocabId);
        if (alreadyExists) continue;
        songMetadataValuesCreate(db, { song_id, definition_id, value_vocabulary_id: vocabId, station_id, value_text: null });
      }
      for (const row of toRemove) {
        songMetadataValuesDelete(db, row.uuid, station_id);
      }
    })();

    return { ok: true, action: 'updated' };
  }

  // ── Single-row path ───────────────────────────────────────────────────────
  const existing = db.prepare(
    `SELECT * FROM ${TABLE} WHERE song_id = ? AND definition_id = ? AND deleted_at IS NULL`
  ).get(song_id, definition_id);

  const isNull = (value_text == null) && (value_vocabulary_id == null);

  if (isNull) {
    // Operator clear: soft-delete existing row, or noop if nothing is set.
    if (existing) {
      songMetadataValuesDelete(db, existing.uuid, station_id);
      return { ok: true, action: 'cleared' };
    }
    return { ok: true, action: 'no-change' };
  }

  if (existing) {
    const sameText  = existing.value_text          === (value_text          ?? null);
    const sameVocab = existing.value_vocabulary_id === (value_vocabulary_id ?? null);
    if (sameText && sameVocab) {
      return { ok: true, action: 'no-change', uuid: existing.uuid };
    }
    songMetadataValuesUpdate(db, existing.uuid, {
      value_text:          value_text          ?? null,
      value_vocabulary_id: value_vocabulary_id ?? null,
    });
    return { ok: true, action: 'updated', uuid: existing.uuid };
  }

  const created = songMetadataValuesCreate(db, {
    song_id, definition_id, station_id,
    value_text:          value_text          ?? null,
    value_vocabulary_id: value_vocabulary_id ?? null,
  });
  return { ok: true, action: 'created', uuid: created?.uuid };
}

// ── IPC installation ──────────────────────────────────────────────────────────

function installSongMetadataValues(ipcMain, db) {
  ipcMain.handle('song_metadata_values:list', (_, stationId, opts) => {
    try { return { ok: true, rows: songMetadataValuesList(db, stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('song_metadata_values:get-by-id', (_, uuid) => {
    try { return { ok: true, row: songMetadataValuesGet(db, uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('song_metadata_values:create', (_, payload) => {
    try { return { ok: true, row: songMetadataValuesCreate(db, payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('song_metadata_values:update', (_, uuid, patch) => {
    try { return { ok: true, row: songMetadataValuesUpdate(db, uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('song_metadata_values:delete', (_, uuid, stationId) => {
    try { return { ok: true, ...songMetadataValuesDelete(db, uuid, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('song_metadata_values:bulk-apply', (_, payload) => {
    try { return metadataValuesBulkApply(db, payload); }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('song_metadata_values:list-by-song', (_, songIds, stationId) => {
    try { return { ok: true, rows: metadataValuesListBySong(db, songIds, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('song_metadata_values:upsert', (_, payload) => {
    try { return metadataValuesUpsert(db, payload); }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[song_metadata_values] handlers installed');
}

module.exports = {
  installSongMetadataValues,
  validateScope,
  songMetadataValuesList,
  songMetadataValuesGet,
  songMetadataValuesCreate,
  songMetadataValuesUpdate,
  songMetadataValuesDelete,
  metadataValuesBulkApply,
  metadataValuesListBySong,
  metadataValuesUpsert,
};
