'use strict';

// electron/sync/handlers/station_config_kv.js — generated by scripts/generate-handlers.js
// IPC handlers for the station_config_kv table (station-scoped).
// Channels: station_config_kv:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.stationConfigKv.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE              = 'station_config_kv';
const HAS_STATION_ID_COL = true;
const PATCHABLE          = ["value","updated_at"];

// LOCAL-AUTHORITATIVE keys (rider B, 2026-07-22): these station_config_kv keys are per-machine truth
// that must NEVER cross sync in either direction — the is_active lesson (cloud sync clobbered local
// switches). `log_reader_flip` selects a station's PLAYOUT ENGINE; a remote machine's sync must never be
// able to flip it. Enforced two ways: (OUT) writes go through stationConfigKvSetLocal which does NOT log
// a mutation, so nothing ever enters the outbound stream; (IN) the mutation-logging writers below skip
// these keys, so an inbound/legacy mutation can never apply one. (The peer sync engine is also off by
// default, so a flag mutation cannot even exist — this is belt-and-suspenders.)
// Keys that are LOCAL-AUTHORITATIVE: never synced, never created through the mutation path, and
// writable only through set-local. A key missing from this set is REFUSED by set-local — which is
// how the auto-generate toggle shipped broken in 4.4.183/184: the UI wrote, the write was rejected
// every time, and the button snapped back to the stored (absent) value. Verified 2026-08-11: zero
// station_config_kv rows existed for it, against 4 for log_reader_flip.
//
// auto_generate_enabled is local by design — generated_schedule syncs and _autoExtendTick has no
// leader guard, so a synced flag would make "every machine generates this station" the replicated
// policy (backlog: multi-machine two-writer hazard).
// kill_lease is LOCAL on purpose: it is an emergency bypass for a bug in this machine's lease
// logic, and a synced kill switch would disable arbitration everywhere at once.
const LOCAL_ONLY_KEYS = new Set(['log_reader_flip', 'auto_generate_enabled', 'kill_lease']);
const isLocalOnlyKey = (k) => LOCAL_ONLY_KEYS.has(k);

// Direct, MUTATION-LESS upsert for a local-authoritative key. Bypasses withMutation entirely, so the
// value never becomes a syncable mutation. The ONLY sanctioned writer for a LOCAL_ONLY_KEYS key.
function stationConfigKvSetLocal(db, stationId, key, value) {
  if (stationId == null) throw new Error(`[station_config_kv] station_id required for setLocal`);
  const now = new Date().toISOString();
  const existing = db.prepare(`SELECT uuid FROM ${TABLE} WHERE station_id = ? AND key = ?`).get(stationId, key);
  if (existing) {
    db.prepare(`UPDATE ${TABLE} SET value = ?, deleted_at = NULL, updated_at = ? WHERE uuid = ?`).run(value, now, existing.uuid);
    return { ok: true, uuid: existing.uuid };
  }
  const crypto = require('crypto');
  const uuid = crypto.randomUUID();
  db.prepare(`INSERT INTO ${TABLE} (station_id, key, value, uuid, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, NULL)`).run(stationId, key, value, uuid, now, now);
  return { ok: true, uuid };
}
function stationConfigKvGetValue(db, stationId, key) {
  const r = db.prepare(`SELECT value FROM ${TABLE} WHERE station_id = ? AND key = ? AND deleted_at IS NULL`).get(stationId, key);
  return r ? r.value : null;
}

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[station_config_kv] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'station') {
    throw new Error(`[station_config_kv] expected station-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function stationConfigKvList(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function stationConfigKvGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function stationConfigKvCreate(db, payload) {
  validateScope();
  // Rider B: a local-authoritative key must never be created via the mutation-logging path (that is the
  // inbound-apply / legacy vector). Skip it — the sanctioned writer is stationConfigKvSetLocal.
  if (isLocalOnlyKey(payload && payload.key)) return { ok: true, skippedLocalOnly: true };
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[station_config_kv] station_id is required for station-scoped create`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     payload.station_id,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (station_id, key, value, uuid, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?)`
    ).run(row.station_id, row.key, row.value, row.uuid, row.created_at, row.updated_at, row.deleted_at);
  });
  return stationConfigKvGet(db, uuid);
}

function stationConfigKvUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[station_config_kv] row not found: ${uuid}`);
  // Rider B: never mutation-log an update to a local-authoritative key (blocks an inbound update landing
  // on the flag row by uuid). Local flips use stationConfigKvSetLocal.
  if (isLocalOnlyKey(existing.key)) return stationConfigKvGet(db, uuid);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[station_config_kv] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[station_config_kv] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     existing.station_id,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return stationConfigKvGet(db, uuid);
}

function stationConfigKvDelete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[station_config_kv] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     (stationId ?? existing.station_id),
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}


function stationConfigKvUpsertByKey(db, stationId, key, value) {
  validateScope();
  // Rider B: never write a local-authoritative key through the mutation-logging path. This is both the
  // inbound-apply guard and a guard against any caller accidentally syncing the flag.
  if (isLocalOnlyKey(key)) return { ok: true, skippedLocalOnly: true };
  if (stationId == null) throw new Error(`[station_config_kv] station_id required for upsertByKey`);
  const existing = db.prepare(
    `SELECT * FROM ${TABLE} WHERE station_id = ? AND key = ?`
  ).get(stationId, key);
  const now = new Date().toISOString();
  if (!existing) {
    const uuid = crypto.randomUUID();
    const row  = { station_id: stationId, key: key, value: value, uuid, created_at: now, updated_at: now, deleted_at: null };
    const payloadAfter = serializePayload(row, TABLE);
    withMutation(db, {
      table_name: TABLE, row_id: uuid, op: 'insert',
      payload_before: null, payload_after: payloadAfter,
      station_id: stationId, actor_id: null,
    }, () => {
      db.prepare(
        `INSERT INTO ${TABLE} (station_id, key, value, uuid, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?)`
      ).run(row.station_id, row.key, row.value, row.uuid, row.created_at, row.updated_at, row.deleted_at);
    });
    return stationConfigKvGet(db, uuid);
  }
  const before  = serializePayload(existing, TABLE);
  const updated = { ...existing, value: value, deleted_at: null, updated_at: now };
  const after   = serializePayload(updated, TABLE);
  withMutation(db, {
    table_name: TABLE, row_id: existing.uuid, op: 'update',
    payload_before: before, payload_after: after,
    station_id: stationId, actor_id: null,
  }, () => {
    db.prepare(
      `UPDATE ${TABLE} SET value = ?, deleted_at = NULL, updated_at = ? WHERE uuid = ?`
    ).run(value, now, existing.uuid);
  });
  return stationConfigKvGet(db, existing.uuid);
}

function stationConfigKvRemoveByKey(db, stationId, key) {
  validateScope();
  if (stationId == null) throw new Error(`[station_config_kv] station_id required for removeByKey`);
  const existing = db.prepare(
    `SELECT * FROM ${TABLE} WHERE station_id = ? AND key = ? AND deleted_at IS NULL`
  ).get(stationId, key);
  if (!existing) return { ok: true, alreadyMissing: true };
  const before = serializePayload(existing, TABLE);
  const now    = new Date().toISOString();
  withMutation(db, {
    table_name: TABLE, row_id: existing.uuid, op: 'delete',
    payload_before: before, payload_after: null,
    station_id: stationId, actor_id: null,
  }, () => {
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, existing.uuid);
  });
  return { ok: true };
}


// ── IPC installation ──────────────────────────────────────────────────────────

function installStationConfigKv(ipcMain, db) {
  const getDb = (typeof db === 'function') ? db : () => db;
  ipcMain.handle('station_config_kv:list', (_, stationId, opts) => {
    try { return { ok: true, rows: stationConfigKvList(getDb(), stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('station_config_kv:get-by-id', (_, uuid) => {
    try { return { ok: true, row: stationConfigKvGet(getDb(), uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('station_config_kv:create', (_, payload) => {
    try { return { ok: true, row: stationConfigKvCreate(getDb(), payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('station_config_kv:update', (_, uuid, patch) => {
    try { return { ok: true, row: stationConfigKvUpdate(getDb(), uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('station_config_kv:delete', (_, uuid, stationId) => {
    try { return { ok: true, ...stationConfigKvDelete(getDb(), uuid, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });


  ipcMain.handle('station_config_kv:upsert-by-key', (_, stationId, key, value) => {
    try { return { ok: true, row: stationConfigKvUpsertByKey(getDb(), stationId, key, value) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('station_config_kv:remove-by-key', (_, stationId, key) => {
    try { return { ok: true, ...stationConfigKvRemoveByKey(getDb(), stationId, key) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  // Rider B: the LOCAL-ONLY setter — the canary toggle for log_reader_flip goes through here (no
  // mutation logged → never syncs). Rejects any non-local-only key so it can't be misused to bypass sync.
  ipcMain.handle('station_config_kv:set-local', (_, stationId, key, value) => {
    try {
      if (!isLocalOnlyKey(key)) {
        // Loud: a refused write is invisible to the operator unless the caller checks the verdict,
        // and 4.4.183/184 proved a caller will forget.
        console.warn(`[station_config_kv] set-local REFUSED station=${stationId} key="${key}" — not in LOCAL_ONLY_KEYS`);
        return { ok: false, error: `set-local refuses non-local-only key "${key}"` };
      }
      console.log(`[station_config_kv] set-local station=${stationId} key="${key}" value="${value}"`);
      return stationConfigKvSetLocal(getDb(), stationId, key, value);
    } catch (e) { return { ok: false, error: e.message }; }
  });
  ipcMain.handle('station_config_kv:get-value', (_, stationId, key) => {
    try { return { ok: true, value: stationConfigKvGetValue(getDb(), stationId, key) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[station_config_kv] handlers installed');
}

module.exports = {
  installStationConfigKv,
  validateScope,
  stationConfigKvList,
  stationConfigKvGet,
  stationConfigKvCreate,
  stationConfigKvUpdate,
  stationConfigKvDelete,

  stationConfigKvUpsertByKey,
  stationConfigKvRemoveByKey,
  stationConfigKvSetLocal,
  stationConfigKvGetValue,
  isLocalOnlyKey,

};
