'use strict';

// electron/sync/handlers/voice_tracks.js — generated by scripts/generate-handlers.js
// IPC handlers for the voice_tracks table (station-scoped).
// Channels: voice_tracks:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.voiceTracks.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE              = 'voice_tracks';
const HAS_STATION_ID_COL = true;
const PATCHABLE          = ["title","file_path","show_id","clock_slot_id","duration_ms","recorded_by","recorded_at","updated_at"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[voice_tracks] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'station') {
    throw new Error(`[voice_tracks] expected station-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function voiceTracksList(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function voiceTracksGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function voiceTracksCreate(db, payload) {
  validateScope();
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[voice_tracks] station_id is required for station-scoped create`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     payload.station_id,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (title, file_path, show_id, clock_slot_id, duration_ms, recorded_by, recorded_at, station_id, uuid, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(row.title, row.file_path, row.show_id, row.clock_slot_id, row.duration_ms, row.recorded_by, row.recorded_at, row.station_id, row.uuid, row.created_at, row.updated_at, row.deleted_at);
  });
  return voiceTracksGet(db, uuid);
}

function voiceTracksUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[voice_tracks] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[voice_tracks] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[voice_tracks] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     existing.station_id,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return voiceTracksGet(db, uuid);
}

function voiceTracksDelete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[voice_tracks] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     (stationId ?? existing.station_id),
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}



function voiceTracksUpdateById(db, intId, patch) {
  validateScope();
  let existing = db.prepare(`SELECT * FROM ${TABLE} WHERE id = ? AND deleted_at IS NULL`).get(intId);
  if (!existing) throw new Error(`[voice_tracks] row not found: id=${intId}`);
  if (!existing.uuid) {
    const uuid = crypto.randomUUID();
    db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(uuid, intId);
    existing = { ...existing, uuid };
  }
  return voiceTracksUpdate(db, existing.uuid, patch);
}

function voiceTracksDeleteById(db, intId) {
  validateScope();
  let existing = db.prepare(`SELECT * FROM ${TABLE} WHERE id = ? AND deleted_at IS NULL`).get(intId);
  if (!existing) return { ok: true };
  if (!existing.uuid) {
    const uuid = crypto.randomUUID();
    db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(uuid, intId);
    existing = { ...existing, uuid };
  }
  return voiceTracksDelete(db, existing.uuid, existing.station_id);
}

function voiceTracksClearClockSlotId(db, slotId) {
  validateScope();
  const rows = db.prepare(
    `SELECT * FROM ${TABLE} WHERE clock_slot_id = ? AND deleted_at IS NULL`
  ).all(slotId);
  db.transaction(() => {
    for (const row of rows) {
      if (!row.uuid) {
        const uuid = crypto.randomUUID();
        db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(uuid, row.id);
        row.uuid = uuid;
      }
      voiceTracksUpdate(db, row.uuid, { clock_slot_id: null });
    }
  })();
  return { ok: true };
}

// ── IPC installation ──────────────────────────────────────────────────────────

function installVoiceTracks(ipcMain, db) {
  ipcMain.handle('voice_tracks:list', (_, stationId, opts) => {
    try { return { ok: true, rows: voiceTracksList(db, stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('voice_tracks:get-by-id', (_, uuid) => {
    try { return { ok: true, row: voiceTracksGet(db, uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('voice_tracks:create', (_, payload) => {
    try { return { ok: true, row: voiceTracksCreate(db, payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('voice_tracks:update', (_, uuid, patch) => {
    try { return { ok: true, row: voiceTracksUpdate(db, uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('voice_tracks:delete', (_, uuid, stationId) => {
    try { return { ok: true, ...voiceTracksDelete(db, uuid, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('voice_tracks:update-by-id', (_, intId, patch) => {
    try { return { ok: true, row: voiceTracksUpdateById(db, intId, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('voice_tracks:delete-by-id', (_, intId) => {
    try { return { ok: true, ...voiceTracksDeleteById(db, intId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('voice_tracks:clear-clock-slot-id', (_, slotId) => {
    try { return { ok: true, ...voiceTracksClearClockSlotId(db, slotId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[voice_tracks] handlers installed');
}

module.exports = {
  installVoiceTracks,
  validateScope,
  voiceTracksList,
  voiceTracksGet,
  voiceTracksCreate,
  voiceTracksUpdate,
  voiceTracksDelete,
  voiceTracksUpdateById,
  voiceTracksDeleteById,
  voiceTracksClearClockSlotId,
};
