'use strict';

// electron/sync/handlers/voice_tracks.js — generated by scripts/generate-handlers.js
// IPC handlers for the voice_tracks table (station-scoped).
// Channels: voice_tracks:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.voiceTracks.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE              = 'voice_tracks';
const HAS_STATION_ID_COL = true;
const PATCHABLE          = ["title","file_path","show_id","clock_slot_id","duration_ms","recorded_by","recorded_at","updated_at"];

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[voice_tracks] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== 'station') {
    throw new Error(`[voice_tracks] expected station-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function voiceTracksList(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function voiceTracksGet(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function voiceTracksCreate(db, payload) {
  validateScope();
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[voice_tracks] station_id is required for station-scoped create`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     payload.station_id,
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} (title, file_path, show_id, clock_slot_id, duration_ms, recorded_by, recorded_at, station_id, uuid, created_at, updated_at, deleted_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`
    ).run(row.title, row.file_path, row.show_id, row.clock_slot_id, row.duration_ms, row.recorded_by, row.recorded_at, row.station_id, row.uuid, row.created_at, row.updated_at, row.deleted_at);
  });
  return voiceTracksGet(db, uuid);
}

function voiceTracksUpdate(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[voice_tracks] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[voice_tracks] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[voice_tracks] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     existing.station_id,
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return voiceTracksGet(db, uuid);
}

// -- The delete contract, for voice tracks ------------------------------------
// A delete RETRACTS THE TAKE'S FUTURE and NEVER EDITS ITS PAST.
//
// Identical in shape to spots (handlers/spots.js retractSpotReferences) and for the identical
// reason. schedule:insertVoiceTrack (electron/main.js:8624) places a take into the log as a FROZEN
// COPY: song_id NULL and the take's file_path copied straight in. There is no voice_track_id column
// on generated_schedule. Playout plays that path directly and never consults this table, so
// tombstoning the row here stopped nothing that was already scheduled -- a deleted jock break kept
// airing, exactly as the deleted OV spot did on 2026-09-14.
//
// Found by the sweep Jeff asked for after the spot fix, and fixed in the same pass rather than left
// to surface live in three weeks. docs/deleted-spot-still-airing-2026-09-14.md
//
// WHY THE MATCH IS song_id IS NULL AND file_path. There is no id to match on. A music or sweeper row
// always carries a song_id, so `song_id IS NULL` excludes every one of them, and the take's file is
// written per-recording by writeTakeFile() -- unique to this take.
//
// content_class is deliberately NOT in the predicate, and THIS IS THE TRAP. insertVoiceTrack does
// not set the column, and generated_schedule.content_class DEFAULTS TO 'MUSIC' (migration v31). So a
// voice track sits in the log LABELLED MUSIC -- 37 such rows on OV's database, measured 2026-09-14.
// A filter like content_class='VT', or IS NULL, would match exactly nothing while looking correct.
// song_id IS NULL is the only thing that actually distinguishes a placed take from a song.
//
// PRESERVED, deliberately -- as in the song and spot contracts:
//   * played / missed rows  - the record of what actually went to air.
//   * playing               - audio ON AIR RIGHT NOW. Never yanked from under the operator.
// Only state = 'pending' is retracted.
//
// UNLOGGED, and also wired into the inbound apply path in merge-engine.js: generated_schedule does
// not sync (synced-tables.js RULING A), so each install must retract from its own log.
function retractVoiceTrackReferences(db, track, nowIso) {
  const out = { pendingLog: 0 };
  if (!track || !track.file_path) return out;
  try {
    out.pendingLog = db.prepare(
      `UPDATE generated_schedule SET deleted_at = ?, updated_at = ?
        WHERE station_id = ? AND song_id IS NULL AND state = 'pending'
          AND deleted_at IS NULL AND file_path = ?`
    ).run(nowIso, nowIso, track.station_id, track.file_path).changes || 0;
  } catch (e) {
    console.error(`[voice_tracks] future-airings retraction failed for "${track.title}": ${e.message}`);
  }
  return out;
}

function voiceTracksDelete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[voice_tracks] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);
  let retracted = null;

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     (stationId ?? existing.station_id),
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
    // The tombstone stops nothing that is already in the log. This does.
    retracted = retractVoiceTrackReferences(db, existing, now);
  });
  console.log(`[voice_tracks] "${existing.title}" deleted - ${(retracted && retracted.pendingLog) || 0} future airing(s) retracted`);
  return { ok: true, retracted };
}



function voiceTracksUpdateById(db, intId, patch) {
  validateScope();
  let existing = db.prepare(`SELECT * FROM ${TABLE} WHERE id = ? AND deleted_at IS NULL`).get(intId);
  if (!existing) throw new Error(`[voice_tracks] row not found: id=${intId}`);
  if (!existing.uuid) {
    const uuid = crypto.randomUUID();
    db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(uuid, intId);
    existing = { ...existing, uuid };
  }
  return voiceTracksUpdate(db, existing.uuid, patch);
}

function voiceTracksDeleteById(db, intId) {
  validateScope();
  let existing = db.prepare(`SELECT * FROM ${TABLE} WHERE id = ? AND deleted_at IS NULL`).get(intId);
  if (!existing) return { ok: true };
  if (!existing.uuid) {
    const uuid = crypto.randomUUID();
    db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(uuid, intId);
    existing = { ...existing, uuid };
  }
  return voiceTracksDelete(db, existing.uuid, existing.station_id);
}

function voiceTracksClearClockSlotId(db, slotId) {
  validateScope();
  const rows = db.prepare(
    `SELECT * FROM ${TABLE} WHERE clock_slot_id = ? AND deleted_at IS NULL`
  ).all(slotId);
  db.transaction(() => {
    for (const row of rows) {
      if (!row.uuid) {
        const uuid = crypto.randomUUID();
        db.prepare(`UPDATE ${TABLE} SET uuid = ? WHERE id = ?`).run(uuid, row.id);
        row.uuid = uuid;
      }
      voiceTracksUpdate(db, row.uuid, { clock_slot_id: null });
    }
  })();
  return { ok: true };
}

// ── IPC installation ──────────────────────────────────────────────────────────

function installVoiceTracks(ipcMain, db) {
  const getDb = (typeof db === 'function') ? db : () => db;
  ipcMain.handle('voice_tracks:list', (_, stationId, opts) => {
    try { return { ok: true, rows: voiceTracksList(getDb(), stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('voice_tracks:get-by-id', (_, uuid) => {
    try { return { ok: true, row: voiceTracksGet(getDb(), uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('voice_tracks:create', (_, payload) => {
    try { return { ok: true, row: voiceTracksCreate(getDb(), payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('voice_tracks:update', (_, uuid, patch) => {
    try { return { ok: true, row: voiceTracksUpdate(getDb(), uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('voice_tracks:delete', (_, uuid, stationId) => {
    try { return { ok: true, ...voiceTracksDelete(getDb(), uuid, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('voice_tracks:update-by-id', (_, intId, patch) => {
    try { return { ok: true, row: voiceTracksUpdateById(getDb(), intId, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('voice_tracks:delete-by-id', (_, intId) => {
    try { return { ok: true, ...voiceTracksDeleteById(getDb(), intId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('voice_tracks:clear-clock-slot-id', (_, slotId) => {
    try { return { ok: true, ...voiceTracksClearClockSlotId(getDb(), slotId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[voice_tracks] handlers installed');
}

module.exports = {
  installVoiceTracks,
  validateScope,
  voiceTracksList,
  voiceTracksGet,
  voiceTracksCreate,
  voiceTracksUpdate,
  voiceTracksDelete,
  retractVoiceTrackReferences,
  voiceTracksUpdateById,
  voiceTracksDeleteById,
  voiceTracksClearClockSlotId,
};
