const fs = require('fs');
const path = require('path');
const os = require('os');

console.log('\n  Ether — Full Playback Update\n  ----------------------------\n');

// ============================================================
// STEP 1: Fix tauri.conf.json (remove assetProtocol that crashes)
// ============================================================

const confPath = path.join('src-tauri', 'tauri.conf.json');
if (fs.existsSync(confPath)) {
  const conf = JSON.parse(fs.readFileSync(confPath, 'utf8'));
  if (conf.app && conf.app.security) {
    delete conf.app.security.assetProtocol;
    conf.app.security.csp = "default-src 'self'; style-src 'self' 'unsafe-inline'; script-src 'self'; media-src 'self' asset: https://asset.localhost; img-src 'self' asset: https://asset.localhost";
  }
  fs.writeFileSync(confPath, JSON.stringify(conf, null, 2), 'utf8');
  console.log('  FIXED   src-tauri/tauri.conf.json');
}

// ============================================================
// STEP 2: Delete old database
// ============================================================

const appData = process.env.APPDATA || path.join(os.homedir(), 'AppData', 'Roaming');
const dirs = ['com.openair.app', 'openair'];
for (const d of dirs) {
  const dir = path.join(appData, d);
  if (fs.existsSync(dir)) {
    const files = fs.readdirSync(dir);
    for (const f of files) {
      if (f.includes('openair.db')) {
        fs.unlinkSync(path.join(dir, f));
        console.log('  DELETED ' + path.join(dir, f));
      }
    }
  }
}

// ============================================================
// STEP 3: Database client
// ============================================================

fs.mkdirSync('src/db', { recursive: true });
fs.writeFileSync('src/db/client.ts', [
  'import Database from "@tauri-apps/plugin-sql";',
  'let db: Database | null = null;',
  'export async function getDb(): Promise<Database> { if (!db) { db = await Database.load("sqlite:openair.db"); } return db; }',
  'export async function query<T>(sql: string, params: unknown[] = []): Promise<T[]> { const d = await getDb(); return (await d.select(sql, params)) as T[]; }',
  'export async function queryOne<T>(sql: string, params: unknown[] = []): Promise<T | null> { const rows = await query<T>(sql, params); return rows.length > 0 ? rows[0] : null; }',
  'export async function execute(sql: string, params: unknown[] = []): Promise<{ rowsAffected: number; lastInsertId: number }> { const d = await getDb(); const r = await d.execute(sql, params); return { rowsAffected: r.rowsAffected, lastInsertId: r.lastInsertId }; }',
  'export async function runMigrations(): Promise<void> {',
  '  const d = await getDb();',
  '  await d.execute("CREATE TABLE IF NOT EXISTS artists (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, sort_name TEXT, created_at INTEGER NOT NULL DEFAULT (unixepoch()))");',
  '  await d.execute("CREATE TABLE IF NOT EXISTS albums (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, artist_id INTEGER, year INTEGER, created_at INTEGER NOT NULL DEFAULT (unixepoch()))");',
  '  await d.execute("CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, color TEXT, description TEXT, created_at INTEGER NOT NULL DEFAULT (unixepoch()))");',
  '  await d.execute("CREATE TABLE IF NOT EXISTS songs (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, artist_id INTEGER, album_id INTEGER, file_path TEXT, file_format TEXT, file_size_bytes INTEGER, duration_ms INTEGER NOT NULL DEFAULT 0, genre TEXT, era TEXT, category_id INTEGER, rotation_status TEXT NOT NULL DEFAULT \'active\', daypart_mask INTEGER NOT NULL DEFAULT 16777215, gender TEXT NOT NULL DEFAULT \'unknown\', tags TEXT NOT NULL DEFAULT \'[]\', notes TEXT, created_at INTEGER NOT NULL DEFAULT (unixepoch()), updated_at INTEGER NOT NULL DEFAULT (unixepoch()))");',
  '  const r = await d.select("SELECT COUNT(*) as c FROM categories");',
  '  if ((r as any)[0].c === 0) {',
  '    await d.execute("INSERT INTO categories (code,name,color) VALUES (\'A\',\'Power Current\',\'#ef4444\')");',
  '    await d.execute("INSERT INTO categories (code,name,color) VALUES (\'B\',\'Secondary\',\'#f59e0b\')");',
  '    await d.execute("INSERT INTO categories (code,name,color) VALUES (\'C\',\'Recurrent\',\'#22c55e\')");',
  '    await d.execute("INSERT INTO categories (code,name,color) VALUES (\'D\',\'Gold\',\'#3b82f6\')");',
  '  }',
  '  console.log("DB ready");',
  '}',
].join('\n'), 'utf8');
console.log('  CREATED src/db/client.ts');

// ============================================================
// STEP 4: index.html
// ============================================================

fs.writeFileSync('index.html', '<!DOCTYPE html>\n<html lang="en" class="dark">\n<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>Ether</title></head>\n<body class="bg-zinc-950 text-zinc-100 overflow-hidden">\n<div id="root"></div>\n<script type="module" src="/src/main.tsx"><\/script>\n</body></html>', 'utf8');
console.log('  CREATED index.html');

// ============================================================
// STEP 5: main.tsx
// ============================================================

fs.writeFileSync('src/main.tsx', [
  'import React from "react";',
  'import ReactDOM from "react-dom/client";',
  'import App from "./App";',
  'import "./index.css";',
  'import { runMigrations } from "./db/client";',
  'runMigrations().then(() => console.log("migrations done")).catch(e => console.error("migration error:", e));',
  'ReactDOM.createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);',
].join('\n'), 'utf8');
console.log('  CREATED src/main.tsx');

// ============================================================
// STEP 6: Audio engine
// ============================================================

fs.mkdirSync('src/audio', { recursive: true });
fs.writeFileSync('src/audio/engine.ts', [
  'export type DeckId = "A" | "B";',
  'export type DeckStatus = "idle" | "loading" | "playing" | "paused" | "ended" | "error";',
  '',
  'export interface DeckState {',
  '  id: DeckId; status: DeckStatus; title: string; artist: string;',
  '  filePath: string; durationSec: number; positionSec: number;',
  '  volume: number; error: string | null;',
  '}',
  '',
  'type Listener = (deck: DeckId, state: DeckState) => void;',
  '',
  'class Deck {',
  '  id: DeckId;',
  '  private ctx: AudioContext;',
  '  private gainNode: GainNode;',
  '  private source: AudioBufferSourceNode | null = null;',
  '  private buf: AudioBuffer | null = null;',
  '  private startedAt = 0;',
  '  private offset = 0;',
  '  private timer: any = null;',
  '  private notify: Listener;',
  '  status: DeckStatus = "idle";',
  '  title = ""; artist = ""; filePath = "";',
  '  durationSec = 0; volume = 1; error: string | null = null;',
  '',
  '  constructor(id: DeckId, ctx: AudioContext, notify: Listener) {',
  '    this.id = id; this.ctx = ctx; this.notify = notify;',
  '    this.gainNode = ctx.createGain(); this.gainNode.connect(ctx.destination);',
  '  }',
  '',
  '  get positionSec(): number {',
  '    if (this.status !== "playing") return this.offset;',
  '    return this.offset + (this.ctx.currentTime - this.startedAt);',
  '  }',
  '',
  '  getState(): DeckState {',
  '    return { id: this.id, status: this.status, title: this.title, artist: this.artist,',
  '      filePath: this.filePath, durationSec: this.durationSec, positionSec: this.positionSec,',
  '      volume: this.volume, error: this.error };',
  '  }',
  '',
  '  private emit() { this.notify(this.id, this.getState()); }',
  '',
  '  async load(filePath: string, title: string, artist: string) {',
  '    this.stop();',
  '    this.status = "loading"; this.filePath = filePath;',
  '    this.title = title; this.artist = artist; this.error = null;',
  '    this.emit();',
  '    try {',
  '      const url = "https://asset.localhost/" + filePath;',
  '      const resp = await fetch(url);',
  '      if (!resp.ok) throw new Error("fetch failed: " + resp.status);',
  '      const ab = await resp.arrayBuffer();',
  '      this.buf = await this.ctx.decodeAudioData(ab);',
  '      this.durationSec = this.buf.duration;',
  '      this.status = "idle"; this.emit();',
  '    } catch (e) {',
  '      this.status = "error"; this.error = String(e); this.emit();',
  '    }',
  '  }',
  '',
  '  play(fromSec = 0) {',
  '    if (!this.buf) return;',
  '    if (this.status === "playing") this.killSource();',
  '    const src = this.ctx.createBufferSource();',
  '    src.buffer = this.buf; src.connect(this.gainNode);',
  '    src.start(0, fromSec);',
  '    this.source = src; this.startedAt = this.ctx.currentTime;',
  '    this.offset = fromSec; this.status = "playing"; this.emit();',
  '    src.onended = () => {',
  '      if (this.status === "playing") {',
  '        this.status = "ended"; this.offset = this.durationSec;',
  '        this.clearTimer(); this.emit();',
  '      }',
  '    };',
  '    this.startTimer();',
  '  }',
  '',
  '  pause() {',
  '    if (this.status !== "playing") return;',
  '    this.offset = this.positionSec; this.killSource();',
  '    this.status = "paused"; this.clearTimer(); this.emit();',
  '  }',
  '',
  '  resume() { if (this.status === "paused") this.play(this.offset); }',
  '',
  '  stop() {',
  '    this.killSource(); this.clearTimer();',
  '    this.status = "idle"; this.offset = 0; this.emit();',
  '  }',
  '',
  '  setVolume(v: number) {',
  '    this.volume = Math.max(0, Math.min(1, v));',
  '    this.gainNode.gain.setTargetAtTime(this.volume, this.ctx.currentTime, 0.01);',
  '  }',
  '',
  '  fadeTo(vol: number, sec: number) {',
  '    this.gainNode.gain.linearRampToValueAtTime(vol, this.ctx.currentTime + sec);',
  '  }',
  '',
  '  private killSource() { try { this.source?.stop(); } catch {} this.source = null; }',
  '  private startTimer() { this.clearTimer(); this.timer = setInterval(() => this.emit(), 200); }',
  '  private clearTimer() { if (this.timer) { clearInterval(this.timer); this.timer = null; } }',
  '}',
  '',
  'export class AudioEngine {',
  '  private ctx: AudioContext | null = null;',
  '  private deckA: Deck | null = null;',
  '  private deckB: Deck | null = null;',
  '  private listeners = new Set<Listener>();',
  '  private onEvt: Listener = (id, st) => { this.listeners.forEach(l => l(id, st)); };',
  '',
  '  init() {',
  '    if (this.ctx) return;',
  '    this.ctx = new AudioContext({ sampleRate: 44100 });',
  '    this.deckA = new Deck("A", this.ctx, this.onEvt);',
  '    this.deckB = new Deck("B", this.ctx, this.onEvt);',
  '  }',
  '',
  '  on(fn: Listener): () => void { this.listeners.add(fn); return () => this.listeners.delete(fn); }',
  '  getDeck(id: DeckId): Deck | null { return id === "A" ? this.deckA : this.deckB; }',
  '',
  '  async loadToDeck(id: DeckId, filePath: string, title: string, artist: string) {',
  '    this.init(); const d = this.getDeck(id); if (d) await d.load(filePath, title, artist);',
  '  }',
  '',
  '  crossfade(fromId: DeckId, toId: DeckId, ms = 2000) {',
  '    const from = this.getDeck(fromId); const to = this.getDeck(toId);',
  '    if (!from || !to) return;',
  '    to.play(); from.fadeTo(0, ms / 1000);',
  '    setTimeout(() => from.stop(), ms + 50);',
  '  }',
  '}',
  '',
  'export const engine = new AudioEngine();',
].join('\n'), 'utf8');
console.log('  CREATED src/audio/engine.ts');

// ============================================================
// STEP 7: App.tsx — Library + Live Assist with playback
// ============================================================

fs.writeFileSync('src/App.tsx', [
'import { useState, useEffect, useCallback } from "react";',
'import { query, execute, queryOne } from "./db/client";',
'import { open } from "@tauri-apps/plugin-dialog";',
'import { readDir } from "@tauri-apps/plugin-fs";',
'import { engine, DeckState } from "./audio/engine";',
'',
'type Panel = "live" | "library" | "clocks" | "logs" | "spots" | "settings";',
'',
'interface SongRow {',
'  id: number; title: string; file_path: string | null;',
'  artist_name: string | null; album_title: string | null;',
'  genre: string | null; duration_ms: number;',
'  category_code: string | null; category_color: string | null;',
'}',
'',
'const EXTS = [".mp3",".flac",".ogg",".wav",".m4a",".aac",".wma",".aiff"];',
'function isAudio(n: string) { return EXTS.some(e => n.toLowerCase().endsWith(e)); }',
'function titleFromFile(p: string) { return (p.split(/[\\\\/]/).pop() || p).replace(/\\.[^.]+$/, "").replace(/[_-]/g, " ").replace(/^\\d+\\.?\\s*/, ""); }',
'function fmtExt(p: string) { return (p.split(".").pop() || "").toLowerCase(); }',
'function fmtTime(s: number) { if (!s || s < 0) return "0:00"; return Math.floor(s/60) + ":" + String(Math.floor(s%60)).padStart(2,"0"); }',
'',
'export default function App() {',
'  const [panel, setPanel] = useState<Panel>("live");',
'  const [onAir, setOnAir] = useState(false);',
'  const [deckA, setDeckA] = useState<DeckState | null>(null);',
'  const [deckB, setDeckB] = useState<DeckState | null>(null);',
'',
'  useEffect(() => {',
'    engine.init();',
'    return engine.on((id, st) => { if (id === "A") setDeckA({...st}); else setDeckB({...st}); });',
'  }, []);',
'',
'  const loadA = useCallback((s: SongRow) => { if (s.file_path) engine.loadToDeck("A", s.file_path, s.title, s.artist_name || ""); }, []);',
'  const loadB = useCallback((s: SongRow) => { if (s.file_path) engine.loadToDeck("B", s.file_path, s.title, s.artist_name || ""); }, []);',
'',
'  const cls = onAir',
'    ? "ml-3 px-3 py-1 rounded text-xs font-bold uppercase tracking-wider bg-red-600 text-white animate-pulse"',
'    : "ml-3 px-3 py-1 rounded text-xs font-bold uppercase tracking-wider bg-zinc-700 text-zinc-400 hover:bg-zinc-600";',
'',
'  return (',
'    <div className="h-screen flex flex-col bg-zinc-950 text-zinc-100">',
'      <header className="h-12 flex items-center justify-between px-4 bg-zinc-900 border-b border-zinc-800 shrink-0">',
'        <div className="flex items-center gap-3">',
'          <span className="text-lg font-bold tracking-tight"><span className="text-blue-400">Eth</span>er</span>',
'          <span className="text-xs text-zinc-500">v0.1.0</span>',
'        </div>',
'        <div className="flex items-center gap-2 text-sm text-zinc-400">',
'          <ClockDisplay />',
'          <button onClick={() => { engine.init(); setOnAir(!onAir); }} className={cls}>{onAir ? "ON AIR" : "OFF AIR"}</button>',
'        </div>',
'      </header>',
'      <div className="flex flex-1 overflow-hidden">',
'        <Nav active={panel} set={setPanel} />',
'        <main className="flex-1 overflow-auto p-6">',
'          {panel === "live" && <LivePanel deckA={deckA} deckB={deckB} />}',
'          {panel === "library" && <LibraryPanel onLoadA={loadA} onLoadB={loadB} />}',
'          {panel === "clocks" && <PH title="Clock Builder" />}',
'          {panel === "logs" && <PH title="Log Builder" />}',
'          {panel === "spots" && <PH title="Spot Inventory" />}',
'          {panel === "settings" && <PH title="Settings" />}',
'        </main>',
'      </div>',
'      <footer className="h-7 flex items-center justify-between px-4 bg-zinc-900 border-t border-zinc-800 text-[11px] text-zinc-500 shrink-0">',
'        <span>{deckA?.status === "playing" ? "Playing: " + deckA.title : "Ready"}</span>',
'        <span>SQLite | Web Audio | Manual</span>',
'      </footer>',
'    </div>',
'  );',
'}',
'',
'function Nav({ active, set }: { active: Panel; set: (p: Panel) => void }) {',
'  const items: { id: Panel; label: string }[] = [',
'    { id: "live", label: "Live Assist" }, { id: "library", label: "Library" },',
'    { id: "clocks", label: "Clocks" }, { id: "logs", label: "Logs" },',
'    { id: "spots", label: "Spots" }, { id: "settings", label: "Settings" },',
'  ];',
'  return (',
'    <nav className="w-48 bg-zinc-900 border-r border-zinc-800 flex flex-col py-2 shrink-0">',
'      {items.map(i => <button key={i.id} onClick={() => set(i.id)} className={active === i.id ? "px-4 py-2.5 text-sm text-left bg-zinc-800 text-white border-l-2 border-blue-400" : "px-4 py-2.5 text-sm text-left text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 border-l-2 border-transparent"}>{i.label}</button>)}',
'      <div className="mt-auto px-4 py-3 text-[10px] text-zinc-600">Ether v0.1.0<br/>Free forever</div>',
'    </nav>',
'  );',
'}',
'',
'function LivePanel({ deckA, deckB }: { deckA: DeckState | null; deckB: DeckState | null }) {',
'  const handleXfade = () => {',
'    if (deckA?.status === "playing" && deckB?.filePath) engine.crossfade("A", "B", 2000);',
'    else if (deckB?.status === "playing" && deckA?.filePath) engine.crossfade("B", "A", 2000);',
'  };',
'  return (',
'    <div className="space-y-4">',
'      <div className="flex items-center justify-between">',
'        <h1 className="text-xl font-bold">Live Assist</h1>',
'        <button onClick={handleXfade} className="px-4 py-1.5 bg-purple-700 hover:bg-purple-600 rounded text-xs font-bold text-white">CROSSFADE</button>',
'      </div>',
'      <div className="grid grid-cols-2 gap-4">',
'        <DeckCard deck={deckA} deckId="A" color="text-blue-400" />',
'        <DeckCard deck={deckB} deckId="B" color="text-emerald-400" />',
'      </div>',
'      <div className="bg-zinc-900 rounded-lg p-4 border border-zinc-800">',
'        <h2 className="text-xs font-bold text-zinc-400 uppercase mb-3">How to use</h2>',
'        <div className="text-sm text-zinc-500">Go to Library tab, import a music folder, then click the A or B button next to any song to load it to a deck. Come back here to play.</div>',
'      </div>',
'    </div>',
'  );',
'}',
'',
'function DeckCard({ deck, deckId, color }: { deck: DeckState | null; deckId: "A" | "B"; color: string }) {',
'  const d = engine.getDeck(deckId);',
'  const st = deck?.status || "idle";',
'  const pos = deck?.positionSec || 0;',
'  const dur = deck?.durationSec || 0;',
'  const pct = dur > 0 ? (pos / dur) * 100 : 0;',
'',
'  const handlePlay = () => {',
'    if (!d) return;',
'    if (st === "playing") d.pause();',
'    else if (st === "paused") d.resume();',
'    else d.play();',
'  };',
'',
'  const pLabel = st === "playing" ? "Pause" : st === "paused" ? "Resume" : "Play";',
'  const pCls = st === "playing"',
'    ? "px-4 py-1.5 rounded text-xs font-bold flex-1 bg-yellow-600 text-white"',
'    : "px-4 py-1.5 rounded text-xs font-bold flex-1 bg-emerald-700 hover:bg-emerald-600 text-white";',
'',
'  return (',
'    <div className="bg-zinc-900 rounded-lg p-4 border border-zinc-800">',
'      <div className="flex items-center justify-between mb-2">',
'        <span className={"text-xs font-bold uppercase tracking-wider " + color}>{"Deck " + deckId}</span>',
'        <span className={"text-[10px] uppercase " + (st === "playing" ? "text-emerald-400 font-bold" : "text-zinc-500")}>{st}</span>',
'      </div>',
'      <div className="text-sm text-zinc-200 truncate mb-1">{deck?.title || "No track loaded"}</div>',
'      {deck?.artist ? <div className="text-xs text-zinc-500 truncate mb-2">{deck.artist}</div> : null}',
'      <div className="h-2 bg-zinc-800 rounded-full overflow-hidden mb-2">',
'        <div className="h-full bg-blue-500 transition-all" style={{ width: pct + "%" }}></div>',
'      </div>',
'      <div className="flex justify-between text-xs font-mono text-zinc-500 mb-3">',
'        <span>{fmtTime(pos)}</span><span>-{fmtTime(dur - pos)}</span>',
'      </div>',
'      <div className="flex items-center gap-2">',
'        <button onClick={() => d?.stop()} className="px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 rounded text-xs">Stop</button>',
'        <button onClick={handlePlay} className={pCls}>{pLabel}</button>',
'      </div>',
'      <div className="flex items-center gap-2 text-xs text-zinc-500 mt-3">',
'        <span>Vol</span>',
'        <input type="range" min="0" max="100" value={Math.round((deck?.volume || 1) * 100)} onChange={e => d?.setVolume(parseInt(e.target.value) / 100)} className="flex-1 h-1.5 accent-blue-500" />',
'        <span>{Math.round((deck?.volume || 1) * 100)}%</span>',
'      </div>',
'      {deck?.error ? <div className="text-xs text-red-400 mt-2">{deck.error}</div> : null}',
'    </div>',
'  );',
'}',
'',
'function LibraryPanel({ onLoadA, onLoadB }: { onLoadA: (s: SongRow) => void; onLoadB: (s: SongRow) => void }) {',
'  const [songs, setSongs] = useState<SongRow[]>([]);',
'  const [loading, setLoading] = useState(true);',
'  const [search, setSearch] = useState("");',
'  const [count, setCount] = useState(0);',
'  const [importing, setImporting] = useState(false);',
'  const [status, setStatus] = useState("");',
'',
'  const load = async () => {',
'    try {',
'      const rows = await query<SongRow>("SELECT s.*, a.name as artist_name, al.title as album_title, c.code as category_code, c.color as category_color FROM songs s LEFT JOIN artists a ON a.id = s.artist_id LEFT JOIN albums al ON al.id = s.album_id LEFT JOIN categories c ON c.id = s.category_id ORDER BY s.title LIMIT 500");',
'      setSongs(rows);',
'      const r = await queryOne<{ c: number }>("SELECT COUNT(*) as c FROM songs");',
'      setCount(r ? r.c : 0);',
'    } catch (e) { console.error(e); setStatus("Error: " + e); }',
'    setLoading(false);',
'  };',
'',
'  useEffect(() => { load(); }, []);',
'',
'  const handleImport = async () => {',
'    try {',
'      const folder = await open({ directory: true, title: "Select Music Folder" });',
'      if (!folder) return;',
'      setImporting(true); setStatus("Scanning...");',
'      const entries = await readDir(folder as string);',
'      const files: string[] = [];',
'      for (const e of entries) {',
'        if (e.name && isAudio(e.name)) {',
'          const sep = (folder as string).includes("/") ? "/" : "\\\\";',
'          files.push((folder as string) + sep + e.name);',
'        }',
'      }',
'      if (files.length === 0) { setStatus("No audio files found."); setTimeout(() => setStatus(""), 3000); setImporting(false); return; }',
'      let n = 0;',
'      for (const fp of files) {',
'        const ex = await queryOne<{ id: number }>("SELECT id FROM songs WHERE file_path = ?", [fp]);',
'        if (!ex) {',
'          await execute("INSERT INTO songs (title, file_path, file_format, daypart_mask) VALUES (?, ?, ?, ?)", [titleFromFile(fp), fp, fmtExt(fp), 16777215]);',
'          n++;',
'        }',
'        setStatus("Importing... " + n);',
'      }',
'      setStatus("Done! " + n + " imported."); setTimeout(() => setStatus(""), 4000);',
'      setImporting(false); load();',
'    } catch (e) { console.error(e); setStatus("Error: " + e); setImporting(false); }',
'  };',
'',
'  const filtered = search ? songs.filter(s => (s.title||"").toLowerCase().includes(search.toLowerCase()) || (s.artist_name||"").toLowerCase().includes(search.toLowerCase())) : songs;',
'',
'  return (',
'    <div className="space-y-4">',
'      <div className="flex items-center justify-between">',
'        <h1 className="text-xl font-bold">Song Library</h1>',
'        <span className="text-xs text-zinc-500">{count} tracks</span>',
'      </div>',
'      <div className="flex items-center gap-2">',
'        <input type="text" placeholder="Search..." value={search} onChange={e => setSearch(e.target.value)} className="flex-1 px-3 py-2 bg-zinc-800 border border-zinc-700 rounded text-sm text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-blue-500" />',
'        <button onClick={handleImport} disabled={importing} className="px-4 py-2 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 rounded text-sm font-medium text-white">Import Folder</button>',
'      </div>',
'      {status ? <div className="px-3 py-2 bg-blue-900 border border-blue-700 rounded text-sm text-blue-200">{status}</div> : null}',
'      {loading ? <div className="text-sm text-zinc-500">Loading...</div> : filtered.length === 0 ? (',
'        <div className="text-center py-16">',
'          <div className="text-zinc-400 text-lg mb-2">No music yet</div>',
'          <div className="text-zinc-600 text-sm mb-6">Import a folder of audio files to get started.</div>',
'          <button onClick={handleImport} className="px-6 py-3 bg-blue-600 hover:bg-blue-500 rounded-lg text-sm font-medium text-white">Import Music Folder</button>',
'        </div>',
'      ) : (',
'        <div className="bg-zinc-900 rounded-lg border border-zinc-800 overflow-hidden">',
'          <table className="w-full text-sm">',
'            <thead><tr className="text-left text-xs text-zinc-500 uppercase border-b border-zinc-800">',
'              <th className="px-3 py-2 w-8">#</th>',
'              <th className="px-3 py-2">Title</th>',
'              <th className="px-3 py-2">Artist</th>',
'              <th className="px-3 py-2">Format</th>',
'              <th className="px-3 py-2 text-right">Deck</th>',
'            </tr></thead>',
'            <tbody>{filtered.map((s, i) => (',
'              <tr key={s.id} className="border-b border-zinc-800 hover:bg-zinc-800 group">',
'                <td className="px-3 py-2 text-zinc-600 text-xs">{i+1}</td>',
'                <td className="px-3 py-2 text-zinc-100">{s.title}</td>',
'                <td className="px-3 py-2 text-zinc-400">{s.artist_name || "Unknown"}</td>',
'                <td className="px-3 py-2 text-zinc-500 text-xs uppercase">{s.file_path ? fmtExt(s.file_path) : "--"}</td>',
'                <td className="px-3 py-2 text-right">',
'                  <button onClick={() => onLoadA(s)} className="px-2 py-1 bg-blue-700 hover:bg-blue-600 rounded text-[10px] font-bold text-white mr-1">A</button>',
'                  <button onClick={() => onLoadB(s)} className="px-2 py-1 bg-emerald-700 hover:bg-emerald-600 rounded text-[10px] font-bold text-white">B</button>',
'                </td>',
'              </tr>',
'            ))}</tbody>',
'          </table>',
'        </div>',
'      )}',
'    </div>',
'  );',
'}',
'',
'function PH({ title }: { title: string }) {',
'  return <div className="flex flex-col items-center justify-center h-full text-center"><h1 className="text-xl font-bold mb-2">{title}</h1><p className="text-xs text-zinc-600 mt-2">Coming soon</p></div>;',
'}',
'',
'function ClockDisplay() {',
'  const [time, setTime] = useState(new Date().toLocaleTimeString());',
'  useEffect(() => { const id = setInterval(() => setTime(new Date().toLocaleTimeString()), 1000); return () => clearInterval(id); }, []);',
'  return <span className="font-mono text-xs">{time}</span>;',
'}',
].join('\n'), 'utf8');
console.log('  CREATED src/App.tsx');

console.log('\n  All done! Run: npm run tauri:dev');
console.log('  Then: Library > Import Folder > pick music');
console.log('  Then: click A or B to load to deck > Live Assist > Play\n');
