const fs = require('fs');
const code = [
  'import { useState, useEffect } from "react";',
  '',
  'type Panel = "live" | "library" | "clocks" | "logs" | "spots" | "settings";',
  '',
  'export default function App() {',
  '  const [activePanel, setActivePanel] = useState<Panel>("live");',
  '  const [onAir, setOnAir] = useState(false);',
  '',
  '  const onAirClass = onAir',
  '    ? "ml-3 px-3 py-1 rounded text-xs font-bold uppercase tracking-wider bg-red-600 text-white animate-pulse"',
  '    : "ml-3 px-3 py-1 rounded text-xs font-bold uppercase tracking-wider bg-zinc-700 text-zinc-400 hover:bg-zinc-600";',
  '',
  '  return (',
  '    <div className="h-screen flex flex-col bg-zinc-950 text-zinc-100">',
  '      <header className="h-12 flex items-center justify-between px-4 bg-zinc-900 border-b border-zinc-800 shrink-0">',
  '        <div className="flex items-center gap-3">',
  '          <span className="text-lg font-bold tracking-tight">',
  '            <span className="text-blue-400">Open</span>Air',
  '          </span>',
  '          <span className="text-xs text-zinc-500">v0.1.0</span>',
  '        </div>',
  '        <div className="flex items-center gap-2 text-sm text-zinc-400">',
  '          <ClockDisplay />',
  '          <button onClick={() => setOnAir(!onAir)} className={onAirClass}>',
  '            {onAir ? "ON AIR" : "OFF AIR"}',
  '          </button>',
  '        </div>',
  '      </header>',
  '',
  '      <div className="flex flex-1 overflow-hidden">',
  '        <Sidebar activePanel={activePanel} setPanel={setActivePanel} />',
  '        <main className="flex-1 overflow-auto p-6">',
  '          {activePanel === "live" && <LivePanel onAir={onAir} />}',
  '          {activePanel === "library" && <P title="Song Library" d="Scan folders, edit metadata, assign categories." />}',
  '          {activePanel === "clocks" && <P title="Clock Builder" d="Design hourly format clocks with the visual wheel editor." />}',
  '          {activePanel === "logs" && <P title="Log Builder" d="Generate and edit hourly playlists." />}',
  '          {activePanel === "spots" && <P title="Spot Inventory" d="Manage commercials, PSAs, promos, and imaging." />}',
  '          {activePanel === "settings" && <P title="Settings" d="Station name, audio device, scheduling rules, theme." />}',
  '        </main>',
  '      </div>',
  '',
  '      <footer className="h-7 flex items-center justify-between px-4 bg-zinc-900 border-t border-zinc-800 text-[11px] text-zinc-500 shrink-0">',
  '        <span>Ready</span>',
  '        <span>SQLite: connected | Audio: Web Audio API | Mode: Manual</span>',
  '      </footer>',
  '    </div>',
  '  );',
  '}',
  '',
  'function Sidebar({ activePanel, setPanel }: { activePanel: Panel; setPanel: (p: Panel) => void }) {',
  '  const items: { id: Panel; label: string }[] = [',
  '    { id: "live", label: "Live Assist" },',
  '    { id: "library", label: "Library" },',
  '    { id: "clocks", label: "Clocks" },',
  '    { id: "logs", label: "Logs" },',
  '    { id: "spots", label: "Spots" },',
  '    { id: "settings", label: "Settings" },',
  '  ];',
  '',
  '  return (',
  '    <nav className="w-48 bg-zinc-900 border-r border-zinc-800 flex flex-col py-2 shrink-0">',
  '      {items.map((item) => {',
  '        const cls = activePanel === item.id',
  '          ? "flex items-center gap-2 px-4 py-2.5 text-sm text-left bg-zinc-800 text-white border-l-2 border-blue-400"',
  '          : "flex items-center gap-2 px-4 py-2.5 text-sm text-left text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 border-l-2 border-transparent";',
  '        return (',
  '          <button key={item.id} onClick={() => setPanel(item.id)} className={cls}>',
  '            {item.label}',
  '          </button>',
  '        );',
  '      })}',
  '      <div className="mt-auto px-4 py-3 text-[10px] text-zinc-600">',
  '        OpenAir v0.1.0<br />MIT License',
  '      </div>',
  '    </nav>',
  '  );',
  '}',
  '',
  'function LivePanel({ onAir }: { onAir: boolean }) {',
  '  return (',
  '    <div className="space-y-4">',
  '      <h1 className="text-xl font-bold">Live Assist</h1>',
  '      <div className="grid grid-cols-2 gap-4">',
  '        <DeckCard name="Deck A" color="text-blue-400" active={onAir} />',
  '        <DeckCard name="Deck B" color="text-emerald-400" active={false} />',
  '      </div>',
  '      <div className="bg-zinc-900 rounded-lg p-4 border border-zinc-800">',
  '        <h2 className="text-xs font-bold text-zinc-400 uppercase mb-3">Up Next</h2>',
  '        <div className="text-sm text-zinc-500 italic">No log loaded. Import music and generate a log to populate the queue.</div>',
  '      </div>',
  '      <div className="bg-zinc-900 rounded-lg p-4 border border-zinc-800">',
  '        <h2 className="text-xs font-bold text-zinc-400 uppercase mb-3">Cart Wall</h2>',
  '        <div className="grid grid-cols-8 gap-1.5">',
  '          {Array.from({ length: 32 }, (_, i) => (',
  '            <button key={i} className="aspect-square rounded bg-zinc-800 hover:bg-zinc-700 text-[10px] text-zinc-600 flex items-center justify-center">',
  '              {i < 12 ? "F" + (i + 1) : ""}',
  '            </button>',
  '          ))}',
  '        </div>',
  '      </div>',
  '    </div>',
  '  );',
  '}',
  '',
  'function DeckCard({ name, color, active }: { name: string; color: string; active: boolean }) {',
  '  const playClass = active',
  '    ? "px-4 py-1.5 rounded text-xs font-bold flex-1 bg-red-600 text-white"',
  '    : "px-4 py-1.5 rounded text-xs font-bold flex-1 bg-emerald-700 hover:bg-emerald-600 text-white";',
  '',
  '  return (',
  '    <div className="bg-zinc-900 rounded-lg p-4 border border-zinc-800">',
  '      <div className="flex items-center justify-between mb-3">',
  '        <span className={"text-xs font-bold uppercase tracking-wider " + color}>{name}</span>',
  '        <span className="text-[10px] text-zinc-500 uppercase">Idle</span>',
  '      </div>',
  '      <div className="h-20 bg-zinc-800 rounded flex items-center justify-center">',
  '        <span className="text-zinc-600 text-xs">No track loaded</span>',
  '      </div>',
  '      <div className="flex justify-between text-xs font-mono text-zinc-500 mt-3">',
  '        <span>00:00.0</span><span>-00:00.0</span>',
  '      </div>',
  '      <div className="flex items-center gap-2 mt-3">',
  '        <button className="px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 rounded text-xs">Cue</button>',
  '        <button className={playClass}>{active ? "Stop" : "Play"}</button>',
  '        <button className="px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 rounded text-xs">Next</button>',
  '      </div>',
  '      <div className="flex items-center gap-2 text-xs text-zinc-500 mt-3">',
  '        <span>Vol</span>',
  '        <div className="flex-1 h-1.5 bg-zinc-800 rounded-full overflow-hidden">',
  '          <div className="h-full w-4/5 bg-zinc-600 rounded-full"></div>',
  '        </div>',
  '        <span>80%</span>',
  '      </div>',
  '    </div>',
  '  );',
  '}',
  '',
  'function P({ title, d }: { title: string; d: string }) {',
  '  return (',
  '    <div className="flex flex-col items-center justify-center h-full text-center">',
  '      <h1 className="text-xl font-bold mb-2">{title}</h1>',
  '      <p className="text-sm text-zinc-400 max-w-md">{d}</p>',
  '      <p className="text-xs text-zinc-600 mt-4">Coming soon</p>',
  '    </div>',
  '  );',
  '}',
  '',
  'function ClockDisplay() {',
  '  const [time, setTime] = useState(new Date().toLocaleTimeString());',
  '  useEffect(() => {',
  '    const id = setInterval(() => setTime(new Date().toLocaleTimeString()), 1000);',
  '    return () => clearInterval(id);',
  '  }, []);',
  '  return <span className="font-mono text-xs">{time}</span>;',
  '}',
].join('\n');

fs.writeFileSync('src/App.tsx', code, 'utf8');
console.log('App.tsx written!');
