const fs = require('fs');

console.log('\n  Ether — Force Link Clocks to Shows\n');

// 1. Add clock_id to shows table in migrations
let client = fs.readFileSync('src/db/client.ts', 'utf8');
if (!client.includes('shows ADD COLUMN clock_id')) {
  client = client.replace(
    'try { await d.execute("ALTER TABLE categories ADD COLUMN spins_per_hour',
    'try { await d.execute("ALTER TABLE shows ADD COLUMN clock_id INTEGER REFERENCES clocks(id)"); } catch {}\n  try { await d.execute("ALTER TABLE categories ADD COLUMN spins_per_hour'
  );
  fs.writeFileSync('src/db/client.ts', client, 'utf8');
  console.log('  UPDATED client.ts');
}

// 2. Update loggen to check shows
let loggen = fs.readFileSync('src/audio/loggen.ts', 'utf8');
if (!loggen.includes('getClockFromShow')) {
  loggen = loggen.replace(
    'async function getClockForNow(): Promise<number | null> {',
    [
      'async function getClockFromShow(): Promise<number | null> {',
      '  const now = new Date();',
      '  const hour = now.getHours();',
      '  const shows = await query<{ id: number; start_hour: number; end_hour: number; clock_id: number | null }>("SELECT * FROM shows WHERE is_active = 1 AND clock_id IS NOT NULL");',
      '  for (const s of shows) {',
      '    if (s.end_hour > s.start_hour) {',
      '      if (hour >= s.start_hour && hour < s.end_hour) return s.clock_id;',
      '    } else {',
      '      if (hour >= s.start_hour || hour < s.end_hour) return s.clock_id;',
      '    }',
      '  }',
      '  return null;',
      '}',
      '',
      'async function getClockForNow(): Promise<number | null> {',
    ].join('\n')
  );
  loggen = loggen.replace(
    '  const row = await queryOne<{ clock_id: number }>("SELECT clock_id FROM schedule_grid WHERE day_of_week = ? AND hour = ?", [day, hour]);\n  return row ? row.clock_id : null;',
    '  const fromShow = await getClockFromShow();\n  if (fromShow) return fromShow;\n  const row = await queryOne<{ clock_id: number }>("SELECT clock_id FROM schedule_grid WHERE day_of_week = ? AND hour = ?", [day, hour]);\n  return row ? row.clock_id : null;'
  );
  fs.writeFileSync('src/audio/loggen.ts', loggen, 'utf8');
  console.log('  UPDATED loggen.ts');
}

// 3. Rewrite Scheduler.tsx completely
fs.writeFileSync('src/components/Scheduler.tsx', [
'import { useState, useEffect } from "react";',
'import { query, execute, queryOne } from "../db/client";',
'',
'interface Show {',
'  id: number; name: string; start_hour: number; end_hour: number;',
'  days: string; color: string | null; description: string | null;',
'  is_active: number; clock_id: number | null; clock_name: string | null;',
'}',
'',
'interface Category {',
'  id: number; code: string; name: string; color: string | null;',
'  spins_per_hour: number; priority: number; song_count?: number;',
'}',
'',
'interface Clock {',
'  id: number; name: string; show_id: number | null;',
'  description: string | null; color: string | null;',
'}',
'',
'interface ClockSlot {',
'  id: number; clock_id: number; position: number;',
'  slot_type: string; category_id: number | null;',
'  label: string | null; duration_min: number;',
'  category_code?: string; category_color?: string;',
'}',
'',
'const HOURS = Array.from({length: 24}, (_, i) => i);',
'const DAYS = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];',
'const SLOT_TYPES = ["music", "spot_break", "liner", "sweeper", "news", "talkset", "jingle"];',
'',
'function fmtHour(h: number): string {',
'  if (h === 0) return "12 AM";',
'  if (h === 12) return "12 PM";',
'  return h < 12 ? h + " AM" : (h - 12) + " PM";',
'}',
'',
'export default function Scheduler() {',
'  const [tab, setTab] = useState<"shows" | "categories" | "clocks">("shows");',
'  return (',
'    <div className="space-y-3">',
'      <h1 className="text-lg font-bold">Show Scheduler</h1>',
'      <div className="flex gap-1">',
'        {(["shows", "categories", "clocks"] as const).map(t => (',
'          <button key={t} onClick={() => setTab(t)}',
'            className={tab === t ? "px-3 py-1.5 rounded text-xs font-bold bg-blue-600 text-white" : "px-3 py-1.5 rounded text-xs font-bold bg-zinc-800 text-zinc-400 hover:bg-zinc-700"}',
'          >{t === "shows" ? "Shows / Dayparts" : t === "categories" ? "Categories" : "Format Clocks"}</button>',
'        ))}',
'      </div>',
'      {tab === "shows" && <ShowsTab />}',
'      {tab === "categories" && <CategoriesTab />}',
'      {tab === "clocks" && <ClocksTab />}',
'    </div>',
'  );',
'}',
'',
'// ============================================================',
'// SHOWS TAB — with clock dropdown',
'// ============================================================',
'',
'function ShowsTab() {',
'  const [shows, setShows] = useState<Show[]>([]);',
'  const [clocks, setClocks] = useState<Clock[]>([]);',
'  const [editing, setEditing] = useState<Partial<Show> | null>(null);',
'',
'  const load = async () => {',
'    setShows(await query<Show>("SELECT s.*, c.name as clock_name FROM shows s LEFT JOIN clocks c ON c.id = s.clock_id ORDER BY s.start_hour"));',
'    setClocks(await query<Clock>("SELECT * FROM clocks ORDER BY name"));',
'  };',
'  useEffect(() => { load(); }, []);',
'',
'  const save = async () => {',
'    if (!editing || !editing.name) return;',
'    if (editing.id) {',
'      await execute("UPDATE shows SET name=?, start_hour=?, end_hour=?, color=?, description=? WHERE id=?",',
'        [editing.name, editing.start_hour || 0, editing.end_hour || 0, editing.color || null, editing.description || null, editing.id]);',
'    } else {',
'      await execute("INSERT INTO shows (name, start_hour, end_hour, color, description) VALUES (?,?,?,?,?)",',
'        [editing.name, editing.start_hour || 0, editing.end_hour || 0, editing.color || null, editing.description || null]);',
'    }',
'    setEditing(null); load();',
'  };',
'',
'  const assignClock = async (showId: number, clockId: number | null) => {',
'    await execute("UPDATE shows SET clock_id = ? WHERE id = ?", [clockId, showId]);',
'    load();',
'  };',
'',
'  const remove = async (id: number) => { await execute("DELETE FROM shows WHERE id=?", [id]); load(); };',
'',
'  return (',
'    <div className="space-y-3">',
'      <div className="flex items-center justify-between">',
'        <h2 className="text-sm font-bold text-zinc-300">Shows / Dayparts</h2>',
'        <button onClick={() => setEditing({ name: "", start_hour: 0, end_hour: 6, color: "#3b82f6" })} className="px-3 py-1 bg-blue-600 hover:bg-blue-500 rounded text-xs font-bold text-white">+ New Show</button>',
'      </div>',
'',
'      {/* Timeline */}',
'      <div className="bg-zinc-900 rounded-lg border border-zinc-800 p-3">',
'        <div className="text-[10px] text-zinc-500 uppercase mb-1">24-Hour Timeline</div>',
'        <div className="relative h-10 bg-zinc-800 rounded overflow-hidden flex">',
'          {HOURS.map(h => (',
'            <div key={h} className="flex-1 border-r border-zinc-700 relative">',
'              {h % 6 === 0 && <span className="absolute -top-4 left-0 text-[8px] text-zinc-600">{fmtHour(h)}</span>}',
'            </div>',
'          ))}',
'          {shows.map(s => {',
'            const start = s.start_hour;',
'            const end = s.end_hour <= s.start_hour ? s.end_hour + 24 : s.end_hour;',
'            const width = ((end - start) / 24) * 100;',
'            const left = (start / 24) * 100;',
'            return <div key={s.id} className="absolute top-0 h-full flex items-center justify-center text-[9px] font-bold text-white" style={{ left: left + "%", width: Math.min(width, 100 - left) + "%", backgroundColor: s.color || "#444", opacity: 0.8 }}>{s.name}</div>;',
'          })}',
'        </div>',
'      </div>',
'',
'      {/* Edit form */}',
'      {editing && (',
'        <div className="bg-zinc-900 rounded-lg border border-zinc-800 p-3 space-y-2">',
'          <div className="grid grid-cols-4 gap-2">',
'            <input className="col-span-2 px-2 py-1.5 bg-zinc-800 border border-zinc-700 rounded text-xs text-zinc-100" placeholder="Show name" value={editing.name || ""} onChange={e => setEditing({...editing, name: e.target.value})} />',
'            <select className="px-2 py-1.5 bg-zinc-800 border border-zinc-700 rounded text-xs text-zinc-100" value={editing.start_hour || 0} onChange={e => setEditing({...editing, start_hour: parseInt(e.target.value)})}>',
'              {HOURS.map(h => <option key={h} value={h}>{fmtHour(h)}</option>)}',
'            </select>',
'            <select className="px-2 py-1.5 bg-zinc-800 border border-zinc-700 rounded text-xs text-zinc-100" value={editing.end_hour || 0} onChange={e => setEditing({...editing, end_hour: parseInt(e.target.value)})}>',
'              {HOURS.map(h => <option key={h} value={h}>{fmtHour(h)}</option>)}',
'            </select>',
'          </div>',
'          <div className="grid grid-cols-4 gap-2">',
'            <input type="color" className="h-8 w-full bg-zinc-800 border border-zinc-700 rounded" value={editing.color || "#3b82f6"} onChange={e => setEditing({...editing, color: e.target.value})} />',
'            <input className="col-span-3 px-2 py-1.5 bg-zinc-800 border border-zinc-700 rounded text-xs text-zinc-100" placeholder="Description" value={editing.description || ""} onChange={e => setEditing({...editing, description: e.target.value})} />',
'          </div>',
'          <div className="flex gap-2">',
'            <button onClick={save} className="px-3 py-1 bg-blue-600 rounded text-xs font-bold text-white">Save</button>',
'            <button onClick={() => setEditing(null)} className="px-3 py-1 bg-zinc-700 rounded text-xs text-zinc-300">Cancel</button>',
'          </div>',
'        </div>',
'      )}',
'',
'      {/* Show list with clock dropdowns */}',
'      <div className="space-y-1.5">',
'        {shows.map(s => (',
'          <div key={s.id} className="bg-zinc-900 rounded-lg border border-zinc-800 p-3">',
'            <div className="flex items-center justify-between">',
'              <div className="flex items-center gap-3">',
'                <div className="w-4 h-4 rounded-full shrink-0" style={{ backgroundColor: s.color || "#444" }}></div>',
'                <div>',
'                  <div className="text-sm text-zinc-100 font-medium">{s.name}</div>',
'                  <div className="text-[11px] text-zinc-500">{fmtHour(s.start_hour)} - {fmtHour(s.end_hour)}{s.description ? " — " + s.description : ""}</div>',
'                </div>',
'              </div>',
'              <div className="flex items-center gap-2">',
'                <button onClick={() => setEditing(s)} className="px-2 py-1 bg-zinc-700 hover:bg-zinc-600 rounded text-[10px] text-zinc-300">Edit</button>',
'                <button onClick={() => remove(s.id)} className="px-2 py-1 bg-zinc-800 hover:bg-red-900 rounded text-[10px] text-zinc-500 hover:text-red-400">Del</button>',
'              </div>',
'            </div>',
'            <div className="mt-2 flex items-center gap-2">',
'              <span className="text-[11px] text-zinc-500">Format Clock:</span>',
'              <select value={s.clock_id || ""} onChange={e => assignClock(s.id, e.target.value ? parseInt(e.target.value) : null)}',
'                className="flex-1 px-2 py-1.5 bg-zinc-800 border border-zinc-700 rounded text-xs text-zinc-200">',
'                <option value="">-- No clock assigned --</option>',
'                {clocks.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}',
'              </select>',
'              {s.clock_name && <span className="text-[11px] text-emerald-400 font-bold">Active</span>}',
'            </div>',
'          </div>',
'        ))}',
'        {shows.length === 0 && <div className="text-xs text-zinc-600 italic text-center py-4">No shows yet. Click + New Show to create dayparts.</div>}',
'      </div>',
'    </div>',
'  );',
'}',
'',
'// ============================================================',
'// CATEGORIES TAB',
'// ============================================================',
'',
'function CategoriesTab() {',
'  const [cats, setCats] = useState<Category[]>([]);',
'  const [editing, setEditing] = useState<Partial<Category> | null>(null);',
'',
'  const load = async () => {',
'    const rows = await query<Category & { song_count: number }>("SELECT c.*, (SELECT COUNT(*) FROM songs WHERE category_id = c.id) as song_count FROM categories c ORDER BY c.code");',
'    setCats(rows);',
'  };',
'  useEffect(() => { load(); }, []);',
'',
'  const save = async () => {',
'    if (!editing || !editing.code) return;',
'    if (editing.id) {',
'      await execute("UPDATE categories SET code=?, name=?, color=?, spins_per_hour=?, priority=? WHERE id=?",',
'        [editing.code, editing.name || editing.code, editing.color || null, editing.spins_per_hour || 0, editing.priority || 0, editing.id]);',
'    } else {',
'      await execute("INSERT INTO categories (code, name, color, spins_per_hour, priority) VALUES (?,?,?,?,?)",',
'        [editing.code, editing.name || editing.code, editing.color || null, editing.spins_per_hour || 0, editing.priority || 0]);',
'    }',
'    setEditing(null); load();',
'  };',
'',
'  return (',
'    <div className="space-y-3">',
'      <div className="flex items-center justify-between">',
'        <h2 className="text-sm font-bold text-zinc-300">Rotation Categories</h2>',
'        <button onClick={() => setEditing({ code: "", name: "", color: "#3b82f6", spins_per_hour: 0, priority: 0 })} className="px-3 py-1 bg-blue-600 hover:bg-blue-500 rounded text-xs font-bold text-white">+ New Category</button>',
'      </div>',
'      <div className="text-xs text-zinc-500 bg-zinc-900 rounded p-2 border border-zinc-800">',
'        <strong>How rotation works:</strong> A = Power Current (heavy rotation, newest hits). B = Secondary (medium rotation). C = Recurrent (familiar favorites). D = Gold (classic library).',
'      </div>',
'      {editing && (',
'        <div className="bg-zinc-900 rounded-lg border border-zinc-800 p-3 space-y-2">',
'          <div className="grid grid-cols-5 gap-2">',
'            <input className="px-2 py-1.5 bg-zinc-800 border border-zinc-700 rounded text-xs text-zinc-100" placeholder="Code (A)" value={editing.code || ""} onChange={e => setEditing({...editing, code: e.target.value})} />',
'            <input className="col-span-2 px-2 py-1.5 bg-zinc-800 border border-zinc-700 rounded text-xs text-zinc-100" placeholder="Name" value={editing.name || ""} onChange={e => setEditing({...editing, name: e.target.value})} />',
'            <input type="number" className="px-2 py-1.5 bg-zinc-800 border border-zinc-700 rounded text-xs text-zinc-100" placeholder="Spins/hr" value={editing.spins_per_hour || ""} onChange={e => setEditing({...editing, spins_per_hour: parseInt(e.target.value) || 0})} />',
'            <input type="color" className="h-8 w-full bg-zinc-800 border border-zinc-700 rounded" value={editing.color || "#3b82f6"} onChange={e => setEditing({...editing, color: e.target.value})} />',
'          </div>',
'          <div className="flex gap-2">',
'            <button onClick={save} className="px-3 py-1 bg-blue-600 rounded text-xs font-bold text-white">Save</button>',
'            <button onClick={() => setEditing(null)} className="px-3 py-1 bg-zinc-700 rounded text-xs text-zinc-300">Cancel</button>',
'          </div>',
'        </div>',
'      )}',
'      <div className="bg-zinc-900 rounded-lg border border-zinc-800 overflow-hidden">',
'        <table className="w-full text-xs">',
'          <thead><tr className="text-left text-[10px] text-zinc-500 uppercase border-b border-zinc-800">',
'            <th className="px-3 py-2 w-8">Color</th>',
'            <th className="px-3 py-2 w-12">Code</th>',
'            <th className="px-3 py-2">Name</th>',
'            <th className="px-3 py-2 text-right">Songs</th>',
'            <th className="px-3 py-2 text-right">Spins/hr</th>',
'            <th className="px-3 py-2 text-right w-16"></th>',
'          </tr></thead>',
'          <tbody>{cats.map(c => (',
'            <tr key={c.id} className="border-b border-zinc-800 hover:bg-zinc-800">',
'              <td className="px-3 py-2"><div className="w-4 h-4 rounded" style={{ backgroundColor: c.color || "#444" }}></div></td>',
'              <td className="px-3 py-2 font-bold text-zinc-100">{c.code}</td>',
'              <td className="px-3 py-2 text-zinc-300">{c.name}</td>',
'              <td className="px-3 py-2 text-right text-zinc-400">{c.song_count || 0}</td>',
'              <td className="px-3 py-2 text-right text-zinc-400">{c.spins_per_hour || "--"}</td>',
'              <td className="px-3 py-2 text-right"><button onClick={() => setEditing(c)} className="px-2 py-0.5 bg-zinc-700 hover:bg-zinc-600 rounded text-[10px] text-zinc-300">Edit</button></td>',
'            </tr>',
'          ))}</tbody>',
'        </table>',
'      </div>',
'    </div>',
'  );',
'}',
'',
'// ============================================================',
'// CLOCKS TAB',
'// ============================================================',
'',
'function ClocksTab() {',
'  const [clocks, setClocks] = useState<Clock[]>([]);',
'  const [selected, setSelected] = useState<number | null>(null);',
'  const [slots, setSlots] = useState<ClockSlot[]>([]);',
'  const [cats, setCats] = useState<Category[]>([]);',
'  const [newName, setNewName] = useState("");',
'',
'  const loadClocks = async () => {',
'    setClocks(await query<Clock>("SELECT * FROM clocks ORDER BY name"));',
'    setCats(await query<Category>("SELECT * FROM categories ORDER BY code"));',
'  };',
'  const loadSlots = async (clockId: number) => {',
'    setSlots(await query<ClockSlot>("SELECT cs.*, c.code as category_code, c.color as category_color FROM clock_slots cs LEFT JOIN categories c ON c.id = cs.category_id WHERE cs.clock_id = ? ORDER BY cs.position", [clockId]));',
'  };',
'',
'  useEffect(() => { loadClocks(); }, []);',
'  useEffect(() => { if (selected) loadSlots(selected); else setSlots([]); }, [selected]);',
'',
'  const createClock = async () => {',
'    if (!newName.trim()) return;',
'    const r = await execute("INSERT INTO clocks (name) VALUES (?)", [newName.trim()]);',
'    setNewName(""); loadClocks(); setSelected(r.lastInsertId);',
'  };',
'',
'  const addSlot = async (type: string, catId: number | null) => {',
'    if (!selected) return;',
'    const pos = slots.length;',
'    await execute("INSERT INTO clock_slots (clock_id, position, slot_type, category_id) VALUES (?,?,?,?)", [selected, pos, type, catId]);',
'    loadSlots(selected);',
'  };',
'',
'  const removeSlot = async (id: number) => {',
'    await execute("DELETE FROM clock_slots WHERE id=?", [id]);',
'    if (selected) loadSlots(selected);',
'  };',
'',
'  const moveSlot = async (idx: number, dir: -1 | 1) => {',
'    const target = idx + dir;',
'    if (target < 0 || target >= slots.length) return;',
'    const a = slots[idx];',
'    const b = slots[target];',
'    await execute("UPDATE clock_slots SET position = ? WHERE id = ?", [target, a.id]);',
'    await execute("UPDATE clock_slots SET position = ? WHERE id = ?", [idx, b.id]);',
'    if (selected) loadSlots(selected);',
'  };',
'',
'  const totalMin = slots.reduce((sum, s) => sum + s.duration_min, 0);',
'',
'  return (',
'    <div className="space-y-3">',
'      <div className="flex items-center justify-between">',
'        <h2 className="text-sm font-bold text-zinc-300">Format Clocks</h2>',
'        <div className="flex gap-1">',
'          <input className="px-2 py-1 bg-zinc-800 border border-zinc-700 rounded text-xs text-zinc-100 w-40" placeholder="New clock name" value={newName} onChange={e => setNewName(e.target.value)} />',
'          <button onClick={createClock} className="px-3 py-1 bg-blue-600 hover:bg-blue-500 rounded text-xs font-bold text-white">Create</button>',
'        </div>',
'      </div>',
'      <div className="grid grid-cols-4 gap-3">',
'        <div className="space-y-1">',
'          {clocks.map(c => (',
'            <button key={c.id} onClick={() => setSelected(c.id)} className={selected === c.id ? "w-full px-3 py-2 text-left bg-blue-900 border border-blue-700 rounded text-xs text-white font-medium" : "w-full px-3 py-2 text-left bg-zinc-900 border border-zinc-800 rounded text-xs text-zinc-300 hover:bg-zinc-800"}>{c.name}</button>',
'          ))}',
'          {clocks.length === 0 && <div className="text-xs text-zinc-600 italic p-2">No clocks yet.</div>}',
'        </div>',
'        <div className="col-span-3">',
'          {selected ? (',
'            <div className="space-y-2">',
'              <div className="flex items-center justify-between">',
'                <span className="text-xs text-zinc-400">{totalMin} min / 60 min hour</span>',
'                <div className="flex gap-1 flex-wrap">',
'                  {cats.map(c => (',
'                    <button key={c.id} onClick={() => addSlot("music", c.id)} className="px-2 py-0.5 rounded text-[9px] font-bold text-white" style={{ backgroundColor: c.color || "#444" }}>+ {c.code}</button>',
'                  ))}',
'                  <button onClick={() => addSlot("spot_break", null)} className="px-2 py-0.5 bg-zinc-700 rounded text-[9px] font-bold text-zinc-300">+ Break</button>',
'                  <button onClick={() => addSlot("liner", null)} className="px-2 py-0.5 bg-zinc-700 rounded text-[9px] font-bold text-zinc-300">+ Liner</button>',
'                  <button onClick={() => addSlot("sweeper", null)} className="px-2 py-0.5 bg-zinc-700 rounded text-[9px] font-bold text-zinc-300">+ Sweep</button>',
'                </div>',
'              </div>',
'              <div className="flex gap-3">',
'                <div className="flex-1">',
'                  <div className="flex flex-wrap gap-1">',
'                    {slots.map((s, i) => (',
'                      <div key={s.id} className="flex items-center gap-0.5 px-1.5 py-1 rounded text-[10px] font-bold text-white group"',
'                        style={{ backgroundColor: s.category_color || (s.slot_type === "spot_break" ? "#991b1b" : s.slot_type === "liner" ? "#854d0e" : "#374151") }}>',
'                        <span className="opacity-60 w-4">{i + 1}</span>',
'                        <span className="flex-1">{s.category_code || s.slot_type}</span>',
'                        <button onClick={() => moveSlot(i, -1)} className="opacity-0 group-hover:opacity-80 text-[9px] px-0.5">&#9650;</button>',
'                        <button onClick={() => moveSlot(i, 1)} className="opacity-0 group-hover:opacity-80 text-[9px] px-0.5">&#9660;</button>',
'                        <button onClick={() => removeSlot(s.id)} className="opacity-0 group-hover:opacity-80 text-[9px] px-0.5 text-red-300">&#10005;</button>',
'                      </div>',
'                    ))}',
'                  </div>',
'                  {slots.length > 0 && <div className="text-[9px] text-zinc-600 mt-1">Hover: arrows to move, X to delete</div>}',
'                </div>',
'                <div className="w-32 h-32 shrink-0">',
'                  <ClockWheel slots={slots} />',
'                </div>',
'              </div>',
'            </div>',
'          ) : (',
'            <div className="text-xs text-zinc-600 italic p-4 text-center">Select a clock or create a new one.</div>',
'          )}',
'        </div>',
'      </div>',
'    </div>',
'  );',
'}',
'',
'function ClockWheel({ slots }: { slots: ClockSlot[] }) {',
'  const total = slots.reduce((s, sl) => s + sl.duration_min, 0) || 60;',
'  let angle = -90;',
'  const arcs = slots.map(s => {',
'    const sweep = (s.duration_min / total) * 360;',
'    const startAngle = angle;',
'    angle += sweep;',
'    const rad1 = (startAngle * Math.PI) / 180;',
'    const rad2 = ((startAngle + sweep) * Math.PI) / 180;',
'    const r = 55; const cx = 64; const cy = 64;',
'    const x1 = cx + r * Math.cos(rad1); const y1 = cy + r * Math.sin(rad1);',
'    const x2 = cx + r * Math.cos(rad2); const y2 = cy + r * Math.sin(rad2);',
'    const large = sweep > 180 ? 1 : 0;',
'    const color = s.category_color || (s.slot_type === "spot_break" ? "#991b1b" : "#374151");',
'    return { d: "M " + cx + " " + cy + " L " + x1 + " " + y1 + " A " + r + " " + r + " 0 " + large + " 1 " + x2 + " " + y2 + " Z", color, id: s.id };',
'  });',
'  return (',
'    <svg viewBox="0 0 128 128" className="w-full h-full">',
'      <circle cx="64" cy="64" r="58" fill="none" stroke="#27272a" strokeWidth="1" />',
'      {arcs.map(a => <path key={a.id} d={a.d} fill={a.color} stroke="#09090b" strokeWidth="0.5" opacity="0.85" />)}',
'      <circle cx="64" cy="64" r="12" fill="#18181b" />',
'      <text x="64" y="67" textAnchor="middle" fill="#71717a" fontSize="8">{total}m</text>',
'    </svg>',
'  );',
'}',
].join('\n'), 'utf8');
console.log('  REWROTE src/components/Scheduler.tsx');

console.log('\n  Done! App should hot-reload.');
console.log('  Each show now has a Format Clock dropdown underneath it.');
console.log('  Pick a clock and GEN LOG will use it during those hours.\n');
console.log('  Push:');
console.log('    git add -A');
console.log('    git commit -m "v0.5.2 clocks linked to dayparts via dropdown"');
console.log('    git push\n');
