
AI Overview
Code implements an OpenAir audio application with SQLite database migrations and library import functionality.

const fs = require('fs');
const path = require('path');

// ============================================================
// 1. src/db/client.ts — Database wrapper + migrations
// ============================================================

fs.mkdirSync('src/db', { recursive: true });

fs.writeFileSync('src/db/client.ts', [
  'import Database from "@tauri-apps/plugin-sql";',
  '',
  'let db: Database | null = null;',
  '',
  'export async function getDb(): Promise<Database> {',
  '  if (!db) { db = await Database.load("sqlite:openair.db"); }',
  '  return db;',
  '}',
  '',
  'export async function query<T>(sql: string, params: unknown[] = []): Promise<T[]> {',
  '  const d = await getDb();',
  '  return (await d.select(sql, params)) as T[];',
  '}',
  '',
  'export async function queryOne<T>(sql: string, params: unknown[] = []): Promise<T | null> {',
  '  const rows = await query<T>(sql, params);',
  '  return rows.length > 0 ? rows[0] : null;',
  '}',
  '',
  'export async function execute(sql: string, params: unknown[] = []): Promise<{ rowsAffected: number; lastInsertId: number }> {',
  '  const d = await getDb();',
  '  const r = await d.execute(sql, params);',
  '  return { rowsAffected: r.rowsAffected, lastInsertId: r.lastInsertId };',
  '}',
  '',
  'export async function runMigrations(): Promise<void> {',
  '  const d = await getDb();',
  '  await d.execute("CREATE TABLE IF NOT EXISTS artists (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, sort_name TEXT, created_at INTEGER NOT NULL DEFAULT (unixepoch()))");',
  '  await d.execute("CREATE TABLE IF NOT EXISTS albums (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, artist_id INTEGER, year INTEGER, created_at INTEGER NOT NULL DEFAULT (unixepoch()))");',
  '  await d.execute("CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, color TEXT, description TEXT, created_at INTEGER NOT NULL DEFAULT (unixepoch()))");',
  '  await d.execute("CREATE TABLE IF NOT EXISTS songs (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, artist_id INTEGER, album_id INTEGER, file_path TEXT, file_format TEXT, file_size_bytes INTEGER, duration_ms INTEGER NOT NULL DEFAULT 0, genre TEXT, era TEXT, category_id INTEGER, rotation_status TEXT NOT NULL DEFAULT \'active\', daypart_mask INTEGER NOT NULL DEFAULT 16777215, gender TEXT NOT NULL DEFAULT \'unknown\', tags TEXT NOT NULL DEFAULT \'[]\', notes TEXT, created_at INTEGER NOT NULL DEFAULT (unixepoch()), updated_at INTEGER NOT NULL DEFAULT (unixepoch()))");',
  '  // Seed categories',
  '  const r = await d.select("SELECT COUNT(*) as c FROM categories");',
  '  if ((r as any)[0].c === 0) {',
  '    await d.execute("INSERT INTO categories (code,name,color) VALUES (\'A\',\'Power Current\',\'#ef4444\')");',
  '    await d.execute("INSERT INTO categories (code,name,color) VALUES (\'B\',\'Secondary\',\'#f59e0b\')");',
  '    await d.execute("INSERT INTO categories (code,name,color) VALUES (\'C\',\'Recurrent\',\'#22c55e\')");',
  '    await d.execute("INSERT INTO categories (code,name,color) VALUES (\'D\',\'Gold\',\'#3b82f6\')");',
  '  }',
  '  console.log("DB ready");',
  '}',
].join('\n'), 'utf8');
console.log('CREATED  src/db/client.ts');

// ============================================================
// 2. Fix index.html
// ============================================================

fs.writeFileSync('index.html', [
  '<!DOCTYPE html>',
  '<html lang="en" class="dark">',
  '<head><meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0"/><title>Ether</title></head>',
  '<body class="bg-zinc-950 text-zinc-100 overflow-hidden">',
  '<div id="root"></div>',
  '<script type="module" src="/src/main.tsx"></scr' + 'ipt>',
  '</body></html>',
].join('\n'), 'utf8');
console.log('REPLACED index.html');

// ============================================================
// 3. main.tsx with migrations
// ============================================================

fs.writeFileSync('src/main.tsx', [
  'import React from "react";',
  'import ReactDOM from "react-dom/client";',
  'import App from "./App";',
  'import "./index.css";',
  'import { runMigrations } from "./db/client";',
  '',
  'runMigrations().catch(console.error);',
  '',
  'ReactDOM.createRoot(document.getElementById("root")!).render(',
  '  <React.StrictMode><App /></React.StrictMode>,',
  ');',
].join('\n'), 'utf8');
console.log('REPLACED src/main.tsx');

// ============================================================
// 4. App.tsx — Full app with music import
// ============================================================

fs.writeFileSync('src/App.tsx', [
'import { useState, useEffect, useRef } from "react";',
'import { query, execute, queryOne } from "./db/client";',
'import { open } from "@tauri-apps/plugin-dialog";',
'import { readDir } from "@tauri-apps/plugin-fs";',
'',
'type Panel = "live" | "library" | "clocks" | "logs" | "spots" | "settings";',
'',
'interface SongRow {',
'  id: number; title: string; file_path: string | null;',
'  artist_name: string | null; album_title: string | null;',
'  genre: string | null; duration_ms: number;',
'  category_code: string | null; category_color: string | null;',
'}',
'',
'const AUDIO_EXTS = [".mp3", ".flac", ".ogg", ".wav", ".m4a", ".aac", ".wma", ".aiff"];',
'',
'function isAudioFile(name: string): boolean {',
'  const lower = name.toLowerCase();',
'  return AUDIO_EXTS.some(ext => lower.endsWith(ext));',
'}',
'',
'function titleFromFilename(filePath: string): string {',
'  const name = filePath.split(/[\\\\/]/).pop() || filePath;',
'  return name.replace(/\\.[^.]+$/, "").replace(/[_-]/g, " ").replace(/^\\d+\\.?\\s*/, "");',
'}',
'',
'function formatFromPath(p: string): string {',
'  const ext = (p.split(".").pop() || "").toLowerCase();',
'  return ext;',
'}',
'',
'// ============================================================',
'// APP',
'// ============================================================',
'',
'export default function App() {',
'  const [panel, setPanel] = useState<Panel>("live");',
'  const [onAir, setOnAir] = useState(false);',
'  const cls = onAir',
'    ? "ml-3 px-3 py-1 rounded text-xs font-bold uppercase tracking-wider bg-red-600 text-white animate-pulse"',
'    : "ml-3 px-3 py-1 rounded text-xs font-bold uppercase tracking-wider bg-zinc-700 text-zinc-400 hover:bg-zinc-600";',
'  return (',
'    <div className="h-screen flex flex-col bg-zinc-950 text-zinc-100">',
'      <header className="h-12 flex items-center justify-between px-4 bg-zinc-900 border-b border-zinc-800 shrink-0">',
'        <div className="flex items-center gap-3">',
'          <span className="text-lg font-bold tracking-tight"><span className="text-blue-400">Eth</span>er</span>',
'          <span className="text-xs text-zinc-500">v0.1.0</span>',
'        </div>',
'        <div className="flex items-center gap-2 text-sm text-zinc-400">',
'          <ClockDisplay />',
'          <button onClick={() => setOnAir(!onAir)} className={cls}>{onAir ? "ON AIR" : "OFF AIR"}</button>',
'        </div>',
'      </header>',
'      <div className="flex flex-1 overflow-hidden">',
'        <Nav active={panel} set={setPanel} />',
'        <main className="flex-1 overflow-auto p-6">',
'          {panel === "live" && <LivePanel onAir={onAir} />}',
'          {panel === "library" && <LibraryPanel />}',
'          {panel === "clocks" && <Placeholder title="Clock Builder" />}',
'          {panel === "logs" && <Placeholder title="Log Builder" />}',
'          {panel === "spots" && <Placeholder title="Spot Inventory" />}',
'          {panel === "settings" && <Placeholder title="Settings" />}',
'        </main>',
'      </div>',
'      <footer className="h-7 flex items-center justify-between px-4 bg-zinc-900 border-t border-zinc-800 text-[11px] text-zinc-500 shrink-0">',
'        <span>Ready</span>',
'        <span>SQLite: connected | Audio: Web Audio API | Mode: Manual</span>',
'      </footer>',
'    </div>',
'  );',
'}',
'',
'// ============================================================',
'// NAV',
'// ============================================================',
'',
'function Nav({ active, set }: { active: Panel; set: (p: Panel) => void }) {',
'  const items: { id: Panel; label: string }[] = [',
'    { id: "live", label: "Live Assist" }, { id: "library", label: "Library" },',
'    { id: "clocks", label: "Clocks" }, { id: "logs", label: "Logs" },',
'    { id: "spots", label: "Spots" }, { id: "settings", label: "Settings" },',
'  ];',
'  return (',
'    <nav className="w-48 bg-zinc-900 border-r border-zinc-800 flex flex-col py-2 shrink-0">',
'      {items.map(i => (',
'        <button key={i.id} onClick={() => set(i.id)}',
'          className={active === i.id',
'            ? "px-4 py-2.5 text-sm text-left bg-zinc-800 text-white border-l-2 border-blue-400"',
'            : "px-4 py-2.5 text-sm text-left text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 border-l-2 border-transparent"',
'          }>{i.label}</button>',
'      ))}',
'      <div className="mt-auto px-4 py-3 text-[10px] text-zinc-600">Ether v0.1.0<br/>Free forever</div>',
'    </nav>',
'  );',
'}',
'',
'// ============================================================',
'// LIBRARY PANEL — with folder import',
'// ============================================================',
'',
'function LibraryPanel() {',
'  const [songs, setSongs] = useState<SongRow[]>([]);',
'  const [loading, setLoading] = useState(true);',
'  const [search, setSearch] = useState("");',
'  const [count, setCount] = useState(0);',
'  const [importing, setImporting] = useState(false);',
'  const [importStatus, setImportStatus] = useState("");',
'',
'  const load = async () => {',
'    try {',
'      const rows = await query<SongRow>(',
'        "SELECT s.*, a.name as artist_name, al.title as album_title, c.code as category_code, c.color as category_color FROM songs s LEFT JOIN artists a ON a.id = s.artist_id LEFT JOIN albums al ON al.id = s.album_id LEFT JOIN categories c ON c.id = s.category_id ORDER BY s.title LIMIT 500"',
'      );',
'      setSongs(rows);',
'      const r = await queryOne<{ c: number }>("SELECT COUNT(*) as c FROM songs");',
'      setCount(r ? r.c : 0);',
'    } catch (e) { console.error(e); }',
'    setLoading(false);',
'  };',
'',
'  useEffect(() => { load(); }, []);',
'',
'  const handleImportFolder = async () => {',
'    try {',
'      const folder = await open({ directory: true, title: "Select Music Folder" });',
'      if (!folder) return;',
'      setImporting(true);',
'      setImportStatus("Scanning folder...");',
'',
'      const entries = await readDir(folder as string);',
'      const audioFiles: string[] = [];',
'',
'      for (const entry of entries) {',
'        if (entry.name && isAudioFile(entry.name)) {',
'          const sep = (folder as string).includes("/") ? "/" : "\\\\";',
'          audioFiles.push((folder as string) + sep + entry.name);',
'        }',
'      }',
'',
'      if (audioFiles.length === 0) {',
'        setImportStatus("No audio files found in that folder.");',
'        setTimeout(() => setImportStatus(""), 3000);',
'        setImporting(false);',
'        return;',
'      }',
'',
'      let imported = 0;',
'      let skipped = 0;',
'',
'      for (const filePath of audioFiles) {',
'        const existing = await queryOne<{ id: number }>("SELECT id FROM songs WHERE file_path = ?", [filePath]);',
'        if (existing) { skipped++; continue; }',
'',
'        const title = titleFromFilename(filePath);',
'        const format = formatFromPath(filePath);',
'',
'        await execute(',
'          "INSERT INTO songs (title, file_path, file_format, daypart_mask) VALUES (?, ?, ?, ?)",',
'          [title, filePath, format, 16777215]',
'        );',
'        imported++;',
'        setImportStatus("Importing... " + imported + " of " + audioFiles.length);',
'      }',
'',
'      setImportStatus("Done! " + imported + " imported, " + skipped + " already in library.");',
'      setTimeout(() => setImportStatus(""), 5000);',
'      setImporting(false);',
'      load();',
'    } catch (e) {',
'      console.error("Import error:", e);',
'      setImportStatus("Error: " + String(e));',
'      setImporting(false);',
'    }',
'  };',
'',
'  const handleImportFiles = async () => {',
'    try {',
'      const files = await open({',
'        multiple: true,',
'        title: "Select Audio Files",',
'        filters: [{ name: "Audio", extensions: ["mp3", "flac", "ogg", "wav", "m4a", "aac", "wma", "aiff"] }]',
'      });',
'      if (!files || (Array.isArray(files) && files.length === 0)) return;',
'      setImporting(true);',
'',
'      const fileList = Array.isArray(files) ? files : [files];',
'      let imported = 0;',
'',
'      for (const filePath of fileList) {',
'        const existing = await queryOne<{ id: number }>("SELECT id FROM songs WHERE file_path = ?", [filePath]);',
'        if (existing) continue;',
'',
'        const title = titleFromFilename(filePath);',
'        const format = formatFromPath(filePath);',
'',
'        await execute(',
'          "INSERT INTO songs (title, file_path, file_format, daypart_mask) VALUES (?, ?, ?, ?)",',
'          [title, filePath, format, 16777215]',
'        );',
'        imported++;',
'      }',
'',
'      setImportStatus("Imported " + imported + " files.");',
'      setTimeout(() => setImportStatus(""), 4000);',
'      setImporting(false);',
'      load();',
'    } catch (e) {',
'      console.error(e);',
'      setImportStatus("Error: " + String(e));',
'      setImporting(false);',
'    }',
'  };',
'',
'  const handleDelete = async (id: number) => {',
'    await execute("DELETE FROM songs WHERE id = ?", [id]);',
'    load();',
'  };',
'',
'  const filtered = search',
'    ? songs.filter(s => (s.title || "").toLowerCase().includes(search.toLowerCase()) || (s.artist_name || "").toLowerCase().includes(search.toLowerCase()))',
'    : songs;',
'',
'  const fmt = (ms: number) => {',
'    if (!ms) return "--:--";',
'    const s = Math.floor(ms / 1000);',
'    return Math.floor(s / 60) + ":" + String(s % 60).padStart(2, "0");',
'  };',
'',
'  return (',
'    <div className="space-y-4">',
'      <div className="flex items-center justify-between">',
'        <h1 className="text-xl font-bold">Song Library</h1>',
'        <span className="text-xs text-zinc-500">{count} tracks</span>',
'      </div>',
'',
'      <div className="flex items-center gap-2">',
'        <input type="text" placeholder="Search by title or artist..."',
'          value={search} onChange={e => setSearch(e.target.value)}',
'          className="flex-1 px-3 py-2 bg-zinc-800 border border-zinc-700 rounded text-sm text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-blue-500" />',
'        <button onClick={handleImportFolder} disabled={importing}',
'          className="px-4 py-2 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 rounded text-sm font-medium text-white">',
'          Import Folder',
'        </button>',
'        <button onClick={handleImportFiles} disabled={importing}',
'          className="px-4 py-2 bg-zinc-700 hover:bg-zinc-600 disabled:opacity-50 rounded text-sm font-medium text-zinc-200">',
'          Import Files',
'        </button>',
'      </div>',
'',
'      {importStatus && (',
'        <div className="px-3 py-2 bg-blue-900 border border-blue-700 rounded text-sm text-blue-200">',
'          {importStatus}',
'        </div>',
'      )}',
'',
'      {loading ? <div className="text-sm text-zinc-500">Loading...</div> : filtered.length === 0 ? (',
'        <div className="text-center py-16">',
'          <div className="text-zinc-400 text-lg mb-2">No music yet</div>',
'          <div className="text-zinc-600 text-sm mb-6">Import a folder of audio files to get started.</div>',
'          <button onClick={handleImportFolder}',
'            className="px-6 py-3 bg-blue-600 hover:bg-blue-500 rounded-lg text-sm font-medium text-white">',
'            Import Music Folder',
'          </button>',
'        </div>',
'      ) : (',
'        <div className="bg-zinc-900 rounded-lg border border-zinc-800 overflow-hidden">',
'          <table className="w-full text-sm">',
'            <thead><tr className="text-left text-xs text-zinc-500 uppercase border-b border-zinc-800">',
'              <th className="px-4 py-2 w-8"></th>',
'              <th className="px-4 py-2">Title</th>',
'              <th className="px-4 py-2">Artist</th>',
'              <th className="px-4 py-2">Format</th>',
'              <th className="px-4 py-2 text-right">Duration</th>',
'              <th className="px-4 py-2 w-8"></th>',
'            </tr></thead>',
'            <tbody>{filtered.map((s, i) => (',
'              <tr key={s.id} className="border-b border-zinc-800 hover:bg-zinc-800 cursor-pointer group">',
'                <td className="px-4 py-2 text-zinc-600 text-xs">{i + 1}</td>',
'                <td className="px-4 py-2 text-zinc-100">{s.title}</td>',
'                <td className="px-4 py-2 text-zinc-400">{s.artist_name || "Unknown"}</td>',
'                <td className="px-4 py-2 text-zinc-500 text-xs uppercase">{s.file_path ? formatFromPath(s.file_path) : "--"}</td>',
'                <td className="px-4 py-2 text-right text-zinc-500 font-mono text-xs">{fmt(s.duration_ms)}</td>',
'                <td className="px-4 py-2">',
'                  <button onClick={() => handleDelete(s.id)} className="text-zinc-700 hover:text-red-400 opacity-0 group-hover:opacity-100 text-xs">X</button>',
'                </td>',
'              </tr>',
'            ))}</tbody>',
'          </table>',
'        </div>',
'      )}',
'    </div>',
'  );',
'}',
'',
'// ============================================================',
'// LIVE PANEL',
'// ============================================================',
'',
'function LivePanel({ onAir }: { onAir: boolean }) {',
'  return (',
'    <div className="space-y-4">',
'      <h1 className="text-xl font-bold">Live Assist</h1>',
'      <div className="grid grid-cols-2 gap-4">',
'        <DeckCard name="Deck A" color="text-blue-400" active={onAir} />',
'        <DeckCard name="Deck B" color="text-emerald-400" active={false} />',
'      </div>',
'      <div className="bg-zinc-900 rounded-lg p-4 border border-zinc-800">',
'        <h2 className="text-xs font-bold text-zinc-400 uppercase mb-3">Up Next</h2>',
'        <div className="text-sm text-zinc-500 italic">No log loaded.</div>',
'      </div>',
'      <div className="bg-zinc-900 rounded-lg p-4 border border-zinc-800">',
'        <h2 className="text-xs font-bold text-zinc-400 uppercase mb-3">Cart Wall</h2>',
'        <div className="grid grid-cols-8 gap-1.5">',
'          {Array.from({ length: 32 }, (_, i) => (',
'            <button key={i} className="aspect-square rounded bg-zinc-800 hover:bg-zinc-700 text-[10px] text-zinc-600 flex items-center justify-center">{i < 12 ? "F" + (i + 1) : ""}</button>',
'          ))}',
'        </div>',
'      </div>',
'    </div>',
'  );',
'}',
'',
'function DeckCard({ name, color, active }: { name: string; color: string; active: boolean }) {',
'  const pc = active ? "px-4 py-1.5 rounded text-xs font-bold flex-1 bg-red-600 text-white" : "px-4 py-1.5 rounded text-xs font-bold flex-1 bg-emerald-700 hover:bg-emerald-600 text-white";',
'  return (',
'    <div className="bg-zinc-900 rounded-lg p-4 border border-zinc-800">',
'      <div className="flex items-center justify-between mb-3">',
'        <span className={"text-xs font-bold uppercase tracking-wider " + color}>{name}</span>',
'        <span className="text-[10px] text-zinc-500 uppercase">Idle</span>',
'      </div>',
'      <div className="h-20 bg-zinc-800 rounded flex items-center justify-center"><span className="text-zinc-600 text-xs">No track loaded</span></div>',
'      <div className="flex justify-between text-xs font-mono text-zinc-500 mt-3"><span>00:00.0</span><span>-00:00.0</span></div>',
'      <div className="flex items-center gap-2 mt-3">',
'        <button className="px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 rounded text-xs">Cue</button>',
'        <button className={pc}>{active ? "Stop" : "Play"}</button>',
'        <button className="px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 rounded text-xs">Next</button>',
'      </div>',
'      <div className="flex items-center gap-2 text-xs text-zinc-500 mt-3"><span>Vol</span><div className="flex-1 h-1.5 bg-zinc-800 rounded-full overflow-hidden"><div className="h-full w-4/5 bg-zinc-600 rounded-full"></div></div><span>80%</span></div>',
'    </div>',
'  );',
'}',
'',
'function Placeholder({ title }: { title: string }) {',
'  return <div className="flex flex-col items-center justify-center h-full text-center"><h1 className="text-xl font-bold mb-2">{title}</h1><p className="text-xs text-zinc-600 mt-2">Coming soon</p></div>;',
'}',
'',
'function ClockDisplay() {',
'  const [time, setTime] = useState(new Date().toLocaleTimeString());',
'  useEffect(() => { const id = setInterval(() => setTime(new Date().toLocaleTimeString()), 1000); return () => clearInterval(id); }, []);',
'  return <span className="font-mono text-xs">{time}</span>;',
'}',
].join('\n'), 'utf8');
console.log('REPLACED src/App.tsx (with Import Folder + Import Files)');

console.log('\nDone! Run: npm run tauri:dev');
console.log('Click Library > Import Folder > pick a folder with MP3s');
