const fs = require('fs');

console.log('\n  Ether — Artist/Song Separation Rules\n');

// ============================================================
// 1. Add separation rules table + settings
// ============================================================

let client = fs.readFileSync('src/db/client.ts', 'utf8');
if (!client.includes('separation_rules')) {
  client = client.replace(
    '  console.log("DB ready");',
    [
      '  await d.execute("CREATE TABLE IF NOT EXISTS separation_rules (id INTEGER PRIMARY KEY AUTOINCREMENT, rule_type TEXT NOT NULL, scope TEXT NOT NULL DEFAULT \'global\', value INTEGER NOT NULL, is_hard INTEGER NOT NULL DEFAULT 1, is_active INTEGER NOT NULL DEFAULT 1, description TEXT)");',
      '',
      '  // Seed default rules',
      '  const ruleCount = await d.select("SELECT COUNT(*) as c FROM separation_rules");',
      '  if ((ruleCount as any)[0].c === 0) {',
      '    await d.execute("INSERT INTO separation_rules (rule_type, scope, value, is_hard, description) VALUES (\'artist_separation_min\', \'global\', 60, 1, \'Minimum minutes before same artist can play again\')");',
      '    await d.execute("INSERT INTO separation_rules (rule_type, scope, value, is_hard, description) VALUES (\'song_separation_min\', \'global\', 240, 1, \'Minimum minutes before same song can play again\')");',
      '    await d.execute("INSERT INTO separation_rules (rule_type, scope, value, is_hard, description) VALUES (\'title_separation_min\', \'global\', 120, 1, \'Minimum minutes before same title (diff artist) can play again\')");',
      '    await d.execute("INSERT INTO separation_rules (rule_type, scope, value, is_hard, description) VALUES (\'max_same_gender\', \'global\', 3, 0, \'Max consecutive songs of same gender (soft rule)\')");',
      '    await d.execute("INSERT INTO separation_rules (rule_type, scope, value, is_hard, description) VALUES (\'max_same_category\', \'global\', 3, 0, \'Max consecutive songs from same category (soft rule)\')");',
      '  }',
      '',
      '  console.log("DB ready");',
    ].join('\n')
  );
  fs.writeFileSync('src/db/client.ts', client, 'utf8');
  console.log('  UPDATED client.ts (separation_rules table)');
}

// ============================================================
// 2. Rewrite loggen.ts with smart scheduling
// ============================================================

fs.writeFileSync('src/audio/loggen.ts', [
'import { query, queryOne, execute } from "../db/client";',
'import { engine } from "./engine";',
'',
'interface SlotDef {',
'  id: number; position: number; slot_type: string;',
'  category_id: number | null; duration_min: number;',
'}',
'',
'interface SongCandidate {',
'  id: number; title: string; file_path: string;',
'  artist_id: number | null; artist_name: string | null;',
'  category_id: number | null; gender: string;',
'  last_played_at: number | null; spins_total: number;',
'}',
'',
'interface SepRule {',
'  rule_type: string; value: number; is_hard: number;',
'}',
'',
'interface RecentPlay {',
'  song_id: number; title: string; artist: string | null;',
'  artist_id: number | null; category_id: number | null;',
'  gender: string | null; played_at: number;',
'}',
'',
'// ============================================================',
'// SCORING ENGINE — rates each candidate',
'// ============================================================',
'',
'async function getRules(): Promise<SepRule[]> {',
'  return query<SepRule>("SELECT rule_type, value, is_hard FROM separation_rules WHERE is_active = 1");',
'}',
'',
'async function getRecentPlays(minutes: number): Promise<RecentPlay[]> {',
'  const cutoff = Math.floor(Date.now() / 1000) - (minutes * 60);',
'  return query<RecentPlay>(',
'    "SELECT pl.title, pl.artist, s.artist_id, s.category_id, s.gender, pl.played_at, s.id as song_id " +',
'    "FROM play_log pl LEFT JOIN songs s ON s.title = pl.title " +',
'    "WHERE pl.played_at > ? ORDER BY pl.played_at DESC", [cutoff]',
'  );',
'}',
'',
'function scoreSong(song: SongCandidate, recent: RecentPlay[], rules: SepRule[], usedInHour: number[]): { score: number; violations: string[] } {',
'  let score = 1000;',
'  const violations: string[] = [];',
'  const nowSec = Math.floor(Date.now() / 1000);',
'',
'  // Skip if already used this hour',
'  if (usedInHour.includes(song.id)) return { score: -99999, violations: ["already scheduled this hour"] };',
'',
'  for (const rule of rules) {',
'    const penalty = rule.is_hard ? 10000 : 100;',
'',
'    if (rule.rule_type === "song_separation_min") {',
'      const lastPlay = recent.find(r => r.song_id === song.id);',
'      if (lastPlay) {',
'        const minsSince = (nowSec - lastPlay.played_at) / 60;',
'        if (minsSince < rule.value) {',
'          score -= penalty;',
'          violations.push("song played " + Math.floor(minsSince) + "m ago (min " + rule.value + ")");',
'        }',
'      }',
'    }',
'',
'    if (rule.rule_type === "artist_separation_min" && song.artist_id) {',
'      const lastArtist = recent.find(r => r.artist_id === song.artist_id);',
'      if (lastArtist) {',
'        const minsSince = (nowSec - lastArtist.played_at) / 60;',
'        if (minsSince < rule.value) {',
'          score -= penalty;',
'          violations.push("artist played " + Math.floor(minsSince) + "m ago (min " + rule.value + ")");',
'        }',
'      }',
'    }',
'',
'    if (rule.rule_type === "title_separation_min") {',
'      const lastTitle = recent.find(r => r.title.toLowerCase() === song.title.toLowerCase() && r.song_id !== song.id);',
'      if (lastTitle) {',
'        const minsSince = (nowSec - lastTitle.played_at) / 60;',
'        if (minsSince < rule.value) {',
'          score -= penalty;',
'          violations.push("same title played " + Math.floor(minsSince) + "m ago");',
'        }',
'      }',
'    }',
'',
'    if (rule.rule_type === "max_same_gender" && song.gender && song.gender !== "unknown") {',
'      let consecutive = 0;',
'      for (const r of recent) {',
'        if (r.gender === song.gender) consecutive++;',
'        else break;',
'      }',
'      if (consecutive >= rule.value) {',
'        score -= penalty;',
'        violations.push(consecutive + " consecutive " + song.gender + " (max " + rule.value + ")");',
'      }',
'    }',
'',
'    if (rule.rule_type === "max_same_category" && song.category_id) {',
'      let consecutive = 0;',
'      for (const r of recent) {',
'        if (r.category_id === song.category_id) consecutive++;',
'        else break;',
'      }',
'      if (consecutive >= rule.value) {',
'        score -= penalty;',
'        violations.push(consecutive + " consecutive from same category (max " + rule.value + ")");',
'      }',
'    }',
'  }',
'',
'  // Bonus: prefer songs that havent played recently',
'  if (!song.last_played_at) score += 50;',
'  else {',
'    const hoursSince = (nowSec - song.last_played_at) / 3600;',
'    score += Math.min(hoursSince * 2, 100);',
'  }',
'',
'  // Bonus: prefer lower spin counts',
'  score -= Math.min(song.spins_total * 2, 200);',
'',
'  return { score, violations };',
'}',
'',
'// ============================================================',
'// PICK BEST SONG — scores all candidates, returns the winner',
'// ============================================================',
'',
'async function pickBestSong(categoryId: number, recent: RecentPlay[], rules: SepRule[], usedInHour: number[]): Promise<SongCandidate | null> {',
'  const candidates = await query<SongCandidate>(',
'    "SELECT s.id, s.title, s.file_path, s.artist_id, a.name as artist_name, s.category_id, s.gender, s.last_played_at, s.spins_total " +',
'    "FROM songs s LEFT JOIN artists a ON a.id = s.artist_id " +',
'    "WHERE s.category_id = ? AND s.file_path IS NOT NULL AND s.rotation_status = \'active\' " +',
'    "ORDER BY s.last_played_at ASC NULLS FIRST, RANDOM() LIMIT 50",',
'    [categoryId]',
'  );',
'',
'  if (candidates.length === 0) return null;',
'',
'  let bestSong = candidates[0];',
'  let bestScore = -99999;',
'',
'  for (const c of candidates) {',
'    const { score } = scoreSong(c, recent, rules, usedInHour);',
'    if (score > bestScore) {',
'      bestScore = score;',
'      bestSong = c;',
'    }',
'  }',
'',
'  // If best score is still deeply negative (all hard rules violated),',
'  // still return the best option — prevents dead air',
'  return bestSong;',
'}',
'',
'async function pickAnySong(recent: RecentPlay[], rules: SepRule[], usedInHour: number[]): Promise<SongCandidate | null> {',
'  const candidates = await query<SongCandidate>(',
'    "SELECT s.id, s.title, s.file_path, s.artist_id, a.name as artist_name, s.category_id, s.gender, s.last_played_at, s.spins_total " +',
'    "FROM songs s LEFT JOIN artists a ON a.id = s.artist_id " +',
'    "WHERE s.file_path IS NOT NULL AND s.rotation_status = \'active\' " +',
'    "ORDER BY RANDOM() LIMIT 30"',
'  );',
'  if (candidates.length === 0) return null;',
'  let best = candidates[0];',
'  let bestScore = -99999;',
'  for (const c of candidates) {',
'    const { score } = scoreSong(c, recent, rules, usedInHour);',
'    if (score > bestScore) { bestScore = score; best = c; }',
'  }',
'  return best;',
'}',
'',
'// ============================================================',
'// CLOCK LOOKUP',
'// ============================================================',
'',
'async function getClockFromShow(): Promise<number | null> {',
'  const now = new Date();',
'  const hour = now.getHours();',
'  const shows = await query<{ id: number; start_hour: number; end_hour: number; clock_id: number | null }>("SELECT * FROM shows WHERE is_active = 1 AND clock_id IS NOT NULL");',
'  for (const s of shows) {',
'    if (s.end_hour > s.start_hour) {',
'      if (hour >= s.start_hour && hour < s.end_hour) return s.clock_id;',
'    } else {',
'      if (hour >= s.start_hour || hour < s.end_hour) return s.clock_id;',
'    }',
'  }',
'  return null;',
'}',
'',
'async function getClockForNow(): Promise<number | null> {',
'  const fromShow = await getClockFromShow();',
'  if (fromShow) return fromShow;',
'  const now = new Date();',
'  const row = await queryOne<{ clock_id: number }>("SELECT clock_id FROM schedule_grid WHERE day_of_week = ? AND hour = ?", [now.getDay(), now.getHours()]);',
'  return row ? row.clock_id : null;',
'}',
'',
'async function getClockSlots(clockId: number): Promise<SlotDef[]> {',
'  return query<SlotDef>("SELECT * FROM clock_slots WHERE clock_id = ? ORDER BY position", [clockId]);',
'}',
'',
'async function markPlayed(songId: number): Promise<void> {',
'  await execute("UPDATE songs SET last_played_at = unixepoch(), spins_total = spins_total + 1, updated_at = unixepoch() WHERE id = ?", [songId]);',
'}',
'',
'// ============================================================',
'// GENERATE LOG HOUR',
'// ============================================================',
'',
'export interface LogItem {',
'  slotType: string; songId: number | null;',
'  title: string; artist: string; filePath: string;',
'  categoryId: number | null; violations: string[];',
'}',
'',
'export async function generateLogHour(): Promise<LogItem[]> {',
'  const clockId = await getClockForNow();',
'  const rules = await getRules();',
'  const recent = await getRecentPlays(240);',
'',
'  if (!clockId) {',
'    console.log("No clock assigned, falling back to scored random");',
'    return generateScoredRandom(rules, recent);',
'  }',
'',
'  const slots = await getClockSlots(clockId);',
'  if (slots.length === 0) return generateScoredRandom(rules, recent);',
'',
'  const log: LogItem[] = [];',
'  const usedIds: number[] = [];',
'',
'  for (const slot of slots) {',
'    if (slot.slot_type === "music" && slot.category_id) {',
'      const song = await pickBestSong(slot.category_id, recent, rules, usedIds);',
'      if (song) {',
'        const { violations } = scoreSong(song, recent, rules, usedIds);',
'        log.push({ slotType: "music", songId: song.id, title: song.title, artist: song.artist_name || "", filePath: song.file_path, categoryId: slot.category_id, violations });',
'        usedIds.push(song.id);',
'        // Add to recent for subsequent scoring this hour',
'        recent.unshift({ song_id: song.id, title: song.title, artist: song.artist_name || null, artist_id: song.artist_id, category_id: song.category_id, gender: song.gender, played_at: Math.floor(Date.now() / 1000) });',
'      } else {',
'        const any = await pickAnySong(recent, rules, usedIds);',
'        if (any) {',
'          log.push({ slotType: "music", songId: any.id, title: any.title, artist: any.artist_name || "", filePath: any.file_path, categoryId: null, violations: ["category empty, fallback"] });',
'          usedIds.push(any.id);',
'        }',
'      }',
'    } else if (slot.slot_type !== "music") {',
'      log.push({ slotType: slot.slot_type, songId: null, title: "--- " + slot.slot_type.toUpperCase() + " ---", artist: "", filePath: "", categoryId: null, violations: [] });',
'    }',
'  }',
'',
'  return log;',
'}',
'',
'async function generateScoredRandom(rules: SepRule[], recent: RecentPlay[]): Promise<LogItem[]> {',
'  const log: LogItem[] = [];',
'  const usedIds: number[] = [];',
'  for (let i = 0; i < 15; i++) {',
'    const song = await pickAnySong(recent, rules, usedIds);',
'    if (song) {',
'      const { violations } = scoreSong(song, recent, rules, usedIds);',
'      log.push({ slotType: "music", songId: song.id, title: song.title, artist: song.artist_name || "", filePath: song.file_path, categoryId: song.category_id, violations });',
'      usedIds.push(song.id);',
'      recent.unshift({ song_id: song.id, title: song.title, artist: song.artist_name || null, artist_id: song.artist_id, category_id: song.category_id, gender: song.gender, played_at: Math.floor(Date.now() / 1000) });',
'    }',
'  }',
'  return log;',
'}',
'',
'// ============================================================',
'// PUBLIC API',
'// ============================================================',
'',
'export async function fillQueueFromSchedule(): Promise<number> {',
'  const log = await generateLogHour();',
'  const musicItems = log.filter(l => l.slotType === "music" && l.filePath);',
'  engine.addToQueue(musicItems.map(l => ({ filePath: l.filePath, title: l.title, artist: l.artist })));',
'  for (const item of musicItems) {',
'    if (item.songId) await markPlayed(item.songId);',
'  }',
'  return musicItems.length;',
'}',
'',
'export async function refillFromSchedule(): Promise<{ filePath: string; title: string; artist: string }[]> {',
'  const log = await generateLogHour();',
'  const musicItems = log.filter(l => l.slotType === "music" && l.filePath);',
'  for (const item of musicItems) {',
'    if (item.songId) await markPlayed(item.songId);',
'  }',
'  return musicItems.map(l => ({ filePath: l.filePath, title: l.title, artist: l.artist }));',
'}',
].join('\n'), 'utf8');
console.log('  REWROTE src/audio/loggen.ts (full scoring engine)');

// ============================================================
// 3. Add Rules Editor to Settings tab
// ============================================================

fs.writeFileSync('src/components/RulesEditor.tsx', [
'import { useState, useEffect } from "react";',
'import { query, execute } from "../db/client";',
'',
'interface Rule {',
'  id: number; rule_type: string; scope: string;',
'  value: number; is_hard: number; is_active: number;',
'  description: string | null;',
'}',
'',
'const RULE_LABELS: Record<string, string> = {',
'  artist_separation_min: "Artist Separation (minutes)",',
'  song_separation_min: "Song Separation (minutes)",',
'  title_separation_min: "Title Separation (minutes)",',
'  max_same_gender: "Max Consecutive Same Gender",',
'  max_same_category: "Max Consecutive Same Category",',
'};',
'',
'export default function RulesEditor() {',
'  const [rules, setRules] = useState<Rule[]>([]);',
'',
'  const load = async () => { setRules(await query<Rule>("SELECT * FROM separation_rules ORDER BY id")); };',
'  useEffect(() => { load(); }, []);',
'',
'  const update = async (id: number, field: string, val: number) => {',
'    await execute("UPDATE separation_rules SET " + field + " = ? WHERE id = ?", [val, id]);',
'    load();',
'  };',
'',
'  return (',
'    <div className="space-y-3">',
'      <h2 className="text-sm font-bold text-zinc-300">Scheduling Rules</h2>',
'      <div className="text-xs text-zinc-500">These rules control how the log generator picks songs. Hard rules block violations entirely. Soft rules penalize but still allow if no better option exists.</div>',
'      <div className="space-y-2">',
'        {rules.map(r => (',
'          <div key={r.id} className="bg-zinc-900 rounded-lg border border-zinc-800 p-3 flex items-center justify-between">',
'            <div className="flex-1">',
'              <div className="text-xs text-zinc-100 font-medium">{RULE_LABELS[r.rule_type] || r.rule_type}</div>',
'              <div className="text-[10px] text-zinc-500">{r.description}</div>',
'            </div>',
'            <div className="flex items-center gap-3">',
'              <div className="flex items-center gap-1">',
'                <span className="text-[10px] text-zinc-500">Value:</span>',
'                <input type="number" className="w-16 px-2 py-1 bg-zinc-800 border border-zinc-700 rounded text-xs text-zinc-100 text-center" value={r.value} onChange={e => update(r.id, "value", parseInt(e.target.value) || 0)} />',
'              </div>',
'              <button onClick={() => update(r.id, "is_hard", r.is_hard ? 0 : 1)} className={r.is_hard ? "px-2 py-1 rounded text-[10px] font-bold bg-red-700 text-white" : "px-2 py-1 rounded text-[10px] font-bold bg-zinc-700 text-zinc-400"}>{r.is_hard ? "HARD" : "SOFT"}</button>',
'              <button onClick={() => update(r.id, "is_active", r.is_active ? 0 : 1)} className={r.is_active ? "px-2 py-1 rounded text-[10px] font-bold bg-emerald-700 text-white" : "px-2 py-1 rounded text-[10px] font-bold bg-zinc-800 text-zinc-500"}>{r.is_active ? "ON" : "OFF"}</button>',
'            </div>',
'          </div>',
'        ))}',
'      </div>',
'    </div>',
'  );',
'}',
].join('\n'), 'utf8');
console.log('  CREATED src/components/RulesEditor.tsx');

// ============================================================
// 4. Wire RulesEditor into Settings tab
// ============================================================

let app = fs.readFileSync('src/App.tsx', 'utf8');
if (!app.includes('RulesEditor')) {
  app = app.replace(
    'import Spots from "./components/Spots";',
    'import Spots from "./components/Spots";\nimport RulesEditor from "./components/RulesEditor";'
  );
  app = app.replace(
    '{panel === "settings" && <PH title="Settings" />}',
    '{panel === "settings" && <RulesEditor />}'
  );
  fs.writeFileSync('src/App.tsx', app, 'utf8');
  console.log('  UPDATED src/App.tsx (Settings = Rules Editor)');
}

console.log('\n  Done! Close app, delete DB, restart:');
console.log('  Remove-Item "$env:APPDATA\\com.openair.app\\openair.db*" -Force -ErrorAction SilentlyContinue');
console.log('  npm run tauri:dev\n');
console.log('  What the scoring engine does:');
console.log('');
console.log('  Every time a slot needs filling, it:');
console.log('    1. Pulls 50 candidates from the right category');
console.log('    2. Scores each one against ALL rules');
console.log('    3. Picks the highest-scoring song');
console.log('    4. Never dead-airs (worst score still plays)');
console.log('');
console.log('  Default rules (editable in Settings):');
console.log('    Artist separation:  60 min  (HARD)');
console.log('    Song separation:   240 min  (HARD)');
console.log('    Title separation:  120 min  (HARD)');
console.log('    Max same gender:     3      (SOFT)');
console.log('    Max same category:   3      (SOFT)');
console.log('');
console.log('  Hard = blocks (10,000 point penalty)');
console.log('  Soft = penalizes but allows (100 point penalty)');
console.log('');
console.log('  This is how GSelector works. You just got it for free.');
console.log('');
console.log('  Push + rebuild:');
console.log('    git add -A');
console.log('    git commit -m "v0.9.0 artist/song separation rules - scoring engine"');
console.log('    git push');
console.log('    npm run tauri:build\n');
