const fs = require('fs');

console.log('\n  Ether — UI Polish + Shuffle Update\n');

// ============================================================
// Updated engine with waveform data + shuffle
// ============================================================

fs.mkdirSync('src/audio', { recursive: true });
fs.writeFileSync('src/audio/engine.ts', [
'import { convertFileSrc } from "@tauri-apps/api/core";',
'',
'export type DeckId = "A" | "B";',
'export type DeckStatus = "idle" | "loading" | "playing" | "paused" | "ended" | "error";',
'',
'export interface DeckState {',
'  id: DeckId; status: DeckStatus; title: string; artist: string;',
'  filePath: string; durationSec: number; positionSec: number;',
'  volume: number; error: string | null;',
'  peaks: number[];',
'}',
'',
'type Listener = (deck: DeckId, state: DeckState) => void;',
'type EndCallback = (deck: DeckId) => void;',
'',
'function extractPeaks(buffer: AudioBuffer, numPeaks: number): number[] {',
'  const chan = buffer.getChannelData(0);',
'  const step = Math.floor(chan.length / numPeaks);',
'  const peaks: number[] = [];',
'  for (let i = 0; i < numPeaks; i++) {',
'    let max = 0;',
'    const start = i * step;',
'    const end = Math.min(start + step, chan.length);',
'    for (let j = start; j < end; j++) {',
'      const abs = Math.abs(chan[j]);',
'      if (abs > max) max = abs;',
'    }',
'    peaks.push(max);',
'  }',
'  return peaks;',
'}',
'',
'class Deck {',
'  id: DeckId;',
'  private ctx: AudioContext;',
'  private gainNode: GainNode;',
'  private source: AudioBufferSourceNode | null = null;',
'  private buf: AudioBuffer | null = null;',
'  private startedAt = 0;',
'  private offset = 0;',
'  private timer: any = null;',
'  private notify: Listener;',
'  private onEnd: EndCallback;',
'  status: DeckStatus = "idle";',
'  title = ""; artist = ""; filePath = "";',
'  durationSec = 0; volume = 1; error: string | null = null;',
'  peaks: number[] = [];',
'',
'  constructor(id: DeckId, ctx: AudioContext, notify: Listener, onEnd: EndCallback) {',
'    this.id = id; this.ctx = ctx; this.notify = notify; this.onEnd = onEnd;',
'    this.gainNode = ctx.createGain(); this.gainNode.connect(ctx.destination);',
'  }',
'',
'  get positionSec(): number {',
'    if (this.status !== "playing") return this.offset;',
'    return this.offset + (this.ctx.currentTime - this.startedAt);',
'  }',
'',
'  getState(): DeckState {',
'    return { id: this.id, status: this.status, title: this.title, artist: this.artist,',
'      filePath: this.filePath, durationSec: this.durationSec, positionSec: this.positionSec,',
'      volume: this.volume, error: this.error, peaks: this.peaks };',
'  }',
'',
'  private emit() { this.notify(this.id, this.getState()); }',
'',
'  async load(filePath: string, title: string, artist: string) {',
'    this.stop();',
'    this.status = "loading"; this.filePath = filePath;',
'    this.title = title; this.artist = artist; this.error = null;',
'    this.peaks = [];',
'    this.emit();',
'    try {',
'      const url = convertFileSrc(filePath);',
'      const resp = await fetch(url);',
'      if (!resp.ok) throw new Error("fetch failed: " + resp.status);',
'      const ab = await resp.arrayBuffer();',
'      this.buf = await this.ctx.decodeAudioData(ab);',
'      this.durationSec = this.buf.duration;',
'      this.peaks = extractPeaks(this.buf, 200);',
'      this.status = "idle"; this.emit();',
'    } catch (e) {',
'      this.status = "error"; this.error = String(e); this.emit();',
'    }',
'  }',
'',
'  play(fromSec = 0) {',
'    if (!this.buf) return;',
'    if (this.status === "playing") this.killSource();',
'    const src = this.ctx.createBufferSource();',
'    src.buffer = this.buf; src.connect(this.gainNode);',
'    src.start(0, fromSec);',
'    this.source = src; this.startedAt = this.ctx.currentTime;',
'    this.offset = fromSec; this.status = "playing"; this.emit();',
'    src.onended = () => {',
'      if (this.status === "playing") {',
'        this.status = "ended"; this.offset = this.durationSec;',
'        this.clearTimer(); this.emit();',
'        this.onEnd(this.id);',
'      }',
'    };',
'    this.startTimer();',
'  }',
'',
'  pause() {',
'    if (this.status !== "playing") return;',
'    this.offset = this.positionSec; this.killSource();',
'    this.status = "paused"; this.clearTimer(); this.emit();',
'  }',
'',
'  resume() { if (this.status === "paused") this.play(this.offset); }',
'',
'  stop() {',
'    this.killSource(); this.clearTimer();',
'    this.status = "idle"; this.offset = 0;',
'    this.gainNode.gain.setValueAtTime(1, this.ctx.currentTime);',
'    this.volume = 1; this.emit();',
'  }',
'',
'  setVolume(v: number) {',
'    this.volume = Math.max(0, Math.min(1, v));',
'    this.gainNode.gain.setTargetAtTime(this.volume, this.ctx.currentTime, 0.01);',
'  }',
'',
'  fadeTo(vol: number, sec: number) {',
'    this.volume = vol;',
'    this.gainNode.gain.linearRampToValueAtTime(vol, this.ctx.currentTime + sec);',
'  }',
'',
'  private killSource() { try { this.source?.stop(); } catch {} this.source = null; }',
'  private startTimer() { this.clearTimer(); this.timer = setInterval(() => this.emit(), 100); }',
'  private clearTimer() { if (this.timer) { clearInterval(this.timer); this.timer = null; } }',
'}',
'',
'export class AudioEngine {',
'  private ctx: AudioContext | null = null;',
'  private deckA: Deck | null = null;',
'  private deckB: Deck | null = null;',
'  private listeners = new Set<Listener>();',
'  private onEvt: Listener = (id, st) => { this.listeners.forEach(l => l(id, st)); };',
'',
'  private queue: { filePath: string; title: string; artist: string }[] = [];',
'  autoAdvance = false;',
'  shuffle = false;',
'',
'  private handleDeckEnd = (deckId: DeckId) => {',
'    if (!this.autoAdvance) return;',
'    if (this.queue.length === 0) return;',
'    let idx = 0;',
'    if (this.shuffle) idx = Math.floor(Math.random() * this.queue.length);',
'    const next = this.queue.splice(idx, 1)[0];',
'    const deck = this.getDeck(deckId);',
'    if (deck) {',
'      deck.load(next.filePath, next.title, next.artist).then(() => {',
'        deck.play();',
'        this.listeners.forEach(l => l(deckId, deck.getState()));',
'      });',
'    }',
'  };',
'',
'  init() {',
'    if (this.ctx) return;',
'    this.ctx = new AudioContext({ sampleRate: 44100 });',
'    this.deckA = new Deck("A", this.ctx, this.onEvt, this.handleDeckEnd);',
'    this.deckB = new Deck("B", this.ctx, this.onEvt, this.handleDeckEnd);',
'  }',
'',
'  on(fn: Listener): () => void { this.listeners.add(fn); return () => this.listeners.delete(fn); }',
'  getDeck(id: DeckId): Deck | null { return id === "A" ? this.deckA : this.deckB; }',
'',
'  async loadToDeck(id: DeckId, filePath: string, title: string, artist: string) {',
'    this.init(); const d = this.getDeck(id); if (d) await d.load(filePath, title, artist);',
'  }',
'',
'  addToQueue(songs: { filePath: string; title: string; artist: string }[]) { this.queue.push(...songs); }',
'  clearQueue() { this.queue = []; }',
'  getQueue() { return [...this.queue]; }',
'',
'  crossfade(fromId: DeckId, toId: DeckId, ms = 2000) {',
'    const from = this.getDeck(fromId);',
'    const to = this.getDeck(toId);',
'    if (!from || !to) return;',
'    to.setVolume(1);',
'    to.play();',
'    from.fadeTo(0, ms / 1000);',
'    setTimeout(() => { from.stop(); from.setVolume(1); }, ms + 100);',
'  }',
'}',
'',
'export const engine = new AudioEngine();',
].join('\n'), 'utf8');
console.log('  UPDATED src/audio/engine.ts (waveform peaks + shuffle)');

// ============================================================
// Waveform component
// ============================================================

fs.mkdirSync('src/components', { recursive: true });
fs.writeFileSync('src/components/Waveform.tsx', [
'import { useRef, useEffect } from "react";',
'',
'interface Props {',
'  peaks: number[];',
'  progress: number; // 0 to 1',
'  color: string;',
'  playedColor: string;',
'  height?: number;',
'}',
'',
'export default function Waveform({ peaks, progress, color, playedColor, height = 60 }: Props) {',
'  const canvasRef = useRef<HTMLCanvasElement>(null);',
'',
'  useEffect(() => {',
'    const canvas = canvasRef.current;',
'    if (!canvas) return;',
'    const ctx = canvas.getContext("2d");',
'    if (!ctx) return;',
'',
'    const w = canvas.width;',
'    const h = canvas.height;',
'    const mid = h / 2;',
'    const barW = Math.max(1, w / (peaks.length || 1));',
'    const playedX = progress * w;',
'',
'    ctx.clearRect(0, 0, w, h);',
'',
'    if (peaks.length === 0) {',
'      ctx.fillStyle = "#27272a";',
'      ctx.fillRect(0, 0, w, h);',
'      ctx.fillStyle = "#3f3f46";',
'      ctx.font = "11px sans-serif";',
'      ctx.textAlign = "center";',
'      ctx.fillText("No track loaded", w / 2, mid + 4);',
'      return;',
'    }',
'',
'    for (let i = 0; i < peaks.length; i++) {',
'      const x = i * barW;',
'      const barH = peaks[i] * mid * 0.9;',
'      ctx.fillStyle = x < playedX ? playedColor : color;',
'      ctx.fillRect(x, mid - barH, Math.max(1, barW - 0.5), barH * 2);',
'    }',
'',
'    // Playhead line',
'    if (progress > 0 && progress < 1) {',
'      ctx.strokeStyle = "#ffffff";',
'      ctx.lineWidth = 1.5;',
'      ctx.beginPath();',
'      ctx.moveTo(playedX, 0);',
'      ctx.lineTo(playedX, h);',
'      ctx.stroke();',
'    }',
'  }, [peaks, progress, color, playedColor, height]);',
'',
'  return (',
'    <canvas',
'      ref={canvasRef}',
'      width={600}',
'      height={height}',
'      style={{ width: "100%", height: height + "px", borderRadius: "6px", background: "#18181b" }}',
'    />',
'  );',
'}',
].join('\n'), 'utf8');
console.log('  CREATED src/components/Waveform.tsx');

// ============================================================
// Updated App.tsx — polished UI
// ============================================================

fs.writeFileSync('src/App.tsx', [
'import { useState, useEffect, useCallback } from "react";',
'import { query, execute, queryOne } from "./db/client";',
'import { open } from "@tauri-apps/plugin-dialog";',
'import { readDir } from "@tauri-apps/plugin-fs";',
'import { engine, DeckState } from "./audio/engine";',
'import Waveform from "./components/Waveform";',
'',
'type Panel = "live" | "library" | "clocks" | "logs" | "spots" | "settings";',
'',
'interface SongRow {',
'  id: number; title: string; file_path: string | null;',
'  artist_name: string | null; album_title: string | null;',
'  genre: string | null; duration_ms: number;',
'  category_code: string | null; category_color: string | null;',
'}',
'',
'const EXTS = [".mp3",".flac",".ogg",".wav",".m4a",".aac",".wma",".aiff"];',
'function isAudio(n: string) { return EXTS.some(e => n.toLowerCase().endsWith(e)); }',
'function titleFromFile(p: string) { return (p.split(/[\\\\/]/).pop() || p).replace(/\\.[^.]+$/, "").replace(/[_-]/g, " ").replace(/^\\d+\\.?\\s*/, ""); }',
'function fmtExt(p: string) { return (p.split(".").pop() || "").toLowerCase(); }',
'function fmtTime(s: number) { if (!s || s < 0) return "0:00"; return Math.floor(s/60) + ":" + String(Math.floor(s%60)).padStart(2,"0"); }',
'function fmtTimeLong(s: number) { if (!s || s < 0) return "00:00.0"; const m = Math.floor(s/60); const sec = s % 60; return String(m).padStart(2,"0") + ":" + sec.toFixed(1).padStart(4,"0"); }',
'',
'export default function App() {',
'  const [panel, setPanel] = useState<Panel>("live");',
'  const [onAir, setOnAir] = useState(false);',
'  const [deckA, setDeckA] = useState<DeckState | null>(null);',
'  const [deckB, setDeckB] = useState<DeckState | null>(null);',
'  const [autoAdv, setAutoAdv] = useState(false);',
'  const [shuffle, setShuffle] = useState(false);',
'  const [queueLen, setQueueLen] = useState(0);',
'',
'  useEffect(() => {',
'    engine.init();',
'    return engine.on((id, st) => {',
'      if (id === "A") setDeckA({...st});',
'      else setDeckB({...st});',
'      setQueueLen(engine.getQueue().length);',
'    });',
'  }, []);',
'',
'  const toggleAuto = () => { const n = !autoAdv; setAutoAdv(n); engine.autoAdvance = n; };',
'  const toggleShuffle = () => { const n = !shuffle; setShuffle(n); engine.shuffle = n; };',
'',
'  const loadA = useCallback((s: SongRow) => { if (s.file_path) engine.loadToDeck("A", s.file_path, s.title, s.artist_name || ""); }, []);',
'  const loadB = useCallback((s: SongRow) => { if (s.file_path) engine.loadToDeck("B", s.file_path, s.title, s.artist_name || ""); }, []);',
'  const addToQueue = useCallback((s: SongRow) => {',
'    if (s.file_path) { engine.addToQueue([{ filePath: s.file_path, title: s.title, artist: s.artist_name || "" }]); setQueueLen(engine.getQueue().length); }',
'  }, []);',
'',
'  return (',
'    <div className="h-screen flex flex-col bg-zinc-950 text-zinc-100">',
'      <header className="h-12 flex items-center justify-between px-4 bg-zinc-900 border-b border-zinc-800 shrink-0">',
'        <div className="flex items-center gap-3">',
'          <span className="text-lg font-bold tracking-tight"><span className="text-blue-400">Eth</span>er</span>',
'          <span className="text-xs text-zinc-500">v0.2.0</span>',
'        </div>',
'        <div className="flex items-center gap-2 text-sm text-zinc-400">',
'          <ClockDisplay />',
'          <button onClick={() => { engine.init(); setOnAir(!onAir); }} className={onAir ? "ml-3 px-3 py-1 rounded text-xs font-bold uppercase tracking-wider bg-red-600 text-white animate-pulse" : "ml-3 px-3 py-1 rounded text-xs font-bold uppercase tracking-wider bg-zinc-700 text-zinc-400 hover:bg-zinc-600"}>{onAir ? "ON AIR" : "OFF AIR"}</button>',
'        </div>',
'      </header>',
'      <div className="flex flex-1 overflow-hidden">',
'        <Nav active={panel} set={setPanel} />',
'        <main className="flex-1 overflow-auto p-4">',
'          {panel === "live" && <LivePanel deckA={deckA} deckB={deckB} autoAdv={autoAdv} shuffle={shuffle} toggleAuto={toggleAuto} toggleShuffle={toggleShuffle} queueLen={queueLen} />}',
'          {panel === "library" && <LibraryPanel onLoadA={loadA} onLoadB={loadB} onQueue={addToQueue} />}',
'          {panel === "clocks" && <PH title="Clock Builder" />}',
'          {panel === "logs" && <PH title="Log Builder" />}',
'          {panel === "spots" && <PH title="Spot Inventory" />}',
'          {panel === "settings" && <PH title="Settings" />}',
'        </main>',
'      </div>',
'      <footer className="h-7 flex items-center justify-between px-4 bg-zinc-900 border-t border-zinc-800 text-[11px] text-zinc-500 shrink-0">',
'        <span>{deckA?.status === "playing" ? "Playing: " + deckA.title : "Ready"}</span>',
'        <span>{autoAdv ? "AUTO" : "MANUAL"}{shuffle ? " | SHUFFLE" : ""} | Queue: {queueLen}</span>',
'      </footer>',
'    </div>',
'  );',
'}',
'',
'function Nav({ active, set }: { active: Panel; set: (p: Panel) => void }) {',
'  const items: { id: Panel; label: string }[] = [',
'    { id: "live", label: "Live Assist" }, { id: "library", label: "Library" },',
'    { id: "clocks", label: "Clocks" }, { id: "logs", label: "Logs" },',
'    { id: "spots", label: "Spots" }, { id: "settings", label: "Settings" },',
'  ];',
'  return (',
'    <nav className="w-44 bg-zinc-900 border-r border-zinc-800 flex flex-col py-2 shrink-0">',
'      {items.map(i => <button key={i.id} onClick={() => set(i.id)} className={active === i.id ? "px-4 py-2.5 text-sm text-left bg-zinc-800 text-white border-l-2 border-blue-400" : "px-4 py-2.5 text-sm text-left text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 border-l-2 border-transparent"}>{i.label}</button>)}',
'      <div className="mt-auto px-4 py-3 text-[10px] text-zinc-600">Ether v0.2.0<br/>Free forever</div>',
'    </nav>',
'  );',
'}',
'',
'// ============================================================',
'// LIVE PANEL — polished',
'// ============================================================',
'',
'function LivePanel({ deckA, deckB, autoAdv, shuffle, toggleAuto, toggleShuffle, queueLen }: { deckA: DeckState | null; deckB: DeckState | null; autoAdv: boolean; shuffle: boolean; toggleAuto: () => void; toggleShuffle: () => void; queueLen: number }) {',
'  const handleXfade = () => {',
'    if (deckA?.status === "playing" && deckB?.filePath) engine.crossfade("A", "B", 2000);',
'    else if (deckB?.status === "playing" && deckA?.filePath) engine.crossfade("B", "A", 2000);',
'  };',
'  const queue = engine.getQueue();',
'  return (',
'    <div className="space-y-3">',
'      <div className="flex items-center justify-between">',
'        <h1 className="text-lg font-bold">Live Assist</h1>',
'        <div className="flex items-center gap-1.5">',
'          <button onClick={toggleShuffle} className={shuffle ? "px-2.5 py-1 rounded text-[11px] font-bold bg-amber-600 text-white" : "px-2.5 py-1 rounded text-[11px] font-bold bg-zinc-800 text-zinc-500 hover:bg-zinc-700"}>SHUFFLE</button>',
'          <button onClick={toggleAuto} className={autoAdv ? "px-2.5 py-1 rounded text-[11px] font-bold bg-blue-600 text-white" : "px-2.5 py-1 rounded text-[11px] font-bold bg-zinc-800 text-zinc-500 hover:bg-zinc-700"}>AUTO</button>',
'          <button onClick={handleXfade} className="px-3 py-1 bg-purple-700 hover:bg-purple-600 rounded text-[11px] font-bold text-white">CROSSFADE</button>',
'        </div>',
'      </div>',
'      <div className="grid grid-cols-2 gap-3">',
'        <DeckCard deck={deckA} deckId="A" accentColor="#3b82f6" waveColor="#1e3a5f" playedColor="#3b82f6" />',
'        <DeckCard deck={deckB} deckId="B" accentColor="#10b981" waveColor="#1a3a2a" playedColor="#10b981" />',
'      </div>',
'      <div className="bg-zinc-900 rounded-lg p-3 border border-zinc-800">',
'        <div className="flex items-center justify-between mb-2">',
'          <h2 className="text-[11px] font-bold text-zinc-400 uppercase">Queue ({queueLen})</h2>',
'          {queue.length > 0 && <button onClick={() => engine.clearQueue()} className="text-[11px] text-zinc-600 hover:text-zinc-400">Clear</button>}',
'        </div>',
'        {queue.length === 0 ? (',
'          <div className="text-xs text-zinc-600 italic">Empty. Add songs from Library with the Q button.</div>',
'        ) : (',
'          <div className="space-y-0.5 max-h-40 overflow-y-auto">',
'            {queue.slice(0, 15).map((item, i) => (',
'              <div key={i} className="flex items-center justify-between px-2 py-1 bg-zinc-800 rounded text-xs">',
'                <span className="text-zinc-400 w-5">{i + 1}</span>',
'                <span className="text-zinc-200 flex-1 truncate">{item.title}</span>',
'                <span className="text-zinc-500 text-[10px] ml-2">{item.artist}</span>',
'              </div>',
'            ))}',
'            {queue.length > 15 && <div className="text-[10px] text-zinc-600 text-center py-1">+ {queue.length - 15} more</div>}',
'          </div>',
'        )}',
'      </div>',
'    </div>',
'  );',
'}',
'',
'// ============================================================',
'// DECK CARD — with waveform',
'// ============================================================',
'',
'function DeckCard({ deck, deckId, accentColor, waveColor, playedColor }: { deck: DeckState | null; deckId: "A" | "B"; accentColor: string; waveColor: string; playedColor: string }) {',
'  const d = engine.getDeck(deckId);',
'  const st = deck?.status || "idle";',
'  const pos = deck?.positionSec || 0;',
'  const dur = deck?.durationSec || 0;',
'  const progress = dur > 0 ? pos / dur : 0;',
'  const peaks = deck?.peaks || [];',
'',
'  const handlePlay = () => {',
'    if (!d) return;',
'    if (st === "playing") d.pause();',
'    else if (st === "paused") d.resume();',
'    else d.play();',
'  };',
'',
'  const pLabel = st === "playing" ? "PAUSE" : st === "paused" ? "RESUME" : "PLAY";',
'',
'  const statusColor = st === "playing" ? "text-emerald-400" : st === "paused" ? "text-yellow-400" : st === "loading" ? "text-blue-400" : st === "error" ? "text-red-400" : "text-zinc-600";',
'',
'  return (',
'    <div className="bg-zinc-900 rounded-lg border border-zinc-800 overflow-hidden">',
'      <div className="flex items-center justify-between px-3 py-2 bg-zinc-800">',
'        <div className="flex items-center gap-2">',
'          <span className="text-[11px] font-bold uppercase tracking-wider" style={{ color: accentColor }}>{"Deck " + deckId}</span>',
'          <span className={"text-[10px] uppercase font-bold " + statusColor}>{st}</span>',
'        </div>',
'      </div>',
'',
'      <div className="px-3 pt-2">',
'        <div className="text-sm text-zinc-100 truncate font-medium">{deck?.title || "No track loaded"}</div>',
'        <div className="text-[11px] text-zinc-500 truncate">{deck?.artist || ""}</div>',
'      </div>',
'',
'      <div className="px-3 py-2">',
'        <Waveform peaks={peaks} progress={progress} color={waveColor} playedColor={playedColor} height={50} />',
'      </div>',
'',
'      <div className="flex justify-between px-3 text-zinc-400 mb-2">',
'        <span className="text-lg font-mono font-bold">{fmtTimeLong(pos)}</span>',
'        <span className="text-lg font-mono font-bold text-zinc-600">-{fmtTimeLong(dur - pos)}</span>',
'      </div>',
'',
'      <div className="flex items-center gap-1.5 px-3 pb-2">',
'        <button onClick={() => d?.stop()} className="px-3 py-2 bg-zinc-800 hover:bg-zinc-700 rounded text-xs font-bold text-zinc-400">STOP</button>',
'        <button onClick={handlePlay} className="flex-1 py-2 rounded text-xs font-bold text-white" style={{ backgroundColor: st === "playing" ? "#ca8a04" : accentColor }}>{pLabel}</button>',
'      </div>',
'',
'      <div className="flex items-center gap-2 px-3 pb-3 text-xs text-zinc-500">',
'        <span className="text-[10px]">VOL</span>',
'        <input type="range" min="0" max="100" value={Math.round((deck?.volume || 1) * 100)} onChange={e => d?.setVolume(parseInt(e.target.value) / 100)} className="flex-1 h-1 accent-blue-500" />',
'        <span className="text-[10px] w-8 text-right">{Math.round((deck?.volume || 1) * 100)}%</span>',
'      </div>',
'',
'      {deck?.error ? <div className="px-3 pb-2 text-[11px] text-red-400">{deck.error}</div> : null}',
'    </div>',
'  );',
'}',
'',
'// ============================================================',
'// LIBRARY',
'// ============================================================',
'',
'function LibraryPanel({ onLoadA, onLoadB, onQueue }: { onLoadA: (s: SongRow) => void; onLoadB: (s: SongRow) => void; onQueue: (s: SongRow) => void }) {',
'  const [songs, setSongs] = useState<SongRow[]>([]);',
'  const [loading, setLoading] = useState(true);',
'  const [search, setSearch] = useState("");',
'  const [count, setCount] = useState(0);',
'  const [importing, setImporting] = useState(false);',
'  const [status, setStatus] = useState("");',
'',
'  const load = async () => {',
'    try {',
'      const rows = await query<SongRow>("SELECT s.*, a.name as artist_name, al.title as album_title, c.code as category_code, c.color as category_color FROM songs s LEFT JOIN artists a ON a.id = s.artist_id LEFT JOIN albums al ON al.id = s.album_id LEFT JOIN categories c ON c.id = s.category_id ORDER BY s.title LIMIT 500");',
'      setSongs(rows);',
'      const r = await queryOne<{ c: number }>("SELECT COUNT(*) as c FROM songs");',
'      setCount(r ? r.c : 0);',
'    } catch (e) { console.error(e); setStatus("Error: " + e); }',
'    setLoading(false);',
'  };',
'',
'  useEffect(() => { load(); }, []);',
'',
'  const handleImport = async () => {',
'    try {',
'      const folder = await open({ directory: true, title: "Select Music Folder" });',
'      if (!folder) return;',
'      setImporting(true); setStatus("Scanning...");',
'      const entries = await readDir(folder as string);',
'      const files: string[] = [];',
'      for (const e of entries) {',
'        if (e.name && isAudio(e.name)) {',
'          const sep = (folder as string).includes("/") ? "/" : "\\\\";',
'          files.push((folder as string) + sep + e.name);',
'        }',
'      }',
'      if (files.length === 0) { setStatus("No audio files found."); setTimeout(() => setStatus(""), 3000); setImporting(false); return; }',
'      let n = 0;',
'      for (const fp of files) {',
'        const ex = await queryOne<{ id: number }>("SELECT id FROM songs WHERE file_path = ?", [fp]);',
'        if (!ex) {',
'          await execute("INSERT INTO songs (title, file_path, file_format, daypart_mask) VALUES (?, ?, ?, ?)", [titleFromFile(fp), fp, fmtExt(fp), 16777215]);',
'          n++;',
'        }',
'        setStatus("Importing... " + n);',
'      }',
'      setStatus("Done! " + n + " imported."); setTimeout(() => setStatus(""), 4000);',
'      setImporting(false); load();',
'    } catch (e) { console.error(e); setStatus("Error: " + e); setImporting(false); }',
'  };',
'',
'  const queueAll = () => {',
'    const items = filtered.filter(s => s.file_path);',
'    engine.addToQueue(items.map(s => ({ filePath: s.file_path!, title: s.title, artist: s.artist_name || "" })));',
'  };',
'',
'  const filtered = search ? songs.filter(s => (s.title||"").toLowerCase().includes(search.toLowerCase()) || (s.artist_name||"").toLowerCase().includes(search.toLowerCase())) : songs;',
'',
'  return (',
'    <div className="space-y-3">',
'      <div className="flex items-center justify-between">',
'        <h1 className="text-lg font-bold">Song Library</h1>',
'        <span className="text-xs text-zinc-500">{count} tracks</span>',
'      </div>',
'      <div className="flex items-center gap-2">',
'        <input type="text" placeholder="Search..." value={search} onChange={e => setSearch(e.target.value)} className="flex-1 px-3 py-1.5 bg-zinc-800 border border-zinc-700 rounded text-sm text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-blue-500" />',
'        <button onClick={queueAll} className="px-3 py-1.5 bg-emerald-700 hover:bg-emerald-600 rounded text-xs font-bold text-white">Queue All</button>',
'        <button onClick={handleImport} disabled={importing} className="px-3 py-1.5 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 rounded text-xs font-bold text-white">Import</button>',
'      </div>',
'      {status ? <div className="px-3 py-1.5 bg-blue-900 border border-blue-700 rounded text-xs text-blue-200">{status}</div> : null}',
'      {loading ? <div className="text-sm text-zinc-500">Loading...</div> : filtered.length === 0 ? (',
'        <div className="text-center py-16">',
'          <div className="text-zinc-400 text-lg mb-2">No music yet</div>',
'          <button onClick={handleImport} className="px-6 py-3 bg-blue-600 hover:bg-blue-500 rounded-lg text-sm font-medium text-white">Import Music Folder</button>',
'        </div>',
'      ) : (',
'        <div className="bg-zinc-900 rounded-lg border border-zinc-800 overflow-hidden">',
'          <table className="w-full text-xs">',
'            <thead><tr className="text-left text-[10px] text-zinc-500 uppercase border-b border-zinc-800">',
'              <th className="px-2 py-1.5 w-7">#</th>',
'              <th className="px-2 py-1.5">Title</th>',
'              <th className="px-2 py-1.5">Artist</th>',
'              <th className="px-2 py-1.5">Fmt</th>',
'              <th className="px-2 py-1.5 text-right w-28">Load</th>',
'            </tr></thead>',
'            <tbody>{filtered.map((s, i) => (',
'              <tr key={s.id} className="border-b border-zinc-800 hover:bg-zinc-800 group">',
'                <td className="px-2 py-1.5 text-zinc-600">{i+1}</td>',
'                <td className="px-2 py-1.5 text-zinc-100">{s.title}</td>',
'                <td className="px-2 py-1.5 text-zinc-400">{s.artist_name || "Unknown"}</td>',
'                <td className="px-2 py-1.5 text-zinc-500 uppercase">{s.file_path ? fmtExt(s.file_path) : "--"}</td>',
'                <td className="px-2 py-1.5 text-right">',
'                  <button onClick={() => onLoadA(s)} className="px-1.5 py-0.5 bg-blue-700 hover:bg-blue-600 rounded text-[9px] font-bold text-white mr-0.5">A</button>',
'                  <button onClick={() => onLoadB(s)} className="px-1.5 py-0.5 bg-emerald-700 hover:bg-emerald-600 rounded text-[9px] font-bold text-white mr-0.5">B</button>',
'                  <button onClick={() => onQueue(s)} className="px-1.5 py-0.5 bg-zinc-700 hover:bg-zinc-600 rounded text-[9px] font-bold text-white">Q</button>',
'                </td>',
'              </tr>',
'            ))}</tbody>',
'          </table>',
'        </div>',
'      )}',
'    </div>',
'  );',
'}',
'',
'function PH({ title }: { title: string }) {',
'  return <div className="flex flex-col items-center justify-center h-full text-center"><h1 className="text-xl font-bold mb-2">{title}</h1><p className="text-xs text-zinc-600 mt-2">Coming soon</p></div>;',
'}',
'',
'function ClockDisplay() {',
'  const [time, setTime] = useState(new Date().toLocaleTimeString());',
'  useEffect(() => { const id = setInterval(() => setTime(new Date().toLocaleTimeString()), 1000); return () => clearInterval(id); }, []);',
'  return <span className="font-mono text-xs">{time}</span>;',
'}',
].join('\n'), 'utf8');
console.log('  UPDATED src/App.tsx (polished UI with waveforms)');

console.log('\n  Done! Restart: npm run tauri:dev');
console.log('  New in v0.2.0:');
console.log('    - Waveform display on each deck');
console.log('    - Playhead position tracking on waveform');
console.log('    - Large time display (elapsed + remaining)');
console.log('    - Shuffle mode toggle');
console.log('    - Tighter, more professional layout');
console.log('    - Color-coded deck headers');
console.log('\n  Push to GitHub:');
console.log('    git add -A');
console.log('    git commit -m "v0.2.0 waveform UI + shuffle"');
console.log('    git push\n');
