const fs = require('fs');
const path = require('path');

// ============================================================
// 1. src/db/client.ts — Database wrapper
// ============================================================

const clientTs = [
  '// src/db/client.ts',
  '// Wrapper around tauri-plugin-sql for typed SQLite access.',
  '',
  'import Database from "@tauri-apps/plugin-sql";',
  '',
  'let db: Database | null = null;',
  '',
  'export async function getDb(): Promise<Database> {',
  '  if (!db) {',
  '    db = await Database.load("sqlite:openair.db");',
  '  }',
  '  return db;',
  '}',
  '',
  'export async function query<T>(sql: string, params: unknown[] = []): Promise<T[]> {',
  '  const d = await getDb();',
  '  return (await d.select(sql, params)) as T[];',
  '}',
  '',
  'export async function queryOne<T>(sql: string, params: unknown[] = []): Promise<T | null> {',
  '  const rows = await query<T>(sql, params);',
  '  return rows.length > 0 ? rows[0] : null;',
  '}',
  '',
  'export interface ExecuteResult {',
  '  rowsAffected: number;',
  '  lastInsertId: number;',
  '}',
  '',
  'export async function execute(sql: string, params: unknown[] = []): Promise<ExecuteResult> {',
  '  const d = await getDb();',
  '  const result = await d.execute(sql, params);',
  '  return {',
  '    rowsAffected: result.rowsAffected,',
  '    lastInsertId: result.lastInsertId,',
  '  };',
  '}',
  '',
  'export async function runMigrations(): Promise<void> {',
  '  const d = await getDb();',
  '  await d.execute("CREATE TABLE IF NOT EXISTS artists (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE, sort_name TEXT, created_at INTEGER NOT NULL DEFAULT (unixepoch()))");',
  '  await d.execute("CREATE TABLE IF NOT EXISTS albums (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, artist_id INTEGER REFERENCES artists(id), year INTEGER, created_at INTEGER NOT NULL DEFAULT (unixepoch()))");',
  '  await d.execute("CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT, code TEXT NOT NULL UNIQUE, name TEXT NOT NULL, color TEXT, description TEXT, target_spins_per_week INTEGER, created_at INTEGER NOT NULL DEFAULT (unixepoch()))");',
  '  await d.execute("CREATE TABLE IF NOT EXISTS songs (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, artist_id INTEGER REFERENCES artists(id), album_id INTEGER REFERENCES albums(id), file_path TEXT, file_format TEXT, file_size_bytes INTEGER, duration_ms INTEGER NOT NULL DEFAULT 0, intro_ms INTEGER NOT NULL DEFAULT 0, outro_ms INTEGER NOT NULL DEFAULT 0, genre TEXT, era TEXT, is_explicit INTEGER NOT NULL DEFAULT 0, is_instrumental INTEGER NOT NULL DEFAULT 0, category_id INTEGER REFERENCES categories(id), rotation_status TEXT NOT NULL DEFAULT \'active\', spins_total INTEGER NOT NULL DEFAULT 0, spins_this_week INTEGER NOT NULL DEFAULT 0, last_played_at INTEGER, last_played_hour INTEGER, no_repeat_hours INTEGER NOT NULL DEFAULT 2, no_artist_hours INTEGER NOT NULL DEFAULT 1, daypart_mask INTEGER NOT NULL DEFAULT 16777215, gender TEXT NOT NULL DEFAULT \'unknown\', tags TEXT NOT NULL DEFAULT \'[]\', notes TEXT, created_at INTEGER NOT NULL DEFAULT (unixepoch()), updated_at INTEGER NOT NULL DEFAULT (unixepoch()))");',
  '',
  '  const catCount = await d.select("SELECT COUNT(*) as c FROM categories");',
  '  if ((catCount as any)[0].c === 0) {',
  '    await d.execute("INSERT INTO categories (code, name, color) VALUES (\'A\', \'Power Current\', \'#ef4444\')");',
  '    await d.execute("INSERT INTO categories (code, name, color) VALUES (\'B\', \'Secondary\', \'#f59e0b\')");',
  '    await d.execute("INSERT INTO categories (code, name, color) VALUES (\'C\', \'Recurrent\', \'#22c55e\')");',
  '    await d.execute("INSERT INTO categories (code, name, color) VALUES (\'D\', \'Gold\', \'#3b82f6\')");',
  '    await d.execute("INSERT INTO categories (code, name, color) VALUES (\'PSA\', \'PSA\', \'#a855f7\')");',
  '  }',
  '  console.log("Migrations complete");',
  '}',
].join('\n');

fs.mkdirSync('src/db', { recursive: true });
fs.writeFileSync('src/db/client.ts', clientTs, 'utf8');
console.log('CREATED  src/db/client.ts');

// ============================================================
// 2. Fix index.html to add dark class
// ============================================================

const indexHtml = '<!DOCTYPE html>\n<html lang="en" class="dark">\n  <head>\n    <meta charset="UTF-8" />\n    <meta name="viewport" content="width=device-width, initial-scale=1.0" />\n    <title>OpenAir</title>\n  </head>\n  <body class="bg-zinc-950 text-zinc-100 overflow-hidden">\n    <div id="root"></div>\n    <script type="module" src="/src/main.tsx"><\/script>\n  </body>\n</html>';

fs.writeFileSync('index.html', indexHtml, 'utf8');
console.log('REPLACED index.html (added dark class)');

// ============================================================
// 3. Update main.tsx to run migrations on startup
// ============================================================

const mainTsx = [
  'import React from "react";',
  'import ReactDOM from "react-dom/client";',
  'import App from "./App";',
  'import "./index.css";',
  'import { runMigrations } from "./db/client";',
  '',
  'runMigrations().catch(console.error);',
  '',
  'ReactDOM.createRoot(document.getElementById("root")!).render(',
  '  <React.StrictMode>',
  '    <App />',
  '  </React.StrictMode>,',
  ');',
].join('\n');

fs.writeFileSync('src/main.tsx', mainTsx, 'utf8');
console.log('REPLACED src/main.tsx (added migrations)');

// ============================================================
// 4. Updated App.tsx with Library panel
// ============================================================

const appTsx = [
'import { useState, useEffect } from "react";',
'import { query, execute, queryOne } from "./db/client";',
'',
'type Panel = "live" | "library" | "clocks" | "logs" | "spots" | "settings";',
'',
'interface SongRow {',
'  id: number; title: string; artist_name: string | null;',
'  album_title: string | null; genre: string | null;',
'  duration_ms: number; category_code: string | null; category_color: string | null;',
'}',
'',
'export default function App() {',
'  const [activePanel, setActivePanel] = useState<Panel>("live");',
'  const [onAir, setOnAir] = useState(false);',
'  const onAirClass = onAir',
'    ? "ml-3 px-3 py-1 rounded text-xs font-bold uppercase tracking-wider bg-red-600 text-white animate-pulse"',
'    : "ml-3 px-3 py-1 rounded text-xs font-bold uppercase tracking-wider bg-zinc-700 text-zinc-400 hover:bg-zinc-600";',
'  return (',
'    <div className="h-screen flex flex-col bg-zinc-950 text-zinc-100">',
'      <header className="h-12 flex items-center justify-between px-4 bg-zinc-900 border-b border-zinc-800 shrink-0">',
'        <div className="flex items-center gap-3">',
'          <span className="text-lg font-bold tracking-tight"><span className="text-blue-400">Open</span>Air</span>',
'          <span className="text-xs text-zinc-500">v0.1.0</span>',
'        </div>',
'        <div className="flex items-center gap-2 text-sm text-zinc-400">',
'          <ClockDisplay />',
'          <button onClick={() => setOnAir(!onAir)} className={onAirClass}>{onAir ? "ON AIR" : "OFF AIR"}</button>',
'        </div>',
'      </header>',
'      <div className="flex flex-1 overflow-hidden">',
'        <Sidebar activePanel={activePanel} setPanel={setActivePanel} />',
'        <main className="flex-1 overflow-auto p-6">',
'          {activePanel === "live" && <LivePanel onAir={onAir} />}',
'          {activePanel === "library" && <LibraryPanel />}',
'          {activePanel === "clocks" && <P title="Clock Builder" d="Design hourly format clocks." />}',
'          {activePanel === "logs" && <P title="Log Builder" d="Generate and edit hourly playlists." />}',
'          {activePanel === "spots" && <P title="Spot Inventory" d="Manage commercials, PSAs, promos." />}',
'          {activePanel === "settings" && <P title="Settings" d="Station name, audio device, rules, theme." />}',
'        </main>',
'      </div>',
'      <footer className="h-7 flex items-center justify-between px-4 bg-zinc-900 border-t border-zinc-800 text-[11px] text-zinc-500 shrink-0">',
'        <span>Ready</span>',
'        <span>SQLite: connected | Audio: Web Audio API | Mode: Manual</span>',
'      </footer>',
'    </div>',
'  );',
'}',
'',
'function Sidebar({ activePanel, setPanel }: { activePanel: Panel; setPanel: (p: Panel) => void }) {',
'  const items: { id: Panel; label: string }[] = [',
'    { id: "live", label: "Live Assist" }, { id: "library", label: "Library" },',
'    { id: "clocks", label: "Clocks" }, { id: "logs", label: "Logs" },',
'    { id: "spots", label: "Spots" }, { id: "settings", label: "Settings" },',
'  ];',
'  return (',
'    <nav className="w-48 bg-zinc-900 border-r border-zinc-800 flex flex-col py-2 shrink-0">',
'      {items.map((item) => {',
'        const cls = activePanel === item.id',
'          ? "flex items-center gap-2 px-4 py-2.5 text-sm text-left bg-zinc-800 text-white border-l-2 border-blue-400"',
'          : "flex items-center gap-2 px-4 py-2.5 text-sm text-left text-zinc-400 hover:text-zinc-200 hover:bg-zinc-800 border-l-2 border-transparent";',
'        return <button key={item.id} onClick={() => setPanel(item.id)} className={cls}>{item.label}</button>;',
'      })}',
'      <div className="mt-auto px-4 py-3 text-[10px] text-zinc-600">OpenAir v0.1.0<br />MIT License</div>',
'    </nav>',
'  );',
'}',
'',
'function LibraryPanel() {',
'  const [songs, setSongs] = useState<SongRow[]>([]);',
'  const [loading, setLoading] = useState(true);',
'  const [search, setSearch] = useState("");',
'  const [count, setCount] = useState(0);',
'  const [showAdd, setShowAdd] = useState(false);',
'',
'  const load = async () => {',
'    try {',
'      const rows = await query<SongRow>("SELECT s.*, a.name as artist_name, al.title as album_title, c.code as category_code, c.color as category_color FROM songs s LEFT JOIN artists a ON a.id = s.artist_id LEFT JOIN albums al ON al.id = s.album_id LEFT JOIN categories c ON c.id = s.category_id ORDER BY s.title LIMIT 500");',
'      setSongs(rows);',
'      const r = await queryOne<{ c: number }>("SELECT COUNT(*) as c FROM songs");',
'      setCount(r ? r.c : 0);',
'    } catch (e) { console.error(e); }',
'    setLoading(false);',
'  };',
'',
'  useEffect(() => { load(); }, []);',
'',
'  const filtered = search ? songs.filter(s => (s.title || "").toLowerCase().includes(search.toLowerCase()) || (s.artist_name || "").toLowerCase().includes(search.toLowerCase())) : songs;',
'',
'  const fmt = (ms: number) => { const s = Math.floor(ms / 1000); return Math.floor(s / 60) + ":" + String(s % 60).padStart(2, "0"); };',
'',
'  return (',
'    <div className="space-y-4">',
'      <div className="flex items-center justify-between">',
'        <h1 className="text-xl font-bold">Song Library</h1>',
'        <span className="text-xs text-zinc-500">{count} tracks</span>',
'      </div>',
'      <div className="flex items-center gap-2">',
'        <input type="text" placeholder="Search by title or artist..." value={search} onChange={(e) => setSearch(e.target.value)} className="flex-1 px-3 py-2 bg-zinc-800 border border-zinc-700 rounded text-sm text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-blue-500" />',
'        <button onClick={() => setShowAdd(!showAdd)} className="px-4 py-2 bg-blue-600 hover:bg-blue-500 rounded text-sm font-medium text-white">+ Add Song</button>',
'      </div>',
'      {showAdd && <AddSong onDone={() => { setShowAdd(false); load(); }} />}',
'      {loading ? <div className="text-sm text-zinc-500">Loading...</div> : filtered.length === 0 ? (',
'        <div className="text-center py-12"><div className="text-zinc-500 text-sm">No songs in library yet.</div><div className="text-zinc-600 text-xs mt-2">Click + Add Song to add your first track.</div></div>',
'      ) : (',
'        <div className="bg-zinc-900 rounded-lg border border-zinc-800 overflow-hidden">',
'          <table className="w-full text-sm">',
'            <thead><tr className="text-left text-xs text-zinc-500 uppercase border-b border-zinc-800">',
'              <th className="px-4 py-2">Title</th><th className="px-4 py-2">Artist</th><th className="px-4 py-2">Album</th><th className="px-4 py-2">Genre</th><th className="px-4 py-2">Cat</th><th className="px-4 py-2 text-right">Duration</th>',
'            </tr></thead>',
'            <tbody>{filtered.map((s) => (',
'              <tr key={s.id} className="border-b border-zinc-800 hover:bg-zinc-800 cursor-pointer">',
'                <td className="px-4 py-2 text-zinc-100">{s.title}</td>',
'                <td className="px-4 py-2 text-zinc-400">{s.artist_name || "\\u2014"}</td>',
'                <td className="px-4 py-2 text-zinc-400">{s.album_title || "\\u2014"}</td>',
'                <td className="px-4 py-2 text-zinc-500">{s.genre || "\\u2014"}</td>',
'                <td className="px-4 py-2">{s.category_code ? <span className="px-1.5 py-0.5 rounded text-xs font-bold" style={{ backgroundColor: s.category_color || "#555", color: "white" }}>{s.category_code}</span> : "\\u2014"}</td>',
'                <td className="px-4 py-2 text-right text-zinc-500 font-mono text-xs">{fmt(s.duration_ms)}</td>',
'              </tr>',
'            ))}</tbody>',
'          </table>',
'        </div>',
'      )}',
'    </div>',
'  );',
'}',
'',
'function AddSong({ onDone }: { onDone: () => void }) {',
'  const [title, setTitle] = useState(""); const [artist, setArtist] = useState("");',
'  const [album, setAlbum] = useState(""); const [genre, setGenre] = useState("");',
'  const [dur, setDur] = useState(""); const [saving, setSaving] = useState(false);',
'  const save = async () => {',
'    if (!title.trim()) return; setSaving(true);',
'    try {',
'      let aid: number | null = null;',
'      if (artist.trim()) {',
'        const ex = await queryOne<{ id: number }>("SELECT id FROM artists WHERE name = ?", [artist.trim()]);',
'        if (ex) { aid = ex.id; } else {',
'          const r = await execute("INSERT INTO artists (name) VALUES (?)", [artist.trim()]);',
'          aid = r.lastInsertId;',
'        }',
'      }',
'      let bid: number | null = null;',
'      if (album.trim()) {',
'        const ex = await queryOne<{ id: number }>("SELECT id FROM albums WHERE title = ?", [album.trim()]);',
'        if (ex) { bid = ex.id; } else {',
'          const r = await execute("INSERT INTO albums (title, artist_id) VALUES (?, ?)", [album.trim(), aid]);',
'          bid = r.lastInsertId;',
'        }',
'      }',
'      await execute("INSERT INTO songs (title, artist_id, album_id, genre, duration_ms, daypart_mask) VALUES (?, ?, ?, ?, ?, ?)", [title.trim(), aid, bid, genre.trim() || null, parseInt(dur || "0") * 1000, 16777215]);',
'      onDone();',
'    } catch (e) { console.error(e); alert("Error: " + e); }',
'    setSaving(false);',
'  };',
'  const ic = "w-full px-3 py-2 bg-zinc-800 border border-zinc-700 rounded text-sm text-zinc-100 placeholder-zinc-500 focus:outline-none focus:border-blue-500";',
'  return (',
'    <div className="bg-zinc-900 border border-zinc-800 rounded-lg p-4 space-y-3">',
'      <h3 className="text-sm font-bold text-zinc-300">Add Song Manually</h3>',
'      <div className="grid grid-cols-2 gap-3">',
'        <input className={ic} placeholder="Title *" value={title} onChange={(e) => setTitle(e.target.value)} />',
'        <input className={ic} placeholder="Artist" value={artist} onChange={(e) => setArtist(e.target.value)} />',
'        <input className={ic} placeholder="Album" value={album} onChange={(e) => setAlbum(e.target.value)} />',
'        <input className={ic} placeholder="Genre" value={genre} onChange={(e) => setGenre(e.target.value)} />',
'        <input className={ic} placeholder="Duration (seconds)" value={dur} onChange={(e) => setDur(e.target.value)} type="number" />',
'      </div>',
'      <div className="flex gap-2">',
'        <button onClick={save} disabled={saving || !title.trim()} className="px-4 py-2 bg-blue-600 hover:bg-blue-500 disabled:opacity-50 rounded text-sm font-medium text-white">{saving ? "Saving..." : "Save"}</button>',
'        <button onClick={onDone} className="px-4 py-2 bg-zinc-700 hover:bg-zinc-600 rounded text-sm text-zinc-300">Cancel</button>',
'      </div>',
'    </div>',
'  );',
'}',
'',
'function LivePanel({ onAir }: { onAir: boolean }) {',
'  return (',
'    <div className="space-y-4">',
'      <h1 className="text-xl font-bold">Live Assist</h1>',
'      <div className="grid grid-cols-2 gap-4">',
'        <DeckCard name="Deck A" color="text-blue-400" active={onAir} />',
'        <DeckCard name="Deck B" color="text-emerald-400" active={false} />',
'      </div>',
'      <div className="bg-zinc-900 rounded-lg p-4 border border-zinc-800">',
'        <h2 className="text-xs font-bold text-zinc-400 uppercase mb-3">Up Next</h2>',
'        <div className="text-sm text-zinc-500 italic">No log loaded.</div>',
'      </div>',
'      <div className="bg-zinc-900 rounded-lg p-4 border border-zinc-800">',
'        <h2 className="text-xs font-bold text-zinc-400 uppercase mb-3">Cart Wall</h2>',
'        <div className="grid grid-cols-8 gap-1.5">',
'          {Array.from({ length: 32 }, (_, i) => (',
'            <button key={i} className="aspect-square rounded bg-zinc-800 hover:bg-zinc-700 text-[10px] text-zinc-600 flex items-center justify-center">{i < 12 ? "F" + (i + 1) : ""}</button>',
'          ))}',
'        </div>',
'      </div>',
'    </div>',
'  );',
'}',
'',
'function DeckCard({ name, color, active }: { name: string; color: string; active: boolean }) {',
'  const pc = active ? "px-4 py-1.5 rounded text-xs font-bold flex-1 bg-red-600 text-white" : "px-4 py-1.5 rounded text-xs font-bold flex-1 bg-emerald-700 hover:bg-emerald-600 text-white";',
'  return (',
'    <div className="bg-zinc-900 rounded-lg p-4 border border-zinc-800">',
'      <div className="flex items-center justify-between mb-3">',
'        <span className={"text-xs font-bold uppercase tracking-wider " + color}>{name}</span>',
'        <span className="text-[10px] text-zinc-500 uppercase">Idle</span>',
'      </div>',
'      <div className="h-20 bg-zinc-800 rounded flex items-center justify-center"><span className="text-zinc-600 text-xs">No track loaded</span></div>',
'      <div className="flex justify-between text-xs font-mono text-zinc-500 mt-3"><span>00:00.0</span><span>-00:00.0</span></div>',
'      <div className="flex items-center gap-2 mt-3">',
'        <button className="px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 rounded text-xs">Cue</button>',
'        <button className={pc}>{active ? "Stop" : "Play"}</button>',
'        <button className="px-3 py-1.5 bg-zinc-800 hover:bg-zinc-700 rounded text-xs">Next</button>',
'      </div>',
'      <div className="flex items-center gap-2 text-xs text-zinc-500 mt-3"><span>Vol</span><div className="flex-1 h-1.5 bg-zinc-800 rounded-full overflow-hidden"><div className="h-full w-4/5 bg-zinc-600 rounded-full"></div></div><span>80%</span></div>',
'    </div>',
'  );',
'}',
'',
'function P({ title, d }: { title: string; d: string }) {',
'  return <div className="flex flex-col items-center justify-center h-full text-center"><h1 className="text-xl font-bold mb-2">{title}</h1><p className="text-sm text-zinc-400 max-w-md">{d}</p><p className="text-xs text-zinc-600 mt-4">Coming soon</p></div>;',
'}',
'',
'function ClockDisplay() {',
'  const [time, setTime] = useState(new Date().toLocaleTimeString());',
'  useEffect(() => { const id = setInterval(() => setTime(new Date().toLocaleTimeString()), 1000); return () => clearInterval(id); }, []);',
'  return <span className="font-mono text-xs">{time}</span>;',
'}',
].join('\n');

fs.writeFileSync('src/App.tsx', appTsx, 'utf8');
console.log('REPLACED src/App.tsx (added Library panel with Add Song)');

console.log('\nDone! Run: npm run tauri:dev');
console.log('Click "Library" in the sidebar, then "+ Add Song" to test.');
