'use strict';

// electron/sync/handlers/{{TABLE_NAME}}.js — generated by scripts/generate-handlers.js
// IPC handlers for the {{TABLE_NAME}} table ({{SCOPE}}-scoped).
// Channels: {{TABLE_NAME}}:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.{{CAMEL_NAME}}.*
//
// Install-scoped: data is shared across all stations. No station_id filtering
// on list. withMutation receives station_id: null per [N-89].

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE    = '{{TABLE_NAME}}';
const PATCHABLE = {{PATCHABLE_COLS_JSON}};

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[{{TABLE_NAME}}] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== '{{SCOPE}}') {
    throw new Error(`[{{TABLE_NAME}}] expected {{SCOPE}}-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function {{CAMEL_NAME}}List(db, opts) {
  const { limit = 500, offset = 0 } = opts || {};
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL ORDER BY rowid LIMIT ? OFFSET ?`
  ).all(limit, offset);
}

function {{CAMEL_NAME}}Get(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function {{CAMEL_NAME}}Create(db, payload) {
  validateScope();
  if (payload.station_id != null) {
    throw new Error(`[{{TABLE_NAME}}] station_id must not be set on install-scoped create (got ${payload.station_id})`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     {{MUT_SID_CREATE}},
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} ({{INSERT_COLS}}) VALUES ({{INSERT_PLACEHOLDERS}})`
    ).run({{INSERT_ROW_BINDINGS}});
  });
  return {{CAMEL_NAME}}Get(db, uuid);
}

function {{CAMEL_NAME}}Update(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[{{TABLE_NAME}}] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[{{TABLE_NAME}}] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[{{TABLE_NAME}}] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     {{MUT_SID_UPDATE}},
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return {{CAMEL_NAME}}Get(db, uuid);
}

function {{CAMEL_NAME}}Delete(db, uuid) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[{{TABLE_NAME}}] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     {{MUT_SID_DELETE}},
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}

// ── IPC installation ──────────────────────────────────────────────────────────

function {{INSTALL_FN}}(ipcMain, db) {
  // Resolve the LIVE connection at call time. `db` may be a Database OR a () => Database getter
  // (main.js passes getDb). After a restore/self-heal reopen the handle changes, so capturing it by
  // value would orphan these handlers on a dead connection ("database connection is not open"). The
  // business-logic fns still take a raw db param (the proofs call them directly) — only the resolution
  // site changes.
  const getDb = (typeof db === 'function') ? db : () => db;
  ipcMain.handle('{{TABLE_NAME}}:list', (_, opts) => {
    try { return { ok: true, rows: {{CAMEL_NAME}}List(getDb(), opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('{{TABLE_NAME}}:get-by-id', (_, uuid) => {
    try { return { ok: true, row: {{CAMEL_NAME}}Get(getDb(), uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('{{TABLE_NAME}}:create', (_, payload) => {
    try { return { ok: true, row: {{CAMEL_NAME}}Create(getDb(), payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('{{TABLE_NAME}}:update', (_, uuid, patch) => {
    try { return { ok: true, row: {{CAMEL_NAME}}Update(getDb(), uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('{{TABLE_NAME}}:delete', (_, uuid) => {
    try { return { ok: true, ...{{CAMEL_NAME}}Delete(getDb(), uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[{{TABLE_NAME}}] handlers installed');
}

module.exports = {
  {{INSTALL_FN}},
  validateScope,
  {{CAMEL_NAME}}List,
  {{CAMEL_NAME}}Get,
  {{CAMEL_NAME}}Create,
  {{CAMEL_NAME}}Update,
  {{CAMEL_NAME}}Delete,
};
