'use strict';

// electron/sync/handlers/{{TABLE_NAME}}.js — generated by scripts/generate-handlers.js
// IPC handlers for the {{TABLE_NAME}} table ({{SCOPE}}-scoped).
// Channels: {{TABLE_NAME}}:list | :get-by-id | :create | :update | :delete
// Preload:  window.ether.{{CAMEL_NAME}}.*
//
// All writes go through withMutation so every CRUD operation is logged to the
// mutations table for future sync.

const crypto = require('crypto');
const { withMutation, serializePayload } = require('../mutation-writer');
const { REGISTRY } = require('../synced-tables');

const TABLE              = '{{TABLE_NAME}}';
const HAS_STATION_ID_COL = {{HAS_STATION_ID_COL}};
const PATCHABLE          = {{PATCHABLE_COLS_JSON}};

// ── Scope guard ───────────────────────────────────────────────────────────────

function validateScope() {
  const entry = REGISTRY[TABLE];
  if (!entry) throw new Error(`[{{TABLE_NAME}}] unknown table in registry: "${TABLE}"`);
  if (entry.scope !== '{{SCOPE}}') {
    throw new Error(`[{{TABLE_NAME}}] expected {{SCOPE}}-scoped table, registry has "${entry.scope}"`);
  }
}

// ── Business logic ────────────────────────────────────────────────────────────

function {{CAMEL_NAME}}List(db, stationId, opts) {
  let sql    = `SELECT * FROM ${TABLE} WHERE deleted_at IS NULL`;
  const params = [];
  if (HAS_STATION_ID_COL && stationId != null) {
    sql += ' AND station_id = ?';
    params.push(stationId);
  }
  const { limit = 500, offset = 0 } = opts || {};
  sql += ' ORDER BY rowid LIMIT ? OFFSET ?';
  params.push(limit, offset);
  return db.prepare(sql).all(...params);
}

function {{CAMEL_NAME}}Get(db, uuid) {
  return db.prepare(
    `SELECT * FROM ${TABLE} WHERE uuid = ? AND deleted_at IS NULL`
  ).get(uuid) ?? null;
}

function {{CAMEL_NAME}}Create(db, payload) {
  validateScope();
  if (HAS_STATION_ID_COL && payload.station_id == null) {
    throw new Error(`[{{TABLE_NAME}}] station_id is required for {{SCOPE}}-scoped create`);
  }
  const now  = new Date().toISOString();
  const uuid = payload.uuid ?? crypto.randomUUID();
  const row  = {
    ...payload,
    uuid,
    created_at: now,
    updated_at: now,
    deleted_at: payload.deleted_at ?? null,
  };
  const payloadAfter = serializePayload(row, TABLE);
  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'insert',
    payload_before: null,
    payload_after:  payloadAfter,
    station_id:     {{MUT_SID_CREATE}},
    actor_id:       payload.actor_id ?? null,
  }, () => {
    db.prepare(
      `INSERT INTO ${TABLE} ({{INSERT_COLS}}) VALUES ({{INSERT_PLACEHOLDERS}})`
    ).run({{INSERT_ROW_BINDINGS}});
  });
  return {{CAMEL_NAME}}Get(db, uuid);
}

function {{CAMEL_NAME}}Update(db, uuid, patch) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[{{TABLE_NAME}}] row not found: ${uuid}`);

  const forbidden = Object.keys(patch).filter(k => k !== 'actor_id' && !PATCHABLE.includes(k));
  if (forbidden.length > 0) {
    throw new Error(`[{{TABLE_NAME}}] cannot patch immutable field(s): ${forbidden.join(', ')}`);
  }

  const patchFields = PATCHABLE.filter(k => k in patch);
  if (patchFields.length === 0) {
    throw new Error(`[{{TABLE_NAME}}] no patchable fields provided in patch`);
  }

  const now     = new Date().toISOString();
  const updated = { ...existing, updated_at: now };
  for (const k of patchFields) updated[k] = patch[k];

  const before = serializePayload(existing, TABLE);
  const after  = serializePayload(updated,  TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'update',
    payload_before: before,
    payload_after:  after,
    station_id:     {{MUT_SID_UPDATE}},
    actor_id:       patch.actor_id ?? null,
  }, () => {
    const sets = patchFields.map(k => `${k} = ?`).join(', ');
    const vals = patchFields.map(k => patch[k]);
    db.prepare(`UPDATE ${TABLE} SET ${sets}, updated_at = ? WHERE uuid = ?`).run(...vals, now, uuid);
  });
  return {{CAMEL_NAME}}Get(db, uuid);
}

function {{CAMEL_NAME}}Delete(db, uuid, stationId) {
  validateScope();
  const existing = db.prepare(`SELECT * FROM ${TABLE} WHERE uuid = ?`).get(uuid);
  if (!existing) throw new Error(`[{{TABLE_NAME}}] row not found: ${uuid}`);

  const before = serializePayload(existing, TABLE);

  withMutation(db, {
    table_name:     TABLE,
    row_id:         uuid,
    op:             'delete',
    payload_before: before,
    payload_after:  null,
    station_id:     {{MUT_SID_DELETE}},
    actor_id:       null,
  }, () => {
    const now = new Date().toISOString();
    db.prepare(
      `UPDATE ${TABLE} SET deleted_at = ?, updated_at = ? WHERE uuid = ?`
    ).run(now, now, uuid);
  });
  return { ok: true };
}

// ── IPC installation ──────────────────────────────────────────────────────────

function {{INSTALL_FN}}(ipcMain, db) {
  ipcMain.handle('{{TABLE_NAME}}:list', (_, stationId, opts) => {
    try { return { ok: true, rows: {{CAMEL_NAME}}List(db, stationId, opts) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('{{TABLE_NAME}}:get-by-id', (_, uuid) => {
    try { return { ok: true, row: {{CAMEL_NAME}}Get(db, uuid) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('{{TABLE_NAME}}:create', (_, payload) => {
    try { return { ok: true, row: {{CAMEL_NAME}}Create(db, payload) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('{{TABLE_NAME}}:update', (_, uuid, patch) => {
    try { return { ok: true, row: {{CAMEL_NAME}}Update(db, uuid, patch) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  ipcMain.handle('{{TABLE_NAME}}:delete', (_, uuid, stationId) => {
    try { return { ok: true, ...{{CAMEL_NAME}}Delete(db, uuid, stationId) }; }
    catch (e) { return { ok: false, error: e.message }; }
  });

  console.log('[{{TABLE_NAME}}] handlers installed');
}

module.exports = {
  {{INSTALL_FN}},
  validateScope,
  {{CAMEL_NAME}}List,
  {{CAMEL_NAME}}Get,
  {{CAMEL_NAME}}Create,
  {{CAMEL_NAME}}Update,
  {{CAMEL_NAME}}Delete,
};
