'use strict';

// electron/sync/handlers/index.js — generated by scripts/generate-handlers.js
// Aggregator: installs all 31 typed IPC handler sets (station_programming hand-written
// + 30 generated) in one call. main.js calls installAll(ipcMain, db).

const { installStationProgramming } = require('./station_programming');
{{REQUIRE_LINES}}

function installAll(ipcMain, db) {
  installStationProgramming(ipcMain, db);
{{INSTALL_LINES}}
}

module.exports = { installAll };
