'use strict';

// electron/preload-handlers.js — generated by scripts/generate-handlers.js
// Factory: call with ipcRenderer, returns all 31 sync handler namespaces.
// Usage in preload.js:
//   const handlers = require('./preload-handlers')(ipcRenderer);
//   contextBridge.exposeInMainWorld('ether', { ...existingNamespaces, ...handlers });

module.exports = function buildHandlers(ipcRenderer) {
  return {
    stationProgramming: {
      list:    (stationId, opts)  => ipcRenderer.invoke('station_programming:list',      stationId, opts),
      getById: (uuid)             => ipcRenderer.invoke('station_programming:get-by-id', uuid),
      create:  (payload)          => ipcRenderer.invoke('station_programming:create',    payload),
      update:  (uuid, patch)      => ipcRenderer.invoke('station_programming:update',    uuid, patch),
      delete:  (uuid, stationId)  => ipcRenderer.invoke('station_programming:delete',    uuid, stationId),
    },
{{NAMESPACE_BLOCKS}}
  };
};
