// ── SLICE 5 — the channel rack's DSP on the audio thread (docs/dsp-channel-rack-eq.md §1.3) ─────────────────
//
// What runs here is ONLY biquads: the coefficients arrive precomputed (rack.rs ChainSpec, f64, computed on the
// dispatch thread). One ChannelDsp per fader, preallocated in BusState: no heap, no lock, no trigonometry.
//
// SMOOTHING — no zipper noise. Any change to what a channel runs (a coefficient, a band, IN ↔ OUT) is a new
// chain; the callback runs the OLD and the NEW chains on the same input for EQ_XFADE_MS and crossfades their
// outputs per sample on a RAISED-COSINE curve, whose slope is zero at both ends of the fade (a linear fade — the
// proposal's word — has a slope jump at each end). Generated by a rotating phasor: no trig per sample. IN ↔ OUT is
// the same mechanism with an empty chain on one side (a dry/wet fade).
// A change arriving DURING a fade is held, and the latest is applied when the fade ends — ≤ 20 ms more latency
// on a drag, never a jump. Proven by `a_band_gain_step_does_not_click` and its deliberate-failure twin.
//
// f64 STATE (Jeff's ruling 3): a 16 Hz HPF at 44.1 kHz puts its poles ~0.002 from the unit circle; f32 there
// drifts and adds noise on the very rumble it removes. Denormals: the callback runs under FtzScope (Slice 1).

use crate::rack::{ChainSpec, CHAIN_MAX, DynCoef, KIND_BQ, KIND_COMP, DYN_BLOCK, comp_gr_db, gate_gr_db};

// TEST-ONLY attribution (Jeff, 2026-09-26): the time spent in ChannelDsp::process on this thread, so the timing
// test can tell the channel-rack work apart from everything else in a slow buffer. Not compiled into the product.
#[cfg(test)]
thread_local! {
    pub(crate) static RACK_NS: std::cell::Cell<u64> = const { std::cell::Cell::new(0) };
    /// Thread CPU CYCLES spent in process (QueryThreadCycleTime: only cycles this thread ran — a preemption
    /// adds wall time, not cycles). GetThreadTimes updates on the ~15.6 ms scheduler tick, too coarse per buffer.
    pub(crate) static RACK_CYC: std::cell::Cell<u64> = const { std::cell::Cell::new(0) };
    /// Per-call wall ns in call order within a buffer (= channel order: the deck loop is sequential).
    pub(crate) static RACK_CALLS: std::cell::RefCell<[u64; 12]> = const { std::cell::RefCell::new([0; 12]) };
    pub(crate) static RACK_NCALLS: std::cell::Cell<usize> = const { std::cell::Cell::new(0) };
}
#[cfg(all(test, windows))]
pub(crate) fn thread_cycles() -> u64 {
    extern "system" {
        fn GetCurrentThread() -> *mut core::ffi::c_void;
        fn QueryThreadCycleTime(h: *mut core::ffi::c_void, cycles: *mut u64) -> i32;
    }
    let mut c = 0u64;
    unsafe { QueryThreadCycleTime(GetCurrentThread(), &mut c); }
    c
}
#[cfg(all(test, not(windows)))]
pub(crate) fn thread_cycles() -> u64 { 0 }

/// The crossfade, in ms and in program-rate frames (Jeff's ruling 2: 20 ms).
pub const EQ_XFADE_MS: f64 = 20.0;
pub const EQ_XFADE_FRAMES: usize = (44_100.0 * EQ_XFADE_MS / 1000.0) as usize;   // 882

/// One stage's state. A biquad uses s1/s2; a dynamics block (SLICE 6) uses the rest: `det` the detector (mean-square
/// for the compressor, a peak envelope for the gate), `gr` the smoothed gain reduction (dB), `g0 → g1` the linear gain
/// interpolated across the current control block, `grmax` the largest GR since the meter last took it, `k` the sample
/// within the block, and the gate's open/hold. Seeded across a crossfade by stage id like a biquad's.
#[derive(Clone, Copy)]
struct St { s1: [f64; 2], s2: [f64; 2], det: f64, gr: f64, g0: f64, g1: f64, grmax: f64, k: u32, open: bool, hold: u32 }
impl Default for St {
    fn default() -> Self { St { s1: [0.0; 2], s2: [0.0; 2], det: 0.0, gr: 0.0, g0: 1.0, g1: 1.0, grmax: 0.0, k: 0, open: false, hold: 0 } }
}

/// One sample through a dynamics stage. The detector runs every sample; the gain computer every DYN_BLOCK samples
/// (ruling 3), and the linear gain is interpolated between. Linked stereo: one gain for both channels.
#[inline(always)]
fn dyn_step(c: &DynCoef, kind: u8, s: &mut St, x: [f64; 2]) -> [f64; 2] {
    if kind == KIND_COMP {
        let p = 0.5 * (x[0] * x[0] + x[1] * x[1]);            // RMS detector (ruling 1): a one-pole mean square
        s.det += c.det_a * (p - s.det);
    } else {
        let e = x[0].abs().max(x[1].abs());                     // the gate: a fast peak envelope
        s.det += (if e > s.det { c.det_a } else { c.det_d }) * (e - s.det);
    }
    s.k += 1;
    let g = s.g0 + (s.g1 - s.g0) * (s.k as f64 / DYN_BLOCK as f64);
    if s.k == DYN_BLOCK { s.k = 0; dyn_control(c, kind, s); }
    [x[0] * g, x[1] * g]
}
#[inline(always)]
fn dyn_control(c: &DynCoef, kind: u8, s: &mut St) {
    let (target, rising_is_attack, makeup) = if kind == KIND_COMP {
        let lvl = 10.0 * s.det.max(1e-20).log10();
        (comp_gr_db(lvl, c.thr, c.ratio, c.knee), true, c.makeup)
    } else {
        let lvl = 20.0 * s.det.max(1e-10).log10();
        // HYSTERESIS + HOLD: open at the threshold; close only after falling below (threshold − hysteresis) for
        // the hold time — so a level hovering at the threshold does not chatter.
        if lvl >= c.thr { s.open = true; s.hold = c.hold_blocks; }
        else if s.open {
            if lvl < c.thr - c.hyst { if s.hold == 0 { s.open = false; } else { s.hold -= 1; } }
            else { s.hold = c.hold_blocks; }
        }
        (if s.open { 0.0 } else { gate_gr_db(lvl, c.thr, c.ratio, c.depth) }, false, 0.0)
    };
    // compressor: GR rising = attack. gate: GR falling = OPENING = its attack; rising = closing = its release.
    let a = if (target > s.gr) == rising_is_attack { c.atk } else { c.rel };
    s.gr += a * (target - s.gr);
    if s.gr > s.grmax { s.grmax = s.gr; }
    s.g0 = s.g1;
    s.g1 = 10f64.powf((makeup - s.gr) / 20.0);
}

#[derive(Clone, Copy)]
pub struct ChannelDsp {
    cur: ChainSpec,
    cur_st: [St; CHAIN_MAX],
    old: ChainSpec,
    old_st: [St; CHAIN_MAX],
    /// Frames of crossfade remaining (0 = not fading).
    fade: usize,
    fade_len: usize,
    pending: Option<ChainSpec>,
    /// The raised-cosine phasor: (cos θ, sin θ), rotated by (rc, rs) each sample; old's weight = (1 + cos θ)/2.
    ph: (f64, f64),
    rot: (f64, f64),
    /// During a fade: how many LEADING stages the old and new chains share exactly (same id, same coefficients).
    /// Their state is identical (the new chain is seeded from the old), so they are computed ONCE and feed both
    /// remainders — exact, not an approximation. Editing a PEQ band leaves the HPF/LPF in front unduplicated.
    shared: usize,
    /// TEST-ONLY: turn the shared front off (the reference the sharing is proven bit-identical against).
    #[cfg(test)]
    pub(crate) no_share: bool,
}
impl Default for ChannelDsp { fn default() -> Self { ChannelDsp::with_fade(EQ_XFADE_FRAMES) } }

#[inline(always)]
fn run(spec: &ChainSpec, st: &mut [St; CHAIN_MAX], x: [f64; 2]) -> [f64; 2] { run_from(spec, st, 0, spec.n, x) }

#[inline(always)]
fn run_from(spec: &ChainSpec, st: &mut [St; CHAIN_MAX], from: usize, to: usize, mut x: [f64; 2]) -> [f64; 2] {
    for k in from..to {
        if spec.kind[k] != KIND_BQ { x = dyn_step(&spec.dy[k], spec.kind[k], &mut st[k], x); continue; }
        let b = &spec.bq[k];
        let s = &mut st[k];
        for c in 0..2 {
            // transposed direct form II
            let y = b.b0 * x[c] + s.s1[c];
            s.s1[c] = b.b1 * x[c] - b.a1 * y + s.s2[c];
            s.s2[c] = b.b2 * x[c] - b.a2 * y;
            x[c] = y;
        }
    }
    x
}

impl ChannelDsp {
    /// `fade_len` = crossfade frames. The product uses EQ_XFADE_FRAMES; the no-click test's twin uses 0 (a hard
    /// switch) to prove the test can see a click.
    pub fn with_fade(fade_len: usize) -> ChannelDsp {
        // θ runs 0 → π over the fade (computed here, off the audio thread).
        let d = std::f64::consts::PI / (fade_len as f64 + 1.0);
        ChannelDsp { cur: ChainSpec::default(), cur_st: [St::default(); CHAIN_MAX], old: ChainSpec::default(),
                     old_st: [St::default(); CHAIN_MAX], fade: 0, fade_len, pending: None,
                     ph: (1.0, 0.0), rot: (d.cos(), d.sin()), shared: 0,
                     #[cfg(test)] no_share: false }
    }
    /// Does this channel need the rack path this buffer? (Nothing IN and no fade = the caller keeps today's
    /// exact arithmetic.)
    #[inline]
    pub fn active(&self) -> bool { self.cur.n > 0 || self.fade > 0 }

    /// A new chain from the Params block. Mid-fade it is held (the latest wins) until the fade ends.
    pub fn set(&mut self, spec: ChainSpec) {
        if self.fade > 0 { self.pending = Some(spec); } else { self.start(spec); }
    }
    fn start(&mut self, spec: ChainSpec) {
        if spec == self.cur { return; }
        self.old = self.cur;
        self.old_st = self.cur_st;
        // Seed the new chain's state from the old one stage-by-stage (same stage id), so a coefficient change
        // continues from where the filter was rather than from rest.
        let mut st = [St::default(); CHAIN_MAX];
        for k in 0..spec.n {
            if let Some(j) = (0..self.old.n).find(|&j| self.old.id[j] == spec.id[k]) { st[k] = self.old_st[j]; }
        }
        self.cur = spec;
        self.cur_st = st;
        self.fade = if self.old.n == 0 && spec.n == 0 { 0 } else { self.fade_len };
        self.ph = (1.0, 0.0);
        self.shared = (0..self.old.n.min(spec.n)).take_while(|&k| self.old.id[k] == spec.id[k] && self.old.kind[k] == spec.kind[k]
            && self.old.bq[k] == spec.bq[k] && self.old.dy[k] == spec.dy[k]).count();
        #[cfg(test)]
        if self.no_share { self.shared = 0; }
    }

    /// SLICE 6 — the meter's take: (gate GR max, comp GR max, gate open) since the last take, from the RUNNING chain
    /// (the new one during a fade). No dynamics stage → (0, 0, true). Allocation-free.
    #[inline]
    pub fn take_gr(&mut self) -> (f32, f32, bool) {
        let (mut g, mut c, mut open) = (0.0f64, 0.0f64, true);
        for k in 0..self.cur.n {
            let kind = self.cur.kind[k];
            if kind == KIND_BQ { continue; }
            let s = &mut self.cur_st[k];
            if kind == KIND_COMP { c = s.grmax; } else { g = s.grmax; open = s.open; }
            s.grmax = s.gr;
        }
        (g as f32, c as f32, open)
    }

    /// Process a channel's lanes in place (post-trim, pre-fader).
    #[inline]
    pub fn process(&mut self, l: &mut [f32], r: &mut [f32]) {
        #[cfg(test)]
        let (t0, c0) = (std::time::Instant::now(), thread_cycles());
        self.process_inner(l, r);
        #[cfg(test)]
        {
            let ns = t0.elapsed().as_nanos() as u64;
            RACK_NS.with(|c| c.set(c.get() + ns));
            RACK_CYC.with(|c| c.set(c.get() + thread_cycles().saturating_sub(c0)));
            RACK_NCALLS.with(|n| { let k = n.get(); if k < 12 { RACK_CALLS.with(|a| a.borrow_mut()[k] = ns); } n.set(k + 1); });
        }
    }
    #[inline(always)]
    fn process_inner(&mut self, l: &mut [f32], r: &mut [f32]) {
        let n = l.len().min(r.len());
        for i in 0..n {
            let x = [l[i] as f64, r[i] as f64];
            let y = if self.fade > 0 {
                // the shared front once, then each chain's own remainder from its output
                let p = run_from(&self.cur, &mut self.cur_st, 0, self.shared, x);
                let yn = run_from(&self.cur, &mut self.cur_st, self.shared, self.cur.n, p);
                let yo = run_from(&self.old, &mut self.old_st, self.shared, self.old.n, p);
                // advance θ, then old's weight = (1 + cos θ)/2: 1 → 0 with zero slope at both ends
                let (c, sn) = self.ph;
                self.ph = (c * self.rot.0 - sn * self.rot.1, sn * self.rot.0 + c * self.rot.1);
                let w = 0.5 * (1.0 + self.ph.0);
                self.fade -= 1;
                if self.fade == 0 { if let Some(p) = self.pending.take() { self.start(p); } }
                [yo[0] * w + yn[0] * (1.0 - w), yo[1] * w + yn[1] * (1.0 - w)]
            } else { run(&self.cur, &mut self.cur_st, x) };
            l[i] = y[0] as f32;
            r[i] = y[1] as f32;
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::rack::{ChannelRack, rbj_pass};

    const FS: f64 = 44_100.0;

    fn peq_rack(gain: f32, on: bool) -> ChannelRack {
        ChannelRack::from_doc_json(&format!(r#"{{"v":1,"sections":{{"ch":[{{"module":{{"type":"peq","bands":[
            {{"freq":100,"gain":0,"width":1}},{{"freq":1000,"gain":{gain},"width":1}},
            {{"freq":3000,"gain":0,"width":1}},{{"freq":8000,"gain":0,"width":1}}]}},"in":{on}}}]}}}}"#)).unwrap()
    }

    /// 8th-order high-pass at 8 kHz (four 2nd-order Butterworth-ish sections): removes the 1 kHz tone by
    /// ~144 dB so what is left is a discontinuity's broadband energy. (A 4th order leaves the −12 dBFS tone at
    /// about −84 dBFS — right at the bar — so it would measure the tone, not a click.)
    fn hp8(x: &[f32]) -> Vec<f64> {
        let q = [0.5098, 0.6013, 0.9000, 2.5629];   // 8th-order Butterworth section Qs
        let mut st = [[0.0f64; 2]; 4];
        x.iter().map(|&v| {
            let mut y = v as f64;
            for (k, qq) in q.iter().enumerate() {
                let b = rbj_pass(8_000.0, *qq, FS, true);
                let o = b.b0 * y + st[k][0];
                st[k][0] = b.b1 * y - b.a1 * o + st[k][1];
                st[k][1] = b.b2 * y - b.a2 * o;
                y = o;
            }
            y
        }).collect()
    }

    /// The 1 kHz test tone, synthesized in f64. (Generating it in f32 — `sin(2π·1000·i/fs)` at large i — gave the
    /// INPUT broadband phase noise near −80 dBFS: the first measurement read that, not the EQ.)
    fn tone(a: f32, n: usize) -> Vec<f32> {
        (0..n).map(|i| (a as f64 * (2.0 * std::f64::consts::PI * 1000.0 * i as f64 / FS).sin()) as f32).collect()
    }
    /// The measurement floor: the tone itself (no DSP) through the same analysis.
    fn floor_db(n: usize, lo: usize, hi: usize) -> f64 {
        let hp = hp8(&tone(10f32.powf(-12.0 / 20.0), n));
        20.0 * hp[lo..hi].iter().fold(0.0f64, |m, v| m.max(v.abs())).max(1e-12).log10()
    }

    /// A 1 kHz tone at −12 dBFS through a channel whose band-2 gain steps 0 → +12 dB at 1.0 s (mid-buffer);
    /// returns the click residual: the peak of the 8 kHz-high-passed output around the step, dBFS.
    fn step_residual(fade_len: usize) -> f64 {
        let a = 10f32.powf(-12.0 / 20.0);
        let n = FS as usize * 2;
        let mut l: Vec<f32> = tone(a, n);
        let mut r = l.clone();
        let mut dsp = ChannelDsp::with_fade(fade_len);
        dsp.set(peq_rack(0.001, true).plan(FS));   // a live chain (0.001 dB, i.e. running) before the step
        let buf = 441;
        let step_at = FS as usize;                  // 1.0 s
        let mut k = 0;
        while k < n {
            let e = (k + buf).min(n);
            if k <= step_at + 200 && step_at + 200 < e { /* the step lands mid-buffer */ }
            if k == (step_at / buf) * buf { dsp.set(peq_rack(12.0, true).plan(FS)); }
            dsp.process(&mut l[k..e], &mut r[k..e]);
            k = e;
        }
        let hp = hp8(&l);
        let (lo, hi) = (step_at - 4410, step_at + 8820);   // 0.1 s before to 0.2 s after
        let pk = hp[lo..hi].iter().fold(0.0f64, |m, v| m.max(v.abs()));
        20.0 * pk.max(1e-12).log10()
    }

    #[test]
    fn a_band_gain_step_does_not_click() {
        let smooth = step_residual(EQ_XFADE_FRAMES);
        let hard = step_residual(0);
        let fl = floor_db(FS as usize * 2, FS as usize - 4410, FS as usize + 8820);
        println!("[no-click] 1 kHz −12 dBFS, band 2 +0 → +12 dB step: crossfaded ({} ms, raised cosine) residual {:.1} dBFS · hard switch (the twin) {:.1} dBFS · measurement floor (the tone alone) {:.1} dBFS · bar −80 dBFS",
                 EQ_XFADE_MS, smooth, hard, fl);
        assert!(smooth < -80.0, "the crossfaded step clicked: {:.1} dBFS", smooth);
        assert!(hard > -80.0, "the deliberate-failure twin did NOT click ({:.1} dBFS) — the test cannot see a click", hard);
    }

    #[test]
    fn a_slider_drag_does_not_click() {
        // 30 changes per second (a drag), band 2 swept 0 → +12 dB over 1 s, on the same tone.
        let a = 10f32.powf(-12.0 / 20.0);
        let n = FS as usize * 3;
        let mut l: Vec<f32> = tone(a, n);
        let mut r = l.clone();
        let mut dsp = ChannelDsp::default();
        dsp.set(peq_rack(0.001, true).plan(FS));
        let buf = 441;
        let mut k = 0;
        let mut step = 0;
        while k < n {
            let e = (k + buf).min(n);
            let t = k as f64 / FS;
            if t >= 1.0 && t < 2.0 && (k / buf) % 3 == 0 { step += 1; dsp.set(peq_rack(((t - 1.0) * 12.0) as f32 + 0.001, true).plan(FS)); }
            dsp.process(&mut l[k..e], &mut r[k..e]);
            k = e;
        }
        let hp = hp8(&l);
        let pk = hp[(FS * 0.9) as usize..(FS * 2.2) as usize].iter().fold(0.0f64, |m, v| m.max(v.abs()));
        let db = 20.0 * pk.max(1e-12).log10();
        let fl = floor_db(n, (FS * 0.9) as usize, (FS * 2.2) as usize);
        println!("[no-click] slider drag ({} changes in 1 s, 30/s): residual {:.1} dBFS · measurement floor {:.1} dBFS · bar −80 dBFS", step, db, fl);
        assert!(db < -80.0);
    }

    #[test]
    fn in_out_is_a_dry_wet_fade_and_an_empty_chain_is_inactive() {
        let mut d = ChannelDsp::default();
        assert!(!d.active());
        d.set(peq_rack(6.0, true).plan(FS));
        assert!(d.active());
        let mut l = vec![0.1f32; EQ_XFADE_FRAMES + 10]; let mut r = l.clone();
        d.process(&mut l, &mut r);
        d.set(peq_rack(6.0, false).plan(FS));        // OUT: fade to dry, then inactive
        let mut l2 = vec![0.1f32; EQ_XFADE_FRAMES + 10]; let mut r2 = l2.clone();
        d.process(&mut l2, &mut r2);
        assert!(!d.active(), "after the fade to OUT the channel returns to the exact old path");
    }

    #[test]
    fn a_silent_tail_after_an_active_rack_does_not_stall() {
        // Denormals: the callback runs under FtzScope; this runs the same chain under it and checks the silent
        // tail costs no more per buffer than the tone did (a denormal stall costs 10-100×).
        let _ftz = crate::rt::FtzScope::enter();
        let rack = ChannelRack::from_doc_json(r#"{"v":1,"sections":{"ch":[
            {"module":{"type":"filters","hpf":{"in":true,"freq":16.1},"lpf":{"in":true,"freq":1000}},"in":true},
            {"module":{"type":"peq","bands":[{"freq":50,"gain":12,"width":0.2,"shelf":true},{"freq":1000,"gain":-14,"width":0.2},
              {"freq":3000,"gain":14,"width":3},{"freq":16000,"gain":-14,"width":0.2,"shelf":true}]},"in":true}]}}"#).unwrap();
        let mut d = ChannelDsp::default();
        d.set(rack.plan(FS));
        let buf = 441;
        let time = |d: &mut ChannelDsp, amp: f32, bufs: usize| {
            let mut ns = Vec::with_capacity(bufs);
            for b in 0..bufs {
                let mut l: Vec<f32> = (0..buf).map(|i| amp * ((b * buf + i) as f32 * 0.0712).sin()).collect();
                let mut r = l.clone();
                let t0 = std::time::Instant::now();
                d.process(&mut l, &mut r);
                ns.push(t0.elapsed().as_nanos() as f64);
            }
            ns.sort_by(|a, b| a.partial_cmp(b).unwrap());
            ns[ns.len() / 2]
        };
        let tone = time(&mut d, 0.5, 1000);
        let tail = time(&mut d, 0.0, 1000);
        println!("[denormal] 8 biquads, 441 frames: tone {:.1} µs · silent tail {:.1} µs per buffer (median)", tone / 1000.0, tail / 1000.0);
        assert!(tail < tone * 3.0, "the silent tail stalled: {} vs {} ns", tail, tone);
    }

    #[test]
    fn the_shared_front_is_bit_identical_to_running_both_chains() {
        // Filters stay put while a PEQ shelf moves: the old and new chains share their HPF/LPF front. Run once
        // with sharing (the product) and once computing both chains in full (the reference) — every sample equal.
        let mk = |g: f32| ChannelRack::from_doc_json(&format!(r#"{{"v":1,"sections":{{"ch":[
            {{"module":{{"type":"filters","hpf":{{"in":true,"freq":80}},"lpf":{{"in":true,"freq":12000}}}},"in":true}},
            {{"module":{{"type":"peq","bands":[{{"freq":120,"gain":{g},"width":1,"shelf":true}},{{"freq":900,"gain":-3,"width":1}},
              {{"freq":3000,"gain":2,"width":2}},{{"freq":9000,"gain":-2,"width":1,"shelf":true}}]}},"in":true}}]}}}}"#)).unwrap().plan(FS);
        let run_it = |share: bool| {
            let mut d = ChannelDsp::default();
            d.no_share = !share;
            let n = FS as usize * 3;
            let mut l: Vec<f32> = tone(0.4, n);
            let mut r: Vec<f32> = l.iter().map(|x| -x * 0.7).collect();
            let (mut k, mut j, mut sh) = (0, 0, 0);
            while k < n {
                let e = (k + 441).min(n);
                if j % 7 == 0 { d.set(if (j / 7) % 2 == 0 { mk(3.0) } else { mk(-3.0) }); }
                sh = sh.max(d.shared);
                d.process(&mut l[k..e], &mut r[k..e]);
                k = e; j += 1;
            }
            (l, r, sh)
        };
        let (a, ar, sh) = run_it(true);
        let (b, br, _) = run_it(false);
        let same = a.iter().zip(&b).all(|(x, y)| x.to_bits() == y.to_bits())
            && ar.iter().zip(&br).all(|(x, y)| x.to_bits() == y.to_bits());
        println!("[shared-front] {} leading stages shared during a PEQ fade; 3 s, a change every 7 buffers: bit-identical to both chains in full = {}", sh, same);
        assert!(sh >= 4, "the HPF/LPF front was not shared ({})", sh);
        assert!(same);
    }

    // ── SLICE 6 — dynamics ─────────────────────────────────────────────────────────────────────────────────
    fn comp_rack(thr: f32, makeup: f32, attack: f32) -> ChannelRack {
        ChannelRack::from_doc_json(&format!(r#"{{"v":1,"sections":{{"ch":[{{"module":{{"type":"comp","threshold":{thr},"ratio":4,
            "attack":{attack},"release":150,"makeup":{makeup},"knee":6}},"in":true}}]}}}}"#)).unwrap()
    }
    fn gate_rack(thr: f32, hyst: f32, hold: f32) -> ChannelRack {
        ChannelRack::from_doc_json(&format!(r#"{{"v":1,"sections":{{"ch":[{{"module":{{"type":"gate","threshold":{thr},"ratio":5,
            "depth":15,"attack":1,"hold":{hold},"release":150,"hysteresis":{hyst}}},"in":true}}]}}}}"#)).unwrap()
    }
    /// A 1 kHz −12 dBFS tone through a compressor at the FASTEST attack (0.1 ms — the worst case); at 1.0 s the rack
    /// steps from `a` to `b`. Returns the 8 kHz high-passed residual around the step (dBFS).
    fn dyn_step_residual(fade_len: usize, a: ChannelRack, b: ChannelRack) -> f64 {
        let n = FS as usize * 2;
        let mut l: Vec<f32> = tone(10f32.powf(-12.0 / 20.0), n);
        let mut r = l.clone();
        let mut dsp = ChannelDsp::with_fade(fade_len);
        dsp.set(a.plan(FS));
        let (buf, step_at) = (441, FS as usize);
        let mut k = 0;
        while k < n {
            let e = (k + buf).min(n);
            if k == (step_at / buf) * buf { dsp.set(b.plan(FS)); }
            dsp.process(&mut l[k..e], &mut r[k..e]);
            k = e;
        }
        let hp = hp8(&l);
        let pk = hp[step_at - 4410..step_at + 8820].iter().fold(0.0f64, |m, v| m.max(v.abs()));
        20.0 * pk.max(1e-12).log10()
    }

    #[test]
    fn a_threshold_or_makeup_step_does_not_click() {
        let fl = floor_db(FS as usize * 2, FS as usize - 4410, FS as usize + 8820);
        // threshold −10 → −30 at 4:1 on a −15 dBFS-RMS tone: 0 → 11.25 dB of GR
        let t_smooth = dyn_step_residual(EQ_XFADE_FRAMES, comp_rack(-10.0, 0.0, 0.1), comp_rack(-30.0, 0.0, 0.1));
        let t_hard = dyn_step_residual(0, comp_rack(-10.0, 0.0, 0.1), comp_rack(-30.0, 0.0, 0.1));
        // makeup 0 → +12 dB (no ballistics of its own — only the crossfade smooths it)
        let m_smooth = dyn_step_residual(EQ_XFADE_FRAMES, comp_rack(-30.0, 0.0, 0.1), comp_rack(-30.0, 12.0, 0.1));
        let m_hard = dyn_step_residual(0, comp_rack(-30.0, 0.0, 0.1), comp_rack(-30.0, 12.0, 0.1));
        println!("[dyn-no-click] 1 kHz −12 dBFS, attack 0.1 ms · threshold −10 → −30 (11.25 dB GR step): crossfaded {:.1} dBFS, hard (twin) {:.1} · makeup 0 → +12 dB: crossfaded {:.1}, hard (twin) {:.1} · floor {:.1} · bar −80",
                 t_smooth, t_hard, m_smooth, m_hard, fl);
        assert!(t_smooth < -80.0 && m_smooth < -80.0, "a crossfaded dynamics step clicked");
        assert!(t_hard > -80.0 && m_hard > -80.0, "the twin did not click — the test cannot see a click");
    }

    #[test]
    fn the_gate_does_not_chatter_around_its_threshold() {
        // a 1 kHz tone whose level wanders ±1 dB around the gate's threshold (−30 dBFS peak), 0.5 Hz, for 10 s
        let run = |hyst: f32, hold: f32| -> usize {
            let n = FS as usize * 10;
            let mut l: Vec<f32> = (0..n).map(|i| {
                let t = i as f64 / FS;
                let db = -30.0 + (2.0 * std::f64::consts::PI * 0.5 * t).sin();
                (10f64.powf(db / 20.0) * (2.0 * std::f64::consts::PI * 1000.0 * t).sin()) as f32
            }).collect();
            let mut r = l.clone();
            let mut dsp = ChannelDsp::default();
            dsp.set(gate_rack(-30.0, hyst, hold).plan(FS));
            let (mut k, mut last, mut flips) = (0, false, 0usize);
            while k < n {
                let e = (k + 441).min(n);
                dsp.process(&mut l[k..e], &mut r[k..e]);
                let (_, _, open) = dsp.take_gr();
                if k > 0 && open != last { flips += 1; }
                last = open; k = e;
            }
            flips
        };
        let with = run(3.0, 100.0);
        let without = run(0.0, 0.0);
        println!("[gate-chatter] level wandering ±1 dB around the threshold for 10 s: hysteresis 3 dB + hold 100 ms → {} open/close transition(s) · the twin with neither → {}", with, without);
        assert!(with <= 1, "the gate chattered: {} transitions", with);
        assert!(without > with, "the twin did not chatter — the test cannot see chatter");
    }

    #[test]
    fn the_dynamics_never_allocate() {
        let mut d = ChannelDsp::default();
        let (a, b) = (gate_rack(-45.0, 3.0, 100.0), comp_rack(-20.0, 6.0, 10.0));
        let (pa, pb) = (a.plan(FS), b.plan(FS));
        let mut l = tone(0.3, 441); let mut r = l.clone();
        let a0 = crate::rt::tl_rt_allocs();
        {
            let _rt = crate::rt::RtScope::enter();
            for k in 0..3000 { if k % 7 == 0 { d.set(if (k / 7) % 2 == 0 { pa } else { pb }); } d.process(&mut l, &mut r); let _ = d.take_gr(); }
        }
        let n = crate::rt::tl_rt_allocs() - a0;
        println!("[trap] gate/comp set + process + take_gr × 3000 buffers inside RtScope: {} allocations", n);
        assert_eq!(n, 0);
    }

    #[test]
    fn the_dsp_never_allocates() {
        let mut d = ChannelDsp::default();
        let specs = [peq_rack(6.0, true).plan(FS), peq_rack(-6.0, true).plan(FS), peq_rack(0.0, false).plan(FS)];
        let mut l = vec![0.2f32; 441]; let mut r = l.clone();
        let a0 = crate::rt::tl_rt_allocs();
        for k in 0..3000 {
            let _rt = crate::rt::RtScope::enter();
            d.set(specs[k % 3]);
            d.process(&mut l, &mut r);
        }
        let allocs = crate::rt::tl_rt_allocs() - a0;
        println!("[trap] ChannelDsp set+process × 3000 buffers inside RtScope: {} allocations", allocs);
        assert_eq!(allocs, 0);
    }
}
